# Instructions ----
#' This file follows the format generated by FIMS:::use_testthat_template().
#' Necessary tests include input and output (IO) correctness [IO
#' correctness], edge-case handling [Edge handling], and built-in errors and
#' warnings [Error handling]. See `?FIMS:::use_testthat_template` for more
#' information. Every test should have a @description tag that takes up just
#' one line, which will be used in the bookdown report of {testthat} results.

# get_obj ----
## Setup ----
# Load or prepare any necessary data for testing
if (!file.exists(test_path("fixtures", "fit_age_length_comp.RDS"))) {
  prepare_test_data()
}
## IO correctness ----
test_that("get_obj() works with correct inputs", {
  # Load the test data from an RDS file containing model fits.
  # List all RDS files in the fixtures directory that match the pattern "fit*_.RDS"
  fit_files <- list.files(
    path = test_path("fixtures"),
    pattern = "^fit.*\\.RDS$",
    full.names = TRUE
  )

  expected_names <- c(
    "par", "fn", "gr", "he", "hessian", "method", "retape",
    "env", "report", "simulate"
  )

  # Function to read the RDS file and get obj
  check_obj <- function(fit_file) {
    fit_data <- readRDS(fit_file)
    obj <- get_obj(fit_data)
    #' @description Test that [get_obj()] returns correct output for the obj
    #' slot.
    expect_equal(
      object = obj,
      expected = fit_data@obj
    )
    #' @description Test that [get_obj()] returns correct names for the obj
    #' slot.
    expect_equal(
      object = names(obj),
      expected = expected_names
    )
  }

  # Use purrr::map to apply the function to each file
  result <- purrr::map(fit_files, check_obj)
})

## Edge handling ----
test_that("get_obj() returns correct outputs for edge cases", {
  #' @description Test that [get_obj()] returns an error when given invalid
  #' input.
  expect_error(
    object = get_obj("invalid_input")
  )
})

## Error handling ----
# No built-in errors to test.
