---
title: "Minimal Example for Running a FIMS Model"
output: github_document
vignette: >
  %\VignetteIndexEntry{Minimal Example for Running a FIMS Model}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Introduction
This vignette provides the minimal steps needed to run a Fisheries Integrated Modeling System (FIMS) model.

## Setup
Load the FIMS package and clear memory:
```{r memory, warning=FALSE, message=FALSE}
library(FIMS)
library(ggplot2)

# clear memory
clear()
```

## Data
Load and prepare data:
```{r data}
# Load sample data
data("data1")
# Prepare data for FIMS model
data_4_model <- FIMSFrame(data1)
```

## Parameters
Set up model parameters:
```{r parameters, max.height='100px', attr.output='.numberLines'}
# Define fleet specifications
fleet1 <- survey1 <- list(
  selectivity = list(form = "LogisticSelectivity"),
  data_distribution = c(
    Index = "DlnormDistribution",
    AgeComp = "DmultinomDistribution",
    LengthComp = "DmultinomDistribution"
  )
)

# Create parameters
parameters <- data_4_model |>
  create_default_parameters(
    fleets = list(fleet1 = fleet1, survey1 = survey1)
  )
```

## Initialize and Fit
Initialize FIMS modules and fit the model:
```{r fit, max.height='100px', attr.output='.numberLines', eval=TRUE}
# Run the model without optimization to help ensure a viable model
test_fit <- parameters |>
  initialize_fims(data = data_4_model) |>
  fit_fims(optimize = FALSE)

# Run the  model with optimization
fit <- parameters |>
  initialize_fims(data = data_4_model) |>
  fit_fims(optimize = TRUE)

# Clear memory post-run
clear()
```
