---
title: "FIMS Surplus Production Demo"
output: github_document
vignette: >
  %\VignetteIndexEntry{FIMS Surplus Production Demo}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, eval = FALSE}
devtools::load_all()
```

## Load JABBA model output

```{r, eval = FALSE}
jabba_output <- readRDS("tests/testthat/fixtures/jabba_output.RDS")
jabba_pars <- jabba_output$pars
jabba_biomass <- jabba_output$flqs |> 
dplyr::filter(qname == "biomass") |> dplyr::select(data) |> as.vector()
jabba_expect_depletion <- (jabba_biomass |> unlist() |> unname()) / 
(jabba_pars |>
    dplyr::filter(rownames(jabba_pars) == "K") |> 
    dplyr::select(Median) |> unlist() |> unname())
```

## Setup index and catch data modules

```{r, eval = FALSE}
clear()

nyears <- 70
survey_index <- data_sp |> dplyr::filter(type == "index")
landings <- data_sp |> dplyr::filter(type == "landings")

# create index module
survey_fleet_index <- methods::new(Index, nyears)
    purrr::walk(
    1:nyears,
    \(x) survey_fleet_index$index_data$set(x - 1, survey_index$value[x])
)

# create catch module
fishing_fleet_landings <- methods::new(Landings, nyears)
purrr::walk(
    1:nyears,
    \(x) fishing_fleet_landings$landings_data$set(x - 1, landings$value[x])
)
```

## Setup survey and fishery fleet modules

```{r, eval = FALSE}
# Initialize the fishing fleet module
fishing_fleet <- methods::new(Fleet)

# Set number of years
fishing_fleet$nyears$set(nyears)
fishing_fleet$SetObservedLandingsDataID(fishing_fleet_landings$get_id())

# Intialize the survey module
survey_fleet <- methods::new(Fleet)
survey_fleet$nyears$set(nyears)

# Estimate q
survey_fleet$log_q[1]$value <- log(0.5)
survey_fleet$log_q[1]$estimation_type$set("fixed_effects")

survey_fleet$SetObservedIndexDataID(survey_fleet_index$get_id())
```

## Setup Survey distribution module

```{r, eval = FALSE}
survey_fleet_index_distribution <- methods::new(DlnormDistribution)

# lognormal observation error transformed on the log scale
# Fix sd as currently FIMS does not have prior distribution
survey_fleet_index_distribution$log_sd$resize(nyears)
for (y in 1:nyears) {
    survey_fleet_index_distribution$log_sd[y]$value <- 
         (jabba_pars |> dplyr::filter(rownames(jabba_pars) == "tau2") |> 
        dplyr::select(Median) + jabba_output$settings$SE2[y]) |> sqrt() |> 
        log() |> unlist()
}
survey_fleet_index_distribution$log_sd$set_all_estimable(FALSE)

# Set Data using the IDs from the modules defined above
survey_fleet_index_distribution$set_observed_data(survey_fleet$GetObservedIndexDataID())
survey_fleet_index_distribution$set_distribution_links("data",          
    survey_fleet$log_index_expected$get_id())
```

## Setup production module

```{r, eval=FALSE}
# create depletion module
production <- new(PTDepletion)

# estimate log r and K
r.init <- rlnorm(1, log(0.2), 0.5) # random draw from prior
production$log_r[1]$value <- log(r.init)
production$log_r[1]$estimation_type$set("fixed_effects")

K.init <- rlnorm(1, log(8 * max(landings$value)), 
    (log(1^2+1))) # random draw from prior
production$log_K[1]$value <- log(K.init)
production$log_K[1]$estimation_type$set("fixed_effects")

# Fix to get Schaefer model
production$log_m[1]$value <- log(2)

# Setup depletion
production$logit_depletion$resize(nyears)
for (i in 1:(nyears)) {
    production$logit_depletion[i]$value <- 0
}

production$logit_depletion$set_all_estimable(TRUE)
production$nyears$set(nyears)
```

## Setup production distribution

```{r, eval = FALSE}
production_distribution <- new(DlnormDistribution)

# Fix sd to jabba value as currently FIMS does not have prior distribution
production_distribution$log_sd[1]$value <- log(sqrt(1.177274e-02)) # from jabba output
production_distribution$expected_values$resize(nyears)

# depletion ~ LNormal(log_expected_depletion, sd)
production_distribution$set_distribution_links(
    "random_effects",
    c(production$depletion$get_id(), production$log_expected_depletion$get_id())
)
```

## Setup Priors

```{r, eval=FALSE}
log_r_Prior <- new(DnormDistribution)
log_r_Prior$expected_values[1]$value <- log(0.2)
log_r_Prior$log_sd[1]$value <- log(0.5)
log_r_Prior$set_distribution_links("prior", production$log_r$get_id())

log_K_Prior <- new(DnormDistribution)
log_K_Prior$expected_values[1]$value <- log(8 * max(landings$value))
log_K_Prior$log_sd[1]$value <- log(sqrt(log(1^2+1))) # CV prior = 1
log_K_Prior$set_distribution_links("prior", production$log_K$get_id())
```

## Setup penalties

```{r, eval=FALSE}
biomass_penalty <- new(DnormDistribution)
biomass_penalty$log_sd[1]$value <- log(sqrt(1/1000)) # from jabba
biomass_penalty$set_distribution_links(
    "random_effects", c(production$biomass_penalty$get_id(), production$biomass_expected_penalty$get_id())
)
K_penalty <- new(DnormDistribution)
K_penalty$log_sd[1]$value <- log(sqrt(1/1000)) # from jabba
K_penalty$set_distribution_links(
    "random_effects", c(production$K_penalty$get_id(), production$K_expected_penalty$get_id())
) 
```

## Setup Population module

```{r, eval=FALSE}
population <- new(Population)
population$nyears$set(nyears)
population$nages$set(1) # only one age in surplus production
population$ages$resize(1)
population$ages$set(0, 0) # only one age in surplus production
init_depletion <- jabba_expect_depletion[1]
population$logit_init_depletion[1]$value <- log(init_depletion/(1 - init_depletion))

population$SetDepletionID(production$get_id())
population$AddFleet(fishing_fleet$get_id())
population$AddFleet(survey_fleet$get_id())
```

## Setup Surplus Production Module

```{r, eval=FALSE}
surplus_production <- methods::new(SurplusProduction)
surplus_production$AddPopulation(population$get_id())
```

## Create TMB model

```{r, eval=FALSE}
# Set-up TMB
CreateTMBModel()

# Create parameter list from Rcpp modules
parameters <- list(
    p = get_fixed(),
    re = get_random()
)

obj <- TMB::MakeADFun(
    data = list(), parameters, DLL = "FIMS",
    random = "re" 
)
```

## Fit with tmbstan

```{r, eval=FALSE}
fit <- tmbstan::tmbstan(obj, init =  "best.last.par", iter = 8000)
```


