name: Bug Report
description: Report a bug that causes the existing functionality to differ from what is described in the development plan
title: "[Bug]: "
labels: ["kind: bug", "status: triage_needed"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! By 
        submitting this issue, you agree to follow our 
        [Code of Conduct](https://noaa-fims.github.io/collaborative_workflow/code-of-conduct.html#code-of-conduct).
  - type: textarea
    id: describe
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: To Reproduce
      description: |
        Please include a minimal reproducible example (AKA a reprex). If you
        have not heard of a [reprex](http://reprex.tidyverse.org/) before,
        you can start by reading about them on the [tidyverse
        blog](https://www.tidyverse.org/help/#reprex). Feel free to copy, paste,
        and edit the [demo
        vignette](https://github.com/NOAA-FIMS/FIMS/blob/4539fc4b6e65b901231c4fb66a113bb5b5d54d22/vignettes/fims-demo.Rmd)
        for your reprex.
      placeholder: |
        # insert reprex here
    validations:
      required: false
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
    validations:
      required: false
  - type: dropdown
    id: os
    attributes:
      label: Which OS are you seeing the problem on?
      multiple: true
      options:
        - Windows
        - Mac
        - Linux
        - Other
    validations: 
      required: false
  - type: dropdown
    id: browser
    attributes:
      label: Which browser are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
        - Other
    validations:
      required: false
  - type: input
    id: version
    attributes:
      label: Which version of FIMS are you seeing the problem on?
    validations:
      required: false
  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.
    validations:
      required: false
