# Instructions ----
#' This file follows the format generated by FIMS:::use_testthat_template().
#' Necessary tests include input and output (IO) correctness [IO
#' correctness], edge-case handling [Edge handling], and built-in errors and
#' warnings [Error handling]. See `?FIMS:::use_testthat_template` for more
#' information. Every test should have a @description tag, which can only span
#' one lines, that will be used in the bookdown report of the results from
#' {testthat}. This line can be more than 80 characters.

# get_input ----
## Setup ----
fit_with_optimization_big <- FIMS::fit_with_optimization_big
fit_without_optimization_big <- FIMS:::fit_without_optimization_big

## IO correctness ----
test_that("`get_input()` works with correct inputs", {
  for (fit in list(fit_with_optimization_big, fit_without_optimization_big)) {
    input <- get_input(fit)
    #' @description Test that `get_input()` returns the FIMSFit input slot.
    expect_equal(input, fit@input)
    #' @description Test that `get_input()` returns parameter and model entries.
    expect_named(input, c("parameters", "model"))
  }
})

## Edge handling ----
test_that("`get_input()` returns correct outputs for edge cases", {
  #' @description Test that `get_input()` returns an error when given invalid inputs.
  expect_error(
    object = get_input("invalid_input")
  )
})

## Error handling ----
# No built-in errors to test.
