# Instructions ----
#' This file follows the format generated by FIMS:::use_testthat_template().
#' Necessary tests include input and output (IO) correctness [IO
#' correctness], edge-case handling [Edge handling], and built-in errors and
#' warnings [Error handling]. See `?FIMS:::use_testthat_template` for more
#' information. Every test should have a @description tag, which can only span
#' one lines, that will be used in the bookdown report of the results from
#' {testthat}. This line can be more than 80 characters.

# integration_unfished_equilibrium ----
## Setup ----
testthat::skip_if(
  Sys.getenv("RUN_SLOW_TESTS") != "true",
  "Skipping: RUN_SLOW_TESTS is not set to true."
)

# data_big has the same natural mortality at every age and year, so unfished
# numbers at age have a closed form and do not change from year to year.
data("data_big")
data_4_model <- FIMSFrame(data_big)
parameters <- setup_default_parameters(data = data_4_model)
fit <- parameters |>
  initialize_fims(data = data_4_model) |>
  fit_fims(optimize = FALSE)
# get_report() holds the values at full precision; get_estimates() rounds some
report <- get_report(fit)
clear()

get_input <- function(x) {
  dplyr::filter(parameters, label == x)[["value"]]
}
r0 <- exp(get_input("log_rzero"))
m <- exp(unique(get_input("log_M")))
n_ages <- get_n_ages(data_4_model)
unfished_numbers <- report[["unfished_numbers_at_age"]][[1]]
unfished_spawning_biomass <- report[["unfished_spawning_biomass"]][[1]]

## IO correctness ----
test_that("unfished numbers at age start at the equilibrium age structure", {
  #' @description Test that the setup has a single natural mortality, which the closed form below assumes.
  expect_length(m, 1)

  # R0 * exp(-M * a) for ages before the plus group and
  # R0 * exp(-M * A) / (1 - exp(-M)) for the plus group A
  expected <- r0 * exp(-m * (seq_len(n_ages) - 1))
  expected[n_ages] <- expected[n_ages] / (1 - exp(-m))

  #' @description Test that first-year unfished numbers at age equal the closed-form equilibrium, including the plus group.
  expect_equal(
    object = unfished_numbers[seq_len(n_ages)],
    expected = expected,
    tolerance = 1e-8
  )
})

test_that("unfished spawning biomass is constant when natural mortality is", {
  #' @description Test that unfished spawning biomass is the same in every year when natural mortality does not vary.
  expect_equal(
    object = unfished_spawning_biomass,
    expected = rep(unfished_spawning_biomass[1], length(unfished_spawning_biomass)),
    tolerance = 1e-8
  )

  #' @description Test that the spawning biomass ratio divides spawning biomass by first-year unfished spawning biomass.
  spawning_biomass <- report[["spawning_biomass"]][[1]]
  expect_equal(
    object = report[["spawning_biomass_ratio"]][[1]],
    expected = spawning_biomass / unfished_spawning_biomass[1],
    tolerance = 1e-8
  )
})
