# Instructions ----
#' This file follows the format generated by FIMS:::use_testthat_template().
#' Necessary tests include input and output (IO) correctness [IO
#' correctness], edge-case handling [Edge handling], and built-in errors and
#' warnings [Error handling]. See `?FIMS:::use_testthat_template` for more
#' information. Every test should have a @description tag that takes up just
#' one line, which will be used in the bookdown report of {testthat} results.

# Deterministic test ----
## Setup ----
# Load necessary data for the integration test
load(test_path("fixtures", "integration_test_data.RData"))

# Set the iteration ID to 1 for accessing specific input/output list
iter_id <- 1

# Run FIMS without wrappers
result <- setup_and_run_FIMS_without_wrappers(
  iter_id = iter_id,
  om_input_list = om_input_list,
  om_output_list = om_output_list,
  em_input_list = em_input_list,
  estimation_mode = FALSE
)

## IO correctness ----
test_that("deterministic run works with correct inputs", {
  #' @description Compare FIMS results with model comparison project OM values.
  verify_fims_deterministic(
    report = result[["report"]],
    estimates = result[["sdr_fixed"]],
    om_input = om_input_list[[iter_id]],
    om_output = om_output_list[[iter_id]],
    em_input = em_input_list[[iter_id]],
    use_fimsfit = FALSE
  )

  #' @description Compare FIMS results with model comparison project OM values.
  verify_fims_nll(
    report = result[["report"]],
    om_input = om_input_list[[iter_id]],
    om_output = om_output_list[[iter_id]],
    em_input = em_input_list[[iter_id]]
  )

  #' @description Verify the number of parameters is correct for deterministic
  #' run.
  #' TODO: change parameter number to 77 after fixing log_devs estimation error
  expect_equal(length(result[["obj"]][["par"]]), 48)
})

## Edge handling ----
# No edge cases to test.

## Error handling ----
# No built-in errors to test.

# Estimation test ----
## Setup ----
result <- setup_and_run_FIMS_without_wrappers(
  iter_id = iter_id,
  om_input_list = om_input_list,
  om_output_list = om_output_list,
  em_input_list = em_input_list,
  estimation_mode = TRUE
)
## IO correctness ----
# Compare FIMS results with model comparison project OM values
## IO correctness ----
test_that("deterministic run works with correct inputs", {
  #' @description Compare FIMS results with model comparison project OM values
  #' in a non-deterministic run with age- and length-composition data.
  validate_fims(
    report = result[["report"]],
    estimates = result[["sdr_report"]],
    om_input = om_input_list[[iter_id]],
    om_output = om_output_list[[iter_id]],
    em_input = em_input_list[[iter_id]]
  )
})

## Edge handling ----
test_that("run FIMS and return correct outputs for edge cases", {
  # Introduce a missing value in survey observations for the EM input
  na_value <- -999
  na_index <- 2
  em_input_list[[iter_id]][["surveyB.obs"]][["survey1"]][na_index] <- na_value

  # Run the FIMS setup and execution function
  result <- setup_and_run_FIMS_without_wrappers(
    iter_id = iter_id,
    om_input_list = om_input_list,
    om_output_list = om_output_list,
    em_input_list = em_input_list,
    estimation_mode = TRUE
  )

  #' @description Test that FIMS runs with missing values in survey index
  #' observations using NA (missing value) placeholder in the second value and
  #' the report is not NULL.
  expect_false(is.null(result[["report"]]))

  # Obtain the gradient and Hessian matrix
  g <- as.numeric(result[["obj"]][["gr"]](result[["opt"]][["par"]]))
  h <- optimHess(
    result[["opt"]][["par"]],
    fn = result[["obj"]][["fn"]],
    gr = result[["obj"]][["gr"]]
  )
  result[["opt"]][["par"]] <- result[["opt"]][["par"]] - solve(h, g)
  max_gradient <- max(abs(result[["obj"]][["gr"]](result[["opt"]][["par"]])))

  #' @description Test that the maximum gradient is less than or equal to 0.0001
  #' after running FIMS with missing values in survey index observations.
  #'   # Obtain the maximum absolute gradient to check convergence
  expect_lte(max_gradient, 0.0001)

  #' @description Test that running FIMS with age compositions in proportions
  #' works.
  # Store the original values of the number of landings observations and
  # survey observations
  n.L_original <- om_input_list[[iter_id]][["n.L"]][["fleet1"]]
  n.survey_original <- om_input_list[[iter_id]][["n.survey"]][["survey1"]]

  # Set the number of landings observations and survey observations to 1
  om_input_list[[iter_id]][["n.L"]][["fleet1"]] <- 1
  om_input_list[[iter_id]][["n.survey"]][["survey1"]] <- 1
  on.exit(
    om_input_list[[iter_id]][["n.L"]][["fleet1"]] <- n.L_original,
    add = TRUE
  )
  on.exit(
    om_input_list[[iter_id]][["n.survey"]][["survey1"]] <- n.survey_original,
    add = TRUE
  )

  # Run the FIMS setup and execution function
  result <- setup_and_run_FIMS_without_wrappers(
    iter_id = iter_id,
    om_input_list = om_input_list,
    om_output_list = om_output_list,
    em_input_list = em_input_list,
    estimation_mode = TRUE
  )

  # Compare FIMS results with model comparison project OM values
  validate_fims(
    report = result[["report"]],
    estimates = result[["sdr_report"]],
    om_input = om_input_list[[iter_id]],
    om_output = om_output_list[[iter_id]],
    em_input = em_input_list[[iter_id]]
  )
})

## Error handling ----
# No built-in errors to test.
