# Instructions ----
#' This file follows the format generated by FIMS:::use_testthat_template().
#' Necessary tests include input and output (IO) correctness [IO
#' correctness], edge-case handling [Edge handling], and built-in errors and
#' warnings [Error handling]. See `?FIMS:::use_testthat_template` for more
#' information. Every test should have a @description tag, which can only span
#' one lines, that will be used in the bookdown report of the results from
#' {testthat}. This line can be more than 80 characters.

# rcpp models ----
## Setup ----
n_years <- 10
n_ages <- 5
n_lengths <- 8

## IO correctness ----

### CatchAtAgePopulationDerivedQuantities ----
test_that("CatchAtAgePopulationDerivedQuantities Initialize resizes all fields correctly", {
  pop_dq <- methods::new(CatchAtAgePopulationDerivedQuantities)
  pop_dq$Initialize(n_years, n_ages)

  #' @description Test that Initialize resizes total_landings_weight to n_years.
  expect_equal(length(pop_dq$total_landings_weight), n_years)
  #' @description Test that Initialize resizes total_landings_numbers to n_years.
  expect_equal(length(pop_dq$total_landings_numbers), n_years)
  #' @description Test that Initialize resizes mortality_F to n_years * n_ages.
  expect_equal(length(pop_dq$mortality_F), n_years * n_ages)
  #' @description Test that Initialize resizes mortality_M to n_years * n_ages.
  expect_equal(length(pop_dq$mortality_M), n_years * n_ages)
  #' @description Test that Initialize resizes mortality_Z to n_years * n_ages.
  expect_equal(length(pop_dq$mortality_Z), n_years * n_ages)
  #' @description Test that Initialize resizes numbers_at_age to (n_years + 1) * n_ages.
  expect_equal(length(pop_dq$numbers_at_age), (n_years + 1) * n_ages)
  #' @description Test that Initialize resizes unfished_numbers_at_age to (n_years + 1) * n_ages.
  expect_equal(length(pop_dq$unfished_numbers_at_age), (n_years + 1) * n_ages)
  #' @description Test that Initialize resizes biomass to n_years + 1.
  expect_equal(length(pop_dq$biomass), n_years + 1)
  #' @description Test that Initialize resizes spawning_biomass to n_years + 1.
  expect_equal(length(pop_dq$spawning_biomass), n_years + 1)
  #' @description Test that Initialize resizes unfished_biomass to n_years + 1.
  expect_equal(length(pop_dq$unfished_biomass), n_years + 1)
  #' @description Test that Initialize resizes unfished_spawning_biomass to n_years + 1.
  expect_equal(length(pop_dq$unfished_spawning_biomass), n_years + 1)
  #' @description Test that Initialize resizes proportion_mature_at_age to (n_years + 1) * n_ages.
  expect_equal(length(pop_dq$proportion_mature_at_age), (n_years + 1) * n_ages)
  #' @description Test that Initialize resizes expected_recruitment to n_years + 1.
  expect_equal(length(pop_dq$expected_recruitment), n_years + 1)
  #' @description Test that Initialize resizes sum_selectivity to n_years * n_ages.
  expect_equal(length(pop_dq$sum_selectivity), n_years * n_ages)

  clear()
})

test_that("CatchAtAgePopulationDerivedQuantities Fill sets all fields to the given value", {
  pop_dq <- methods::new(CatchAtAgePopulationDerivedQuantities)
  pop_dq$Initialize(n_years, n_ages)
  fill_value <- 3.14
  pop_dq$Fill(fill_value)

  #' @description Test that Fill sets all total_landings_weight values to fill_value.
  for (i in 1:n_years) {
    expect_equal(pop_dq$total_landings_weight[i]$value, fill_value)
  }
  #' @description Test that Fill sets all mortality_F values to fill_value.
  for (i in 1:(n_years * n_ages)) {
    expect_equal(pop_dq$mortality_F[i]$value, fill_value)
  }
  #' @description Test that Fill sets all biomass values to fill_value.
  for (i in 1:(n_years + 1)) {
    expect_equal(pop_dq$biomass[i]$value, fill_value)
  }
  #' @description Test that Fill sets all numbers_at_age values to fill_value.
  for (i in 1:((n_years + 1) * n_ages)) {
    expect_equal(pop_dq$numbers_at_age[i]$value, fill_value)
  }

  clear()
})

test_that("CatchAtAgePopulationDerivedQuantities Fill defaults to 0.0", {
  pop_dq <- methods::new(CatchAtAgePopulationDerivedQuantities)
  pop_dq$Initialize(n_years, n_ages)
  pop_dq$Fill(3.14)
  #' @description Test that Fill with no arguments resets all total_landings_weight values to 0.
  pop_dq$Fill()
  for (i in 1:n_years) {
    expect_equal(pop_dq$total_landings_weight[i]$value, 0.0)
  }
  #' @description Test that Fill with no arguments resets all spawning_biomass values to 0.
  for (i in 1:(n_years + 1)) {
    expect_equal(pop_dq$spawning_biomass[i]$value, 0.0)
  }

  clear()
})

### CatchAtAgeFleetDerivedQuantities ----
test_that("CatchAtAgeFleetDerivedQuantities Initialize resizes all fields correctly", {
  fleet_dq <- methods::new(CatchAtAgeFleetDerivedQuantities)
  fleet_dq$Initialize(n_years, n_ages, n_lengths)

  #' @description Test that Initialize resizes landings_numbers_at_age to n_years * n_ages.
  expect_equal(length(fleet_dq$landings_numbers_at_age), n_years * n_ages)
  #' @description Test that Initialize resizes landings_weight_at_age to n_years * n_ages.
  expect_equal(length(fleet_dq$landings_weight_at_age), n_years * n_ages)
  #' @description Test that Initialize resizes landings_numbers_at_length to n_years * n_lengths.
  expect_equal(length(fleet_dq$landings_numbers_at_length), n_years * n_lengths)
  #' @description Test that Initialize resizes landings_weight to n_years.
  expect_equal(length(fleet_dq$landings_weight), n_years)
  #' @description Test that Initialize resizes landings_numbers to n_years.
  expect_equal(length(fleet_dq$landings_numbers), n_years)
  #' @description Test that Initialize resizes landings_expected to n_years.
  expect_equal(length(fleet_dq$landings_expected), n_years)
  #' @description Test that Initialize resizes log_landings_expected to n_years.
  expect_equal(length(fleet_dq$log_landings_expected), n_years)
  #' @description Test that Initialize resizes agecomp_proportion to n_years * n_ages.
  expect_equal(length(fleet_dq$agecomp_proportion), n_years * n_ages)
  #' @description Test that Initialize resizes lengthcomp_proportion to n_years * n_lengths.
  expect_equal(length(fleet_dq$lengthcomp_proportion), n_years * n_lengths)
  #' @description Test that Initialize resizes index_numbers_at_age to n_years * n_ages.
  expect_equal(length(fleet_dq$index_numbers_at_age), n_years * n_ages)
  #' @description Test that Initialize resizes index_weight_at_age to n_years * n_ages.
  expect_equal(length(fleet_dq$index_weight_at_age), n_years * n_ages)
  #' @description Test that Initialize resizes index_numbers_at_length to n_years * n_lengths.
  expect_equal(length(fleet_dq$index_numbers_at_length), n_years * n_lengths)
  #' @description Test that Initialize resizes index_weight to n_years.
  expect_equal(length(fleet_dq$index_weight), n_years)
  #' @description Test that Initialize resizes index_numbers to n_years.
  expect_equal(length(fleet_dq$index_numbers), n_years)
  #' @description Test that Initialize resizes index_expected to n_years.
  expect_equal(length(fleet_dq$index_expected), n_years)
  #' @description Test that Initialize resizes log_index_expected to n_years.
  expect_equal(length(fleet_dq$log_index_expected), n_years)
  #' @description Test that Initialize resizes catch_index to n_years.
  expect_equal(length(fleet_dq$catch_index), n_years)
  #' @description Test that Initialize resizes expected_catch to n_years.
  expect_equal(length(fleet_dq$expected_catch), n_years)
  #' @description Test that Initialize resizes expected_index to n_years.
  expect_equal(length(fleet_dq$expected_index), n_years)
  #' @description Test that Initialize resizes agecomp_expected to n_years * n_ages.
  expect_equal(length(fleet_dq$agecomp_expected), n_years * n_ages)
  #' @description Test that Initialize resizes lengthcomp_expected to n_years * n_lengths.
  expect_equal(length(fleet_dq$lengthcomp_expected), n_years * n_lengths)

  clear()
})

test_that("CatchAtAgeFleetDerivedQuantities Fill sets all fields to the given value", {
  fleet_dq <- methods::new(CatchAtAgeFleetDerivedQuantities)
  fleet_dq$Initialize(n_years, n_ages, n_lengths)
  fill_value <- 2.71
  fleet_dq$Fill(fill_value)

  #' @description Test that Fill sets all landings_weight values to fill_value.
  for (i in 1:n_years) {
    expect_equal(fleet_dq$landings_weight[i]$value, fill_value)
  }
  #' @description Test that Fill sets all landings_numbers_at_age values to fill_value.
  for (i in 1:(n_years * n_ages)) {
    expect_equal(fleet_dq$landings_numbers_at_age[i]$value, fill_value)
  }
  #' @description Test that Fill sets all agecomp_expected values to fill_value.
  for (i in 1:(n_years * n_ages)) {
    expect_equal(fleet_dq$agecomp_expected[i]$value, fill_value)
  }
  #' @description Test that Fill sets all index_expected values to fill_value.
  for (i in 1:n_years) {
    expect_equal(fleet_dq$index_expected[i]$value, fill_value)
  }

  clear()
})

test_that("CatchAtAgeFleetDerivedQuantities Fill defaults to 0.0", {
  fleet_dq <- methods::new(CatchAtAgeFleetDerivedQuantities)
  fleet_dq$Initialize(n_years, n_ages, n_lengths)
  fleet_dq$Fill(2.71)
  #' @description Test that Fill with no arguments resets all landings_weight values to 0.
  fleet_dq$Fill()
  for (i in 1:n_years) {
    expect_equal(fleet_dq$landings_weight[i]$value, 0.0)
  }
  #' @description Test that Fill with no arguments resets all agecomp_proportion values to 0.
  for (i in 1:(n_years * n_ages)) {
    expect_equal(fleet_dq$agecomp_proportion[i]$value, 0.0)
  }

  clear()
})

### CatchAtAge ----
test_that("CatchAtAge constructor and GetId work correctly", {
  caa <- methods::new(CatchAtAge)
  #' @description Test that GetId returns 1 for the first CatchAtAge instance.
  expect_equal(caa$GetId(), 1)
  clear()
})

test_that("CatchAtAge AddPopulation runs without error for a valid or missing population id", {
  caa <- methods::new(CatchAtAge)
  #' @description Test that AddPopulation does not throw when called with a population id that has no corresponding live object (logs internally instead).
  expect_no_error(caa$AddPopulation(1))
  clear()
})

test_that("CatchAtAge IsReporting returns FALSE without an active TMB model", {
  caa <- methods::new(CatchAtAge)
  #' @description Test that IsReporting returns FALSE when no TMB model has been initialized.
  expect_false(caa$IsReporting())
  clear()
})

test_that("CatchAtAge InitializePopulationDerivedQuantities and GetPopulationDerivedQuantities work correctly", {
  caa <- methods::new(CatchAtAge)

  #' @description Test that InitializePopulationDerivedQuantities runs silently.
  expect_silent(caa$InitializePopulationDerivedQuantities(1, n_years, n_ages))

  pop_dq <- caa$GetPopulationDerivedQuantities(1)
  #' @description Test that GetPopulationDerivedQuantities returns an object with total_landings_weight sized to n_years.
  expect_equal(length(pop_dq$total_landings_weight), n_years)
  #' @description Test that GetPopulationDerivedQuantities returns an object with mortality_F sized to n_years * n_ages.
  expect_equal(length(pop_dq$mortality_F), n_years * n_ages)
  #' @description Test that GetPopulationDerivedQuantities returns an object with numbers_at_age sized to (n_years + 1) * n_ages.
  expect_equal(length(pop_dq$numbers_at_age), (n_years + 1) * n_ages)
  #' @description Test that GetPopulationDerivedQuantities returns an object with biomass sized to n_years + 1.
  expect_equal(length(pop_dq$biomass), n_years + 1)
  #' @description Test that GetPopulationDerivedQuantities returns an object with expected_recruitment sized to n_years + 1.
  expect_equal(length(pop_dq$expected_recruitment), n_years + 1)

  clear()
})

test_that("CatchAtAge InitializeFleetDerivedQuantities and GetFleetDerivedQuantities work correctly", {
  caa <- methods::new(CatchAtAge)

  #' @description Test that InitializeFleetDerivedQuantities runs silently.
  expect_silent(caa$InitializeFleetDerivedQuantities(1, n_years, n_ages, n_lengths))

  fleet_dq <- caa$GetFleetDerivedQuantities(1)
  #' @description Test that GetFleetDerivedQuantities returns an object with landings_numbers_at_age sized to n_years * n_ages.
  expect_equal(length(fleet_dq$landings_numbers_at_age), n_years * n_ages)
  #' @description Test that GetFleetDerivedQuantities returns an object with landings_weight sized to n_years.
  expect_equal(length(fleet_dq$landings_weight), n_years)
  #' @description Test that GetFleetDerivedQuantities returns an object with agecomp_proportion sized to n_years * n_ages.
  expect_equal(length(fleet_dq$agecomp_proportion), n_years * n_ages)
  #' @description Test that GetFleetDerivedQuantities returns an object with index_numbers_at_length sized to n_years * n_lengths.
  expect_equal(length(fleet_dq$index_numbers_at_length), n_years * n_lengths)
  #' @description Test that GetFleetDerivedQuantities returns an object with expected_catch sized to n_years.
  expect_equal(length(fleet_dq$expected_catch), n_years)

  clear()
})

## Edge handling ----
test_that("CatchAtAge GetPopulationDerivedQuantities after AddPopulation initializes the entry", {
  caa <- methods::new(CatchAtAge)
  caa$AddPopulation(1)
  caa$InitializePopulationDerivedQuantities(1, n_years, n_ages)

  pop_dq <- caa$GetPopulationDerivedQuantities(1)
  #' @description Test that GetPopulationDerivedQuantities works after AddPopulation and Initialize and returns correctly sized spawning_biomass.
  expect_equal(length(pop_dq$spawning_biomass), n_years + 1)

  clear()
})

## Error handling ----
test_that("CatchAtAge returns errors for unregistered derived quantity IDs", {
  caa <- methods::new(CatchAtAge)

  #' @description Test that GetPopulationDerivedQuantities throws when the population_id has not been initialized.
  expect_error(caa$GetPopulationDerivedQuantities(99))
  #' @description Test that GetFleetDerivedQuantities throws when the fleet_id has not been initialized.
  expect_error(caa$GetFleetDerivedQuantities(99))

  clear()
})
