# Instructions ----
#' This file follows the format generated by FIMS:::use_testthat_template().
#' Necessary tests include input and output (IO) correctness [IO
#' correctness], edge-case handling [Edge handling], and built-in errors and
#' warnings [Error handling]. See `?FIMS:::use_testthat_template` for more
#' information. Every test should have a @description tag that takes up just
#' one line, which will be used in the bookdown report of {testthat} results.

# Setup ----
data <- FIMS::FIMSFrame(data1)

fleet1 <- survey1 <- list(
  selectivity = list(form = "LogisticSelectivity"),
  data_distribution = c(
    Index = "DlnormDistribution",
    AgeComp = "DmultinomDistribution"
  )
)

fleets <- list(fleet1 = fleet1, survey1 = survey1)

# create_default_parameters() ----
## IO correctness ----
test_that("create_default_parameters() returns correct structure", {
  result <- create_default_parameters(data, fleets = fleets)

  expect_named(result, c("parameters", "modules"))
  expect_type(result[["parameters"]], "list")
  expect_type(result[["modules"]], "list")
  expect_named(result[["modules"]], c("fleets", "recruitment", "growth", "maturity"))
})

## Edge handling ----


## Error handling ----
test_that("create_default_parameters() returns correct error messages", {
  #' @description Test that create_default_parameters() detects missing fleet
  #' names.
  invalid_fleet <- list(
    selectivity = list(form = "LogisticSelectivity"),
    data_distribution = c(
      Index = "DlnormDistribution",
      AgeComp = "DmultinomDistribution"
    )
  )

  invalid_fleets <- list(
    fleet1 = fleet1,
    survey1 = survey1,
    invalid_fleet = invalid_fleet
  )

  expect_error(
    create_default_parameters(data, invalid_fleets),
    "The following 1 fleet name is missing from the data: invalid_fleet"
  )

  #' @description Test that create_default_parameters() returns error because
  #' input list is `NULL`.
  empty_data <- NULL

  expect_error(create_default_parameters(empty_data, fleets = fleets))
})
