# Instructions ----
#' This file follows the format generated by FIMS:::use_testthat_template().
#' Necessary tests include input and output (IO) correctness [IO
#' correctness], edge-case handling [Edge handling], and built-in errors and
#' warnings [Error handling]. See `?FIMS:::use_testthat_template` for more
#' information. Every test should have a @description tag that takes up just
#' one line, which will be used in the bookdown report of {testthat} results.

# Deterministic test ----
## Setup ----
# Load necessary data for the integration test
load(test_path("fixtures", "integration_test_data.RData"))

# Set the iteration ID to 1 for accessing specific input/output list
iter_id <- 1

# Run FIMS without wrappers
result <- setup_and_run_FIMS_without_wrappers(
  iter_id = iter_id,
  om_input_list = om_input_list,
  om_output_list = om_output_list,
  em_input_list = em_input_list,
  estimation_mode = FALSE
)

## IO correctness ----
test_that("deterministic run works with correct inputs", {
  # Compare FIMS results with model comparison project OM values
  verify_fims_deterministic(
    report = result[["report"]],
    estimates = result[["sdr_fixed"]],
    om_input = om_input_list[[iter_id]],
    om_output = om_output_list[[iter_id]],
    em_input = em_input_list[[iter_id]],
    use_fimsfit = FALSE
  )
})

test_that("deterministic run returns correct nlls", {
  #' Compare FIMS NLLs with model comparison project "true" NLLs
  verify_fims_nll(
    report = result[["report"]],
    om_input = om_input_list[[iter_id]],
    om_output = om_output_list[[iter_id]],
    em_input = em_input_list[[iter_id]]
  )
})

## Edge handling ----
# No edge cases to test.

## Error handling ----
# No built-in errors to test.

# Estimation test ----
## Setup ----
result <- setup_and_run_FIMS_without_wrappers(
  iter_id = iter_id,
  om_input_list = om_input_list,
  om_output_list = om_output_list,
  em_input_list = em_input_list,
  estimation_mode = TRUE
)
## IO correctness ----
# Compare FIMS results with model comparison project OM values
test_that("estimation test with age and length comp", {
  validate_fims(
    report = result[["report"]],
    estimates = result[["sdr_report"]],
    om_input = om_input_list[[iter_id]],
    om_output = om_output_list[[iter_id]],
    em_input = em_input_list[[iter_id]]
  )
})

## Edge handling ----
test_that("run FIMS with missing values", {
  # Define the NA (missing value) placeholder and the index where it will be inserted
  na_value <- -999
  na_index <- 2

  # Introduce a missing value into the survey observations for the estimation model input
  em_input_list[[iter_id]][["surveyB.obs"]][["survey1"]][na_index] <- na_value

  # Run the FIMS setup and execution function
  result <- setup_and_run_FIMS_without_wrappers(
    iter_id = iter_id,
    om_input_list = om_input_list,
    om_output_list = om_output_list,
    em_input_list = em_input_list,
    estimation_mode = TRUE
  )

  # Validate that the result report is not null
  expect_false(is.null(result[["report"]]))

  # Obtain the gradient and Hessian matrix
  g <- as.numeric(result[["obj"]][["gr"]](result[["opt"]][["par"]]))
  h <- optimHess(result[["opt"]][["par"]], fn = result[["obj"]][["fn"]], gr = result[["obj"]][["gr"]])
  result[["opt"]][["par"]] <- result[["opt"]][["par"]] - solve(h, g)

  # Obtain the maximum absolute gradient to check convergence
  # Ensure that the maximum gradient is less than or equal to
  # the specified tolerance (0.0001)
  max_gradient <- max(abs(result[["obj"]][["gr"]](result[["opt"]][["par"]])))
  expect_lte(max_gradient, 0.0001)
})

test_that("agecomp in proportion works", {
  # Store the original values of the number of landings observations and
  # survey observations
  n.L_original <- om_input_list[[iter_id]][["n.L"]][["fleet1"]]
  n.survey_original <- om_input_list[[iter_id]][["n.survey"]][["survey1"]]

  # Set the number of landings observations and survey observations to 1
  om_input_list[[iter_id]][["n.L"]][["fleet1"]] <- 1
  om_input_list[[iter_id]][["n.survey"]][["survey1"]] <- 1
  on.exit(om_input_list[[iter_id]][["n.L"]][["fleet1"]] <- n.L_original, add = TRUE)
  on.exit(om_input_list[[iter_id]][["n.survey"]][["survey1"]] <- n.survey_original, add = TRUE)

  # Run the FIMS setup and execution function
  result <- setup_and_run_FIMS_without_wrappers(
    iter_id = iter_id,
    om_input_list = om_input_list,
    om_output_list = om_output_list,
    em_input_list = em_input_list,
    estimation_mode = TRUE
  )

  # Compare FIMS results with model comparison project OM values
  validate_fims(
    report = result[["report"]],
    estimates = result[["sdr_report"]],
    om_input = om_input_list[[iter_id]],
    om_output = om_output_list[[iter_id]],
    em_input = em_input_list[[iter_id]]
  )
})

## Error handling ----
# No built-in errors to test.
