# Instructions ----
#' This file follows the format generated by FIMS:::use_testthat_template().
#' Necessary tests include input and output (IO) correctness [IO
#' correctness], edge-case handling [Edge handling], and built-in errors and
#' warnings [Error handling]. See `?FIMS:::use_testthat_template` for more
#' information. Every test should have a @description tag, which can span
#' multiple lines, that will be used in the bookdown report of the results from
#' {testthat}.

# create_default_configurations ----
## Setup ----
# Load or prepare any necessary data for testing
data("data1")
data_age_length <- FIMSFrame(data1)

## IO correctness ----
test_that("create_default_configurations() works with correct inputs", {
  expected_names <- c("model_family", "module_name", "fleet_name", "data")
  default_configurations <- create_default_configurations(data_age_length)

  #' @description Test that create_default_configurations(data_age_length)
  #' returns a tibble with correct column names.
  expect_equal(
    object = colnames(default_configurations),
    expected = expected_names
  )

  expected_names_unnested <- c(
    "model_family", "module_name", "fleet_name", "module_type",
    "distribution_link", "distribution_type", "distribution"
  )
  default_configurations_unnested <- default_configurations |>
    tidyr::unnest(cols = data)

  #' @description Test that unnested default_configurations
  #' has correct column names.
  expect_equal(
    object = colnames(default_configurations_unnested),
    expected = expected_names_unnested
  )

  #' @description Test that create_default_configurations(data_age_length)
  #' returns a tibble with "catch_at_age" as model_family.
  expect_equal(
    object = unique(default_configurations_unnested[["model_family"]]),
    expected = "catch_at_age"
  )

  expect_snapshot_file(save_csv(default_configurations_unnested), "default_configurations.csv")
})

## Edge handling ----
# Please remove/comment out the test template below if no edge cases are being tested.
test_that("create_default_configurations() returns correct outputs for edge cases", {
  # Load the test data from an RDS file containing model fits.
  if (!file.exists(test_path("fixtures", "data_length_comp.RDS"))) {
    prepare_test_data()
  }

  # List all RDS files in the fixtures directory that match the pattern "data*_.RDS"
  data_files <- list.files(
    path = test_path("fixtures"),
    pattern = "^data.*\\.RDS$",
    full.names = TRUE
  )

  # Function to read the RDS file, get fits, and check column names
  check_colnames <- function(data_file) {
    data <- readRDS(data_file)
    configurations <- create_default_configurations(data) |>
      tidyr::unnest(cols = data)
    expected_names <- colnames(configurations)
    #' @description Test that [create_default_configurations()] returns correct
    #' column names.
    expect_equal(
      object = colnames(configurations),
      expected = expected_names
    )

    if (data_file == test_path("fixtures", "data_age_comp_na.RDS")) {
      module_types <- configurations |>
        dplyr::pull(module_type) |>
        unique()
      #' @description Test that AgeComp exists in the age only data configurations.
      expect_true("AgeComp" %in% module_types)
      
      #' @description Test that LengthComp does not exist in the age only data configurations.
      expect_true(!("LengthComp" %in% module_types))
    }

    if (data_file == test_path("fixtures", "data_length_comp_na.RDS")) {
      module_types <- configurations |>
        dplyr::pull(module_type) |>
        unique()
      #' @description Test that LengthComp exists in the length only data configurations.
      expect_true("LengthComp" %in% module_types)

      #' @description Test that AgeComp does not exist in the length only data configurations.
      expect_true(!("AgeComp" %in% module_types))
    }
  }

  # Use purrr::map to apply the function to each file
  result <- purrr::map(data_files, check_colnames)
})

## Error handling ----
# Please remove/comment out the test template below if there are no built-in errors/warnings.
test_that("create_default_configurations() returns correct error messages", {
  #' @description Test that the function aborts with a specific error message
  #' if the input object is not a `FIMSFrame`. Using a standard data frame
  #' to trigger the error.
  expect_error(
    create_default_configurations(data = data.frame(a = 1)),
    regexp = "`data` must be a"
  )

  #' @description Test that the function aborts with a specific error message
  #' if the model_family is not valid.
  expect_error(
    create_default_configurations(
      data = data_age_length,
      model_family = "invalid_family"
    )
  )
})
