# Instructions ----
#' This file follows the format generated by FIMS:::use_testthat_template().
#' Necessary tests include input and output (IO) correctness [IO
#' correctness], edge-case handling [Edge handling], and built-in errors and
#' warnings [Error handling]. See `?FIMS:::use_testthat_template` for more
#' information. Every test should have a @description tag, which can only span
#' one lines, that will be used in the bookdown report of the results from
#' {testthat}. This line can be more than 80 characters.

# Setup ----
# Load or prepare any necessary data for testing

# get_fixed ----
## IO correctness ----
test_that("`get_fixed()` works with correct inputs", {
  clear()
  # Create selectivity
  selectivity <- create_selectivity("Logistic")
  set_variable_vector(selectivity, "inflection_point", 10.0, "fixed_effects")
  set_variable_vector(selectivity, "slope", 0.2, "fixed_effects")

  CreateTMBModel()
  #' @description Test that `get_fixed()` works with a logistic selectivity curve returns the correct number of parameters with their specified inputs.
  expect_equal(
    c(get_variable_vector(selectivity, "inflection_point")[["values"]], get_variable_vector(selectivity, "slope")[["values"]]),
    get_fixed()
  )
  clear()

  selectivity <- create_selectivity("Logistic")
  set_variable_vector(selectivity, "inflection_point", 10.0, "assumed_known")
  set_variable_vector(selectivity, "slope", 0.2, "fixed_effects")
  CreateTMBModel()
  #' @description Test that setting a selectivity parameter to FALSE in a previously defined module changes the number of parameters.
  expect_equal(
    get_variable_vector(selectivity, "slope")[["values"]],
    get_fixed()
  )
  clear()

  fish_selex <- create_selectivity("DoubleLogistic")
  set_variable_vector(fish_selex, "inflection_point_asc", 2, "fixed_effects")
  set_variable_vector(fish_selex, "inflection_point_desc", 3, "fixed_effects")
  set_variable_vector(fish_selex, "slope_asc", 1, "assumed_known")
  set_variable_vector(fish_selex, "slope_desc", 1.5, "fixed_effects")

  CreateTMBModel()
  sel_parm <- c(
    get_variable_vector(fish_selex, "inflection_point_asc")[["values"]],
    get_variable_vector(fish_selex, "inflection_point_desc")[["values"]],
    get_variable_vector(fish_selex, "slope_desc")[["values"]]
  )
  #' @description Test that the correct number of parameters are returned for a double logistic selectivity curve.
  expect_equal(get_fixed(), sel_parm)
  clear()

  selectivity <- create_selectivity("Logistic")
  set_variable_vector(selectivity, "inflection_point", 11.0, "fixed_effects")
  set_variable_vector(selectivity, "slope", 0.5, "fixed_effects")
  sel_parm <- c(get_variable_vector(selectivity, "inflection_point")[["values"]], get_variable_vector(selectivity, "slope")[["values"]])
  recruitment <- create_recruitment("BevertonHolt")
  h <- 0.75
  r0 <- 1000000.0
  spawns <- 9.55784 * 10^6
  phi_0 <- 0.0102562
  set_variable_vector(
    recruitment, "logit_steep",
    -log(1.0 - h) + log(h - 0.2), "fixed_effects"
  )
  set_variable_vector(recruitment, "log_rzero", log(r0), "fixed_effects")
  # recruitment$n_years needs to be greater than 0 to avoid a CreateTMBModel() error
  set_recruitment_n_years(recruitment, 1)
  rec_parm <- c(-log(1.0 - h) + log(h - 0.2), log(r0))

  CreateTMBModel()
  #' @description Test the counting of parameters when multiple modules are involved, e.g., selectivity and recruitment.
  expect_equal(c(sel_parm, rec_parm), get_fixed())
  clear()
})


## Edge handling ----
# No edge cases to test for this interface.
test_that("`get_fixed()` returns correct outputs for edge cases", {
  clear()
  #' @description Test that zero parameters are registered after using `clear()`.
  expect_equal(numeric(0), get_fixed())
  #' @description Test that model creation diagnoses an empty XPtr registry.
  expect_error(CreateTMBModel(), "No model components have been registered")
  expect_equal(numeric(0), get_fixed())
  clear()
})

## Error handling ----
# No error handling to test for this interface.
