# Instructions ----
#' This file follows the format generated by FIMS:::use_testthat_template().
#' Necessary tests include input and output (IO) correctness [IO
#' correctness], edge-case handling [Edge handling], and built-in errors and
#' warnings [Error handling]. See `?FIMS:::use_testthat_template` for more
#' information. Every test should have a @description tag, which can span
#' multiple lines, that will be used in the bookdown report of the results from
#' {testthat}.

# distribution_formulas ----
## Setup ----
load(testthat::test_path("fixtures", "integration_test_data.RData"))
iter_id <- 1
# Load operating model data
om_input <- om_input_list[[iter_id]]
om_output <- om_output_list[[iter_id]]
em_input <- em_input_list[[iter_id]]

# Clear any previous FIMS settings
clear()

# Set up recruitment module to test initialize_process_distribution
# create new module in the recruitment class (specifically Beverton--Holt,
# when there are other options, this would be where the option would be chosen)
recruitment <- methods::new(BevertonHoltRecruitment)

# set up log_rzero (equilibrium recruitment)
recruitment$log_rzero[1]$value <- log(om_input$R0)
recruitment$log_rzero[1]$estimation_type$set("fixed_effects")
# set up logit_steep
recruitment$logit_steep[1]$value <- -log(1.0 - om_input$h) +
  log(om_input$h - 0.2)
recruitment$logit_steep[1]$estimation_type$set("constant")
# turn on estimation of deviations recruit deviations should enter the model in
# normal space. The log is taken in the likelihood calculations alternative
# setting: recruitment$log_devs <- rep(0, length(om_input$logR.resid))
recruitment$log_devs$resize(om_input$nyr - 1)
recruitment$log_devs$set_all_estimable(TRUE)
recruitment$log_r$resize(om_input$nyr - 1)
recruitment$log_r$set_all_random(TRUE)

logR_resid <- om_input$logR.resid[-1]
purrr::walk(
  seq_along(logR_resid),
  \(x) recruitment$log_devs[x]$value <- logR_resid[x]
)


# set up logR_sd using the normal log_sd parameter
recruitment_distribution <- initialize_process_distribution(
  module = recruitment,
  par = "log_devs",
  family = gaussian(),
  sd = list(value = om_input$logR_sd, estimation_type = "constant"),
  is_random_effect = FALSE
)

# Set up fishing fleet modules to test initialize_data_distribution
catch <- em_input$L.obs$fleet1
# set fishing fleet catch data, need to set dimensions of data index currently
# FIMS only has a fleet module that takes index for both survey index and
# fishery catch
fishing_fleet_index <- methods::new(Index, om_input$nyr)
purrr::walk(
  seq_along(catch),
  \(x) fishing_fleet_index$index_data$set(x - 1, catch[x])
)
fishing_fleet <- methods::new(Fleet)
fishing_fleet$n_ages$set(om_input$nages)
fishing_fleet$n_years$set(om_input$nyr)
fishing_fleet$log_Fmort$resize(om_input$nyr)
purrr::walk(
  seq_along(log(om_output$f)),
  \(x) fishing_fleet$log_Fmort[x]$value <- log(om_output$f)[x]
)
fishing_fleet$log_Fmort$set_all_estimable(TRUE)
fishing_fleet$log_q[1]$value <- log(1.0)
fishing_fleet$log_q$set_all_estimable(FALSE)
fishing_fleet$SetObservedIndexDataID(fishing_fleet_index$get_id())

# Set up fishery index data using the lognormal
fleet_sd <- rep(sqrt(log(em_input$cv.L$fleet1^2 + 1)), om_input$nyr)
fishing_fleet_index_distribution1 <- initialize_data_distribution(
  module = fishing_fleet,
  family = lognormal(link = "log"),
  sd = list(value = fleet_sd, estimation_type = "constant"),
  data_type = "index"
)
fishing_fleet_index_distribution2 <- initialize_data_distribution(
  module = fishing_fleet,
  family = stats::gaussian(link = "log"),
  sd = list(value = fleet_sd[1], estimation_type = "fixed_effects"),
  data_type = "index"
)


## IO correctness ----
test_that("`initialize_process_distribution()` works with correct inputs", {
  #' @description Test that `initialize_process_distribution()` returns the correct log sd values when scalar.
  expect_equal(log(om_input$logR_sd), recruitment_distribution$log_sd[1]$value)

  #' @description Test that `initialize_process_distribution()` returns the correct dimension for x values.
  expect_equal(length(recruitment$log_devs), length(recruitment_distribution$x))

  #' @description Test that `initialize_process_distribution()` matches the dimensions of x and expected values.
  expect_equal(
    length(recruitment_distribution$x),
    length(recruitment_distribution$expected_values)
  )
})

test_that("`initialize_data_distribution()` works with correct inputs", {
  #' @description Test that `initialize_data_distribution()` returns the correct log sd values when given a vector.
  expect_equal(
    log(fleet_sd[1]),
    fishing_fleet_index_distribution1$log_sd[1]$value
  )
  #' @description Test that `initialize_data_distribution()` returns the correct log sd estimation type.
  expect_equal(
    "constant",
    fishing_fleet_index_distribution1$log_sd[1]$estimation_type$get()
  )
  #' @description Test that `initialize_data_distribution()` returns the correct log sd values when scalar.
  expect_equal(
    log(fleet_sd[1]),
    fishing_fleet_index_distribution2$log_sd[1]$value
  )
})

## Edge handling ----
test_that("`sd` value from `initialize_process_distribution()` must be greater than 0", {
  #' @description Test that error is thrown when `sd` `value` is out of bounds.
  expect_error(
    initialize_process_distribution(
      module = recruitment,
      par = "log_devs",
      family = gaussian(),
      sd = list(value = -1, estimation_type = "constant"),
      is_random_effect = FALSE
    ),
    "are out of bounds"
  )
})


## Error handling ----
test_that("`initialize_process_distribution()` returns correct error messages", {
  #' @description Test that `multinomial` cannot be specified as a `family` in `initialize_process_distribution()`.
  expect_error(
    initialize_process_distribution(
      module = recruitment,
      par = "log_devs",
      family = multinomial(),
      sd = list(value = om_input$logR_sd, estimation_type = "constant"),
      is_random_effect = FALSE
    ),
    "FIMS currently does not allow the family"
  )

  #' @description Test that error is thrown when incorrect `family` specified for `initialize_process_distribution()`.
  expect_error(
    initialize_process_distribution(
      module = recruitment,
      par = "log_devs",
      family = binomial(),
      sd = list(value = om_input$logR_sd, estimation_type = "constant"),
      is_random_effect = FALSE
    ),
    "FIMS currently does not allow the family"
  )

  #' @description Test that error is thrown when vector size of `sd` `value` and `estimation_type` do not match.
  expect_error(
    initialize_process_distribution(
      module = recruitment,
      par = "log_devs",
      family = gaussian(),
      sd = list(
        value = rep(om_input$logR_sd, 3),
        estimation_type = rep("constant", 2)
      ),
      is_random_effect = FALSE
    ),
    "must match"
  )

  #' @description Test that error is thrown when `family` is not a family class.
  expect_error(
    initialize_process_distribution(
      module = recruitment,
      par = "log_devs",
      family = "normal",
      sd = list(
        value = rep(om_input$logR_sd, 3),
        estimation_type = "constant"
      ),
      is_random_effect = FALSE
    ),
    "should be an object of class"
  )

  #' @description Test that error is thrown when `sd` `estimation_type` is missing.
  expect_error(
    initialize_process_distribution(
      module = recruitment,
      par = "log_devs",
      family = gaussian(),
      sd = list(value = 1),
      is_random_effect = FALSE
    ),
    "need to be present"
  )
})


test_that("`initialize_data_distribution()` returns correct error messages", {
  #' @description Test that error is thrown when `family` and `index` `data_type` don't match in `initialize_data_distribution()`.
  expect_error(
    initialize_data_distribution(
      module = fishing_fleet,
      family = multinomial(),
      sd = list(value = fleet_sd, estimation_type = "constant"),
      data_type = "index"
    ),
    "does not allow the family to be"
  )

  #' @description Test that error is thrown when `family` and `landings` `data_type` don't match in `initialize_data_distribution()`.
  expect_error(
    initialize_data_distribution(
      module = fishing_fleet,
      family = multinomial(),
      sd = list(value = fleet_sd, estimation_type = "constant"),
      data_type = "landings"
    ),
    "does not allow the family to be"
  )

  #' @description Test that error is thrown when `family` and `agecomp` `data_type` don't match in `initialize_data_distribution()`.
  expect_error(
    initialize_data_distribution(
      module = fishing_fleet,
      family = gaussian(),
      sd = list(value = fleet_sd, estimation_type = "constant"),
      data_type = "agecomp"
    ),
    "does not allow the family to be"
  )

  #' @description Test that error is thrown when `family` and `lengthcomp` `data_type` don't match in `initialize_data_distribution()`.
  expect_error(
    initialize_data_distribution(
      module = fishing_fleet,
      family = lognormal(),
      sd = list(value = fleet_sd, estimation_type = "constant"),
      data_type = "lengthcomp"
    ),
    "does not allow the family to be"
  )

  #' @description Test that error is thrown when `data_type` is incorrect in `initialize_data_distribution()`.
  expect_error(
    initialize_data_distribution(
      module = fishing_fleet,
      family = lognormal(),
      sd = list(value = fleet_sd, estimation_type = "constant"),
      data_type = "length_comp"
    ),
    "must be one of"
  )

  #' @description Test that error is thrown when `sd` value and `estimation_type` dimensions do not match.
  expect_error(
    initialize_data_distribution(
      module = fishing_fleet,
      family = multinomial(),
      sd = list(value = fleet_sd, estimation_type = c("constant", "constant")),
      data_type = "agecomp"
    ),
    "must match if more than one value"
  )

  #' @description Test that error is thrown when `sd` value is missing.
  expect_error(
    initialize_data_distribution(
      module = fishing_fleet,
      family = multinomial(),
      sd = list(estimation_type = "constant"),
      data_type = "agecomp"
    ),
    "need to be present"
  )
  #' @description Test that error is thrown when `family` is missing.
  expect_error(
    initialize_data_distribution(
      module = fishing_fleet,
      sd = list(value = fleet_sd),
      data_type = "agecomp"
    ),
    "is missing from"
  )
  clear()
})
