# Instructions ----
#' This file follows the format generated by FIMS:::use_testthat_template().
#' Necessary tests include input and output (IO) correctness [IO
#' correctness], edge-case handling [Edge handling], and built-in errors and
#' warnings [Error handling]. See `?FIMS:::use_testthat_template` for more
#' information. Every test should have a @description tag, which can only span
#' one lines, that will be used in the bookdown report of the results from
#' {testthat}. This line can be more than 80 characters.

# check_mle_convergence ----
## Setup ----
make_mock_mle_input <- function() {
  list(dummy = TRUE)
}

make_mock_mle_obj <- function() {
  list(env = list(random = numeric()))
}

make_mock_mle_opt <- function(convergence = 0, message = NULL, par = numeric()) {
  list(
    convergence = convergence,
    message = message,
    par = par
  )
}

mock_gradient <- c(0.001, 0.5, -0.02)
mock_parameter_names <- c(
  "Recruitment.1.log_rzero.1",
  "Selectivity.2.slope.47",
  "Fleet.1.log_q.3"
)

mock_fimsfit <- function(input, obj, opt, sdreport, run_time) {
  list(
    tag = "mock_fit",
    input = input,
    obj = obj,
    opt = opt,
    sdreport = sdreport,
    run_time = run_time
  )
}

## IO correctness ----
test_that("check_mle_convergence() works with correct inputs", {
  #' @description Test that `check_mle_convergence()` returns NULL when convergence code is zero and the gradient is low.
  input <- make_mock_mle_input()
  obj <- make_mock_mle_obj()
  opt <- make_mock_mle_opt(convergence = 0)

  expect_no_warning(
    out <- FIMS:::check_mle_convergence(input, obj, opt, maxgrad = 1e-4)
  )
  expect_null(out)

  #' @description Test that `check_mle_convergence()` names the parameter with the largest absolute gradient when the gradient is above 1.
  expect_warning(
    object = FIMS:::check_mle_convergence(
      input,
      obj,
      opt,
      maxgrad = 5,
      gradient = c(0.001, 5, -0.02),
      parameter_names = mock_parameter_names
    ),
    regexp = "Largest absolute gradient is on \"Selectivity 2: slope (parameter_id 47)\"",
    fixed = TRUE
  )

  #' @description Test that `check_mle_convergence()` names the parameter with the largest absolute gradient when nlminb did not converge.
  expect_warning(
    object = FIMS:::check_mle_convergence(
      input,
      obj,
      make_mock_mle_opt(convergence = 1, message = "iteration limit reached"),
      maxgrad = 0.03,
      gradient = c(0.001, 0.01, -0.03),
      parameter_names = mock_parameter_names
    ),
    regexp = "Largest absolute gradient is on \"Fleet 1: log_q (parameter_id 3)\"",
    fixed = TRUE
  )
})

## Edge handling ----
test_that("check_mle_convergence() returns correct outputs for edge cases", {
  #' @description Test that `check_mle_convergence()` warns when nlminb convergence code is non-zero.
  input <- make_mock_mle_input()
  obj <- make_mock_mle_obj()
  opt <- make_mock_mle_opt(convergence = 1, message = "false convergence")

  expect_warning(
    object = FIMS:::check_mle_convergence(input, obj, opt, maxgrad = 1e-4),
    regexp = "Optimization failed convergence checks"
  )

  #' @description Test that `check_mle_convergence()` leaves out the gradient name when no gradient is supplied, as in calls made before names were added.
  warning_text <- tryCatch(
    FIMS:::check_mle_convergence(input, obj, make_mock_mle_opt(), maxgrad = 5),
    warning = conditionMessage
  )
  expect_match(warning_text, "Model does not seem converged")
  expect_no_match(warning_text, "Largest absolute gradient")

  #' @description Test that `check_mle_convergence()` falls back to indexed labels when the names do not line up with the gradient.
  expect_warning(
    object = FIMS:::check_mle_convergence(
      input,
      obj,
      make_mock_mle_opt(),
      maxgrad = 5,
      gradient = c(0.001, 5, -0.02),
      parameter_names = mock_parameter_names[1:2]
    ),
    regexp = "Largest absolute gradient is on \"p[2]\"",
    fixed = TRUE
  )

  #' @description Test that `check_mle_convergence()` leaves out the gradient name when every gradient is NaN.
  warning_text <- tryCatch(
    FIMS:::check_mle_convergence(
      input,
      obj,
      make_mock_mle_opt(),
      maxgrad = 5,
      gradient = c(NaN, NaN, NaN),
      parameter_names = mock_parameter_names
    ),
    warning = conditionMessage
  )
  expect_no_match(warning_text, "Largest absolute gradient")
})

## Error handling ----
test_that("check_mle_convergence() returns correct error messages", {
  #' @description Test that `check_mle_convergence()` warns for moderately high gradients and returns a diagnostic fit object.
  input <- make_mock_mle_input()
  obj <- make_mock_mle_obj()
  opt <- make_mock_mle_opt(convergence = 0)
  maxgrad <- 0.1
  out <- NULL

  testthat::with_mocked_bindings(
    FIMSFit = mock_fimsfit,
    print = function(x, ...) invisible(x),
    {
      expect_warning(
        object = out <- FIMS:::check_mle_convergence(input, obj, opt, maxgrad),
        regexp = "Optimization resulted in high gradients"
      )
    },
    .package = "FIMS"
  )

  expect_equal(object = out$tag, expected = "mock_fit")
  expect_identical(object = out$input, expected = input)

  #' @description Test that `check_mle_convergence()` names the parameter with the largest absolute gradient for moderately high gradients.
  testthat::with_mocked_bindings(
    FIMSFit = mock_fimsfit,
    print = function(x, ...) invisible(x),
    {
      expect_warning(
        object = FIMS:::check_mle_convergence(
          input,
          obj,
          opt,
          maxgrad = 0.5,
          gradient = mock_gradient,
          parameter_names = mock_parameter_names
        ),
        regexp = "Largest absolute gradient is on \"Selectivity 2: slope (parameter_id 47)\"",
        fixed = TRUE
      )
    },
    .package = "FIMS"
  )
})

# label_values ----
## IO correctness ----
test_that("label_values() works with correct inputs", {
  #' @description Test that `label_values()` returns readable FIMS parameter names when they are unique and line up with the values.
  expect_equal(
    object = FIMS:::label_values(1:3, mock_parameter_names),
    expected = c(
      "Recruitment 1: log_rzero (parameter_id 1)",
      "Selectivity 2: slope (parameter_id 47)",
      "Fleet 1: log_q (parameter_id 3)"
    )
  )

  #' @description Test that `label_values()` indexes repeated labels within their name, as for ADREPORT vectors.
  expect_equal(
    object = FIMS:::label_values(1:4, c("biomass", "biomass", "ssb", "biomass")),
    expected = c("biomass[1]", "biomass[2]", "ssb", "biomass[3]")
  )
})

## Edge handling ----
test_that("label_values() returns correct outputs for edge cases", {
  #' @description Test that `label_values()` indexes the fallback, even for a single value, so a bare "p" is never shown.
  expect_equal(object = FIMS:::label_values(0.1), expected = "p[1]")
  expect_equal(
    object = FIMS:::label_values(1:2, NULL, fallback = "re"),
    expected = c("re[1]", "re[2]")
  )

  #' @description Test that `label_values()` uses the fallback when the labels do not line up with the values.
  expect_equal(
    object = FIMS:::label_values(1:3, c("a", "b")),
    expected = c("p[1]", "p[2]", "p[3]")
  )

  #' @description Test that `label_values()` returns an empty character vector for empty input.
  expect_identical(
    object = FIMS:::label_values(numeric(0), character(0)),
    expected = character(0)
  )
})

# readable_parameter_labels ----
## IO correctness ----
test_that("readable_parameter_labels() works with correct inputs", {
  #' @description Test that `readable_parameter_labels()` splits FIMS names into module name, module id, label, and parameter id.
  expect_equal(
    object = FIMS:::readable_parameter_labels(
      c("Selectivity.2.slope.47", "Recruitment.1.log_devs.729")
    ),
    expected = c(
      "Selectivity 2: slope (parameter_id 47)",
      "Recruitment 1: log_devs (parameter_id 729)"
    )
  )

  #' @description Test that `readable_parameter_labels()` adds the fleet name, and the data type for distributions, from the fleet lookup.
  fleet_modules <- tibble::tibble(
    fleet = c("fleet1", "survey1", "survey1"),
    module_name = c("Selectivity", "Fleet", "distribution"),
    module_id = c(2L, 2L, 7L),
    data_type = c(NA, NA, "index")
  )
  expect_equal(
    object = FIMS:::readable_parameter_labels(
      c(
        "Selectivity.2.slope.47",
        "Fleet.2.log_q.366",
        "dnorm.7.log_sd.763",
        "Recruitment.1.log_devs.729"
      ),
      fleet_modules
    ),
    expected = c(
      "Selectivity 2 (fleet1): slope (parameter_id 47)",
      "Fleet 2 (survey1): log_q (parameter_id 366)",
      "dnorm 7 (survey1 index): log_sd (parameter_id 763)",
      "Recruitment 1: log_devs (parameter_id 729)"
    )
  )
})

## Edge handling ----
test_that("readable_parameter_labels() returns correct outputs for edge cases", {
  #' @description Test that `readable_parameter_labels()` leaves labels unchanged when applied a second time.
  once <- FIMS:::readable_parameter_labels("Selectivity.2.slope.47")
  expect_equal(object = FIMS:::readable_parameter_labels(once), expected = once)

  #' @description Test that `readable_parameter_labels()` leaves out the fleet when a module is not in the lookup.
  expect_equal(
    object = FIMS:::readable_parameter_labels(
      "Selectivity.9.slope.47",
      tibble::tibble(
        fleet = "fleet1",
        module_name = "Selectivity",
        module_id = 1L,
        data_type = NA_character_
      )
    ),
    expected = "Selectivity 9: slope (parameter_id 47)"
  )

  #' @description Test that `readable_parameter_labels()` leaves labels that do not follow the FIMS pattern unchanged.
  other_labels <- c(
    "p[2]",
    "biomass[3]",
    "fixed_1",
    "a.b.c.d",
    "Fleet.1.log_q",
    "Fleet.1.log.q.3"
  )
  expect_equal(
    object = FIMS:::readable_parameter_labels(other_labels),
    expected = other_labels
  )

  #' @description Test that `readable_parameter_labels()` returns an empty character vector for empty input.
  expect_identical(
    object = FIMS:::readable_parameter_labels(character(0)),
    expected = character(0)
  )
})
