# Instructions ----
#' This file follows the format generated by FIMS:::use_testthat_template().
#' Necessary tests include input and output (IO) correctness [IO
#' correctness], edge-case handling [Edge handling], and built-in errors and
#' warnings [Error handling]. See `?FIMS:::use_testthat_template` for more
#' information. Every test should have a @description tag, which can only span
#' one lines, that will be used in the bookdown report of the results from
#' {testthat}. This line can be more than 80 characters.

# describe_model ----
## Setup ----
# describe_model() reports whatever is in the registry, so each test starts
# from an empty one and clears up after itself.

## IO correctness ----
test_that("`describe_model()` reports registered modules", {
  clear()
  selectivity <- create_selectivity("Logistic")
  recruitment <- create_recruitment("BevertonHolt")

  #' @description Test that `describe_model()` names each module by its type and module name.
  expect_output(describe_model(), "Logistic Selectivity")
  expect_output(describe_model(), "BevertonHolt Recruitment")

  #' @description Test that `describe_model()` reports each module's id.
  expect_output(describe_model(), paste0("id: ", get_module_id(selectivity)))
  expect_output(describe_model(), paste0("id: ", get_module_id(recruitment)))

  #' @description Test that `describe_model()` reports the number of components.
  expect_output(describe_model(), "Total: 2 component\\(s\\)")

  clear()
})

test_that("`describe_model()` names modules that have no type", {
  clear()
  fleet <- create_fleet()
  population <- create_population()

  #' @description Test that a module with no module_type is named by its module name alone.
  output <- capture.output(describe_model())
  expect_true(any(grepl("^\\s+Fleet\\s+id:", output)))
  expect_true(any(grepl("^\\s+Population\\s+id:", output)))

  #' @description Test that a module with no module_type does not print NA as part of its name.
  expect_false(any(grepl("NA Fleet|NA Population", output)))

  clear()
})

test_that("`describe_model()` reports the dimensions a data module was given", {
  clear()
  age_comp <- create_data("age_comp", n_years = 30, n_bins = 12)

  #' @description Test that `describe_model()` reports the dimensions recorded by `create_data()`.
  output <- capture.output(describe_model())
  expect_true(any(grepl("n_years = 30", output)))
  expect_true(any(grepl("n_ages = 12", output)))

  clear()
})

test_that("`describe_model()` returns its metadata invisibly", {
  clear()
  selectivity <- create_selectivity("Logistic")

  #' @description Test that `describe_model()` returns the metadata for each registered module.
  metadata <- capture.output(result <- describe_model())
  expect_length(result, 1)
  expect_equal(result[[1]][["module_name"]], "Selectivity")
  expect_equal(result[[1]][["module_type"]], "Logistic")
  expect_equal(result[[1]][["id"]], get_module_id(selectivity))

  #' @description Test that `describe_model()` returns invisibly rather than printing its value twice.
  # capture.output() keeps the printed report out of the test log; the
  # visibility of the inner call is what is being checked.
  invisible(capture.output(expect_invisible(describe_model())))

  clear()
})

## Edge handling ----
test_that("`describe_model()` handles an empty registry", {
  clear()

  #' @description Test that `describe_model()` reports when no modules have been registered.
  expect_message(describe_model(), "No model components have been registered")

  #' @description Test that `describe_model()` returns NULL when no modules have been registered.
  expect_null(suppressMessages(describe_model()))

  clear()
})

test_that("`describe_model()` reflects the registry after clear()", {
  clear()
  selectivity <- create_selectivity("Logistic")
  expect_output(describe_model(), "Total: 1 component\\(s\\)")

  clear()
  #' @description Test that `describe_model()` reports an empty registry after `clear()`.
  expect_message(describe_model(), "No model components have been registered")
})

## Error handling ----
# describe_model() takes no arguments and reports whatever is registered, so
# there are no built-in errors to test.
