# Instructions ----
#' This file follows the format generated by FIMS:::use_testthat_template().
#' Necessary tests include input and output (IO) correctness [IO
#' correctness], edge-case handling [Edge handling], and built-in errors and
#' warnings [Error handling]. See `?FIMS:::use_testthat_template` for more
#' information. Every test should have a @description tag, which can only span
#' one lines, that will be used in the bookdown report of the results from
#' {testthat}. This line can be more than 80 characters.

# get_version ----
## Setup ----
fit_with_optimization_big <- FIMS::fit_with_optimization_big
fit_without_optimization_big <- FIMS:::fit_without_optimization_big
## IO correctness ----
test_that("`get_version()` works with correct inputs", {
  expected_version <- utils::packageVersion("FIMS")
  for (fit in list(fit_with_optimization_big, fit_without_optimization_big)) {
    version <- get_version(fit)
    #' @description Test that `get_version()` returns the fit's version slot.
    expect_equal(version, fit@version)
    #' @description Test that `get_version()` matches the current package version.
    expect_equal(version, expected_version)
  }
})

## Edge handling ----
test_that("`get_version()` returns correct outputs for edge cases", {
  #' @description Test that `get_version()` returns an error when given invalid input.
  expect_error(
    object = get_version("invalid_input")
  )
})

## Error handling ----
# No built-in errors to test.
