# Instructions ----
#' This file follows the format generated by FIMS:::use_testthat_template().
#' Necessary tests include input and output (IO) correctness [IO
#' correctness], edge-case handling [Edge handling], and built-in errors and
#' warnings [Error handling]. See `?FIMS:::use_testthat_template` for more
#' information. Every test should have a @description tag, which can only span
#' one line, that will be used in the bookdown report of the results from
#' {testthat}. This line can be more than 80 characters.

# rcpp real vector ops ----
## IO correctness ----
# Use a real vector object and confirm Ops with scalar and vector RHS values.
test_that("Rcpp_RealVector Ops works with numeric operands", {
  real_vector <- methods::new(RealVector, 4)
  real_vector$set_values(c(1, 2, 3, 4))

  #' @description Test that scalar addition preserves RealVector values.
  sum_result <- real_vector + 1
  expect_s4_class(sum_result, "Rcpp_RealVector")
  expect_equal(sum_result$get_values(), c(2, 3, 4, 5))

  #' @description Test that scalar multiplication preserves RealVector values.
  mul_result <- real_vector * 2
  expect_s4_class(mul_result, "Rcpp_RealVector")
  expect_equal(mul_result$get_values(), c(2, 4, 6, 8))

  #' @description Test that vector addition preserves RealVector values.
  vector_add_result <- real_vector + c(10, 20, 30, 40)
  expect_s4_class(vector_add_result, "Rcpp_RealVector")
  expect_equal(vector_add_result$get_values(), c(11, 22, 33, 44))

  #' @description Test that comparison returns a logical vector result.
  expect_equal(real_vector == 2, c(FALSE, TRUE, FALSE, FALSE))
  expect_equal(real_vector == c(1, 5, 3, 4), c(TRUE, FALSE, TRUE, TRUE))
})
