# Instructions ----
#' This file follows the format generated by FIMS:::use_testthat_template().
#' Necessary tests include input and output (IO) correctness [IO
#' correctness], edge-case handling [Edge handling], and built-in errors and
#' warnings [Error handling]. See `?FIMS:::use_testthat_template` for more
#' information. Every test should have a @description tag, which can only span
#' one lines, that will be used in the bookdown report of the results from
#' {testthat}. This line can be more than 80 characters.

# rcpp population interface ----
## Setup ----
# Load or prepare any necessary data for testing

## IO correctness ----
test_that("rcpp population interface works with correct inputs", {
  # setup population to create test values
  population <- create_population()
  n_years <- 10
  n_ages <- 10
  log_M_length <- n_years * n_ages
  population$log_M[] <- rep(-1, log_M_length)

  population$log_init_naa[] <- rep(0, n_ages)

  population$n_ages$set(n_ages)
  population$ages[] <- seq(1, n_ages)
  population$n_fleets$set(2)
  population$n_years$set(n_years)


  #' @description Test that the population id is 1.
  expect_equal(
    object = get_module_id(population),
    expected = 1
  )

  #' @description Test that the log_M values are all -1.
  expect_equal(
    object = get_variable_vector(population, "log_M")[["values"]],
    expected = rep(-1, n_years * n_ages)
  )
  #' @description Test that the log_M values are not estimated.
  expect_equal(
    object = get_variable_vector(population, "log_M")[["estimation_status"]],
    expected = rep("assumed_known", n_years * n_ages)
  )

  #' @description Test that the log_init_naa values are all 0.
  expect_equal(
    object = get_variable_vector(population, "log_init_naa")[["values"]],
    expected = rep(0, n_years)
  )
  #' @description Test that the log_init_naa values are estimated.
  expect_equal(
    object = get_variable_vector(population, "log_init_naa")[["estimation_status"]],
    expected = rep("fixed_effects", n_years)
  )


  #' @description Test that the log_M values are all -1.
  expect_equal(
    object = get_variable_vector(population, "log_M")[["values"]],
    expected = rep(-1, n_years * n_ages)
  )
  #' @description Test that the log_M values are now estimated.
  expect_equal(
    object = get_variable_vector(population, "log_M")[["estimation_status"]],
    expected = rep("fixed_effects", n_years * n_ages)
  )

  #' @description Test that the log_init_naa values are all 0.
  expect_equal(
    object = get_variable_vector(population, "log_init_naa")[["values"]],
    expected = rep(0, n_years)
  )
  #' @description Test that the log_init_naa values are not estimated.
  expect_equal(
    object = get_variable_vector(population, "log_init_naa")[["estimation_status"]],
    expected = rep("assumed_known", n_years)
  )

  clear()
})

## Edge handling ----
# No Edge handling for now.

## Error handling ----
# No built in errors or warnings to test for now.
