# Instructions ----
#' This file follows the format generated by FIMS:::use_testthat_template().
#' Necessary tests include input and output (IO) correctness [IO
#' correctness], edge-case handling [Edge handling], and built-in errors and
#' warnings [Error handling]. See `?FIMS:::use_testthat_template` for more
#' information. Every test should have a @description tag, which can only span
#' one lines, that will be used in the bookdown report of the results from
#' {testthat}. This line can be more than 80 characters.

# get_estimates ----
## Setup ----
# Load or prepare any necessary data for testing
if (!file.exists(testthat::test_path("fixtures", "fit_age_length_comp.RDS"))) {
  prepare_test_data()
}

## IO correctness ----
# Define the expected column names for the estimates tibble
expected_colnames <- c(
  "module_name", "module_id", "module_type", "label", "type", "type_id",
  "parameter_id", "fleet", "year_i", "age_i", "length_i",
  "input", "estimated", "expected", "observed",
  "estimation_type", "uncertainty",
  "distribution", "input_type",
  "lpdf", "likelihood", "log_sd", "log_like_cv", "gradient"
)

test_that("`get_estimates()` works with deterministic run", {
  # Read the RDS file containing the deterministic run results
  deterministic_results <- readRDS(testthat::test_path("fixtures", "deterministic_age_length_comp.RDS"))
  deterministic_estimates <- get_estimates(deterministic_results)
  deterministic_colnames <- colnames(deterministic_estimates)
  #' @description Test that `get_estimates()` returns correct colnames from a deterministic run.
  expect_equal(
    object = deterministic_colnames,
    expected = expected_colnames
  )

  #' @description Test that deterministic estimates contain the core native model components and parameters.
  expect_true(nrow(deterministic_estimates) > 0L)
  expect_true(
    all(c("Selectivity", "Fleet", "Recruitment", "Population") %in%
      deterministic_estimates$module_name)
  )
  expect_true(
    all(c("log_Fmort", "log_rzero", "log_init_naa") %in%
      deterministic_estimates$label)
  )
})

test_that("`get_estimates()` works with estimation run", {
  # Load the test data from an RDS file containing model fits.
  # List all RDS files in the fixtures directory that match the pattern "fit*_.RDS"
  fit_files <- list.files(
    path = testthat::test_path("fixtures"),
    pattern = "^fit.*\\.RDS$",
    full.names = TRUE
  )

  # Function to read the RDS file, get estimates, and check column names
  check_estimates_colnames <- function(fit_file) {
    fit_data <- readRDS(fit_file)
    estimates <- get_estimates(fit_data)
    estimates_colnames <- colnames(estimates)

    #' @description Test that `get_estimates()` returns correct colnames from a estimation run.
    expect_equal(
      object = estimates_colnames,
      expected = expected_colnames
    )
  }

  # Use purrr::map to apply the function to each file
  result <- purrr::map(fit_files, check_estimates_colnames)

  #' @description Test that an estimation run includes fitted parameters and derived quantities.
  estimates <- get_estimates(readRDS(fit_files[[1]]))
  expect_true(any(estimates$type == "derived_quantity", na.rm = TRUE))
  expect_true(any(!is.na(estimates$estimated)))
})

## Edge handling ----
test_that("`get_estimates()` returns correct outputs for edge cases", {
  #' @description Test that an error occurs if the input is not a valid model fit object.
  expect_error(
    object = get_estimates("invalid_fit")
  )
})

## Error handling ----
# No built-in errors to test.
