# Instructions ----
#' This file follows the format generated by FIMS:::use_testthat_template().
#' Necessary tests include input and output (IO) correctness [IO
#' correctness], edge-case handling [Edge handling], and built-in errors and
#' warnings [Error handling]. See `?FIMS:::use_testthat_template` for more
#' information. Every test should have a @description tag, which can only span
#' one lines, that will be used in the bookdown report of the results from
#' {testthat}. This line can be more than 80 characters.

# parse_data_distribution ----
## Setup ----
# No setup required.

## IO correctness ----
test_that("`parse_data_distribution()` works with correct inputs", {
  #' @description Test that a lognormal distribution string is parsed into a flat list of its family, link, and parameters.
  expect_equal(
    parse_data_distribution(
      "~ dlnorm(meanlog = log_catch_expected, sdlog = 0.00999975001354021)"
    ),
    list(
      family = "dlnorm",
      link = "log_catch_expected",
      mean = list(NA),
      meanlog = list(quote(log_catch_expected)),
      prob = list(NA),
      sd = list(NA),
      sdlog = list(0.00999975001354021),
      size = list(NA)
    )
  )

  #' @description Test that whitespace is not required between the formula operator and a normal distribution call.
  expect_equal(
    parse_data_distribution("~dnorm(mean = catch_expected, sd = 0.1)"),
    list(
      family = "dnorm",
      link = "catch_expected",
      mean = list(quote(catch_expected)),
      meanlog = list(NA),
      prob = list(NA),
      sd = list(0.1),
      sdlog = list(NA),
      size = list(NA)
    )
  )

  #' @description Test that calls and single-element expressions are accepted without first converting them to strings.
  expect_equal(
    parse_data_distribution(quote(~ dnorm(mean = index_expected, sd = 1))),
    parse_data_distribution(expression(~ dnorm(mean = index_expected, sd = 1)))
  )
})

## Edge handling ----
test_that("`parse_data_distribution()` returns correct outputs for edge cases", {
  #' @description Test that mixed distributions and missing specifications return aligned components with a fixed schema.
  parsed <- parse_data_distribution(c(
    "~dnorm(mean = catch_expected, sd = 0.1)",
    NA_character_,
    "~dmultinom(prob = agecomp_expected, size = 10)"
  ))
  expect_equal(parsed$family, c("dnorm", NA_character_, "dmultinom"))
  expect_equal(
    parsed$link,
    c("catch_expected", NA_character_, "agecomp_expected")
  )
  expect_identical(
    as.character(stats::na.omit(unlist(parsed$link))),
    c("catch_expected", "agecomp_expected")
  )
  expect_equal(parsed$size, list(NA, 1, 10))
  expect_equal(parsed$sd, list(0.1, 1, NA))
  expect_equal(unname(lengths(parsed)), rep(3L, length(parsed)))

  #' @description Test that a scalar missing specification has the same rectangular return schema as non-missing input.
  expect_equal(parse_data_distribution(NA_character_)$family, NA_character_)
})

## Error handling ----
test_that("`parse_data_distribution()` returns correct error messages", {
  #' @description Test that unsupported input types return an informative error.
  expect_error(
    parse_data_distribution(list("~dnorm(mean = x, sd = 1)")),
    "must be a character vector, expression, call, or formula",
    fixed = TRUE
  )

  #' @description Test that input without the formula operator returns an informative error.
  expect_error(
    parse_data_distribution("dnorm(mean = x, sd = 1)"),
    "Expression must be a distribution call",
    fixed = TRUE
  )

  #' @description Test that two-sided formulas are rejected for data distribution specifications.
  expect_error(
    parse_data_distribution("catch ~ dnorm(mean = x, sd = 1)"),
    "Two-sided formulas are not allowed",
    fixed = TRUE
  )

  #' @description Test that the family-specific central parameter must be present.
  expect_error(
    parse_data_distribution("~dnorm(sd = 1)"),
    "The central parameter does not exist for dnorm",
    fixed = TRUE
  )

  #' @description Test that distribution arguments must be formal arguments of the selected family.
  expect_error(
    parse_data_distribution("~dnorm(mean = x, sd = 1, extra = 2)"),
    "are not formal arguments of the dnorm function",
    fixed = TRUE
  )

  #' @description Test that a normal distribution standard deviation must be positive.
  expect_error(
    parse_data_distribution("~dnorm(mean = x, sd = -0.1)"),
    "`sd` must be positive",
    fixed = TRUE
  )

  #' @description Test that a lognormal distribution log-scale standard deviation must be positive.
  expect_error(
    parse_data_distribution("~dlnorm(meanlog = x, sdlog = 0)"),
    "`sdlog` must be positive",
    fixed = TRUE
  )
})
