# Instructions ----
#' This file follows the format generated by FIMS:::use_testthat_template().
#' Necessary tests include input and output (IO) correctness [IO
#' correctness], edge-case handling [Edge handling], and built-in errors and
#' warnings [Error handling]. See `?FIMS:::use_testthat_template` for more
#' information. Every test should have a @description tag, which can span
#' multiple lines, that will be used in the bookdown report of the results from
#' {testthat}.

# get_model_output ----
## Setup ----
# Load or prepare any necessary data for testing
if (!file.exists(test_path("fixtures", "fit_age_length_comp.RDS"))) {
  prepare_test_data()
}

## IO correctness ----
test_that("`get_model_output()` works with correct inputs", {
  # Load the test data from an RDS file containing model fits.
  # List all RDS files in the fixtures directory that match the pattern "fit*_.RDS"
  # or "deterministic*.RDS"
  fit_files <- list.files(
    path = test_path("fixtures"),
    pattern = "^(fit.*|deterministic.*)\\.RDS$",
    full.names = TRUE
  )

  expected_names <- c(
    "name", "type", "estimation_framework", "id", "objective_function_value",
    "growth", "recruitment", "maturity",
    "selectivity", "population_ids", "fleet_ids", "populations", "fleets",
    "density_components", "data", "log"
  )

  # Function to read the RDS file and get obj
  check_obj <- function(fit_file) {
    fit_data <- readRDS(fit_file)
    model_output <- get_model_output(fit_data)
    json_list <- jsonlite::fromJSON(model_output, simplifyVector = FALSE)
    #' @description Test that `get_model_output()` returns correct names for the `model_output` slot.
    expect_equal(
      object = names(json_list),
      expected = expected_names
    )
  }

  # Use purrr::map to apply the function to each file
  result <- purrr::map(fit_files, check_obj)
})

## Edge handling ----
# No edge handling tests for this function.

## Error handling ----
# No built-in errors to test.
