# Instructions ----
#' This file follows the format generated by FIMS:::use_testthat_template().
#' Necessary tests include input and output (IO) correctness [IO
#' correctness], edge-case handling [Edge handling], and built-in errors and
#' warnings [Error handling]. See `?FIMS:::use_testthat_template` for more
#' information. Every test should have a @description tag, which can only span
#' one lines, that will be used in the bookdown report of the results from
#' {testthat}. This line can be more than 80 characters.

# rcpp maturity ----
## Setup ----
# Load or prepare any necessary data for testing

## IO correctness ----
test_that("rcpp maturity works with correct inputs", {
  # Create maturity1
  maturity1 <- methods::new(LogisticMaturity)

  maturity1$inflection_point[1]$value <- 10.0
  maturity1$inflection_point[1]$estimation_type$set("fixed_effects")
  maturity1$slope[1]$value <- 0.2

  #' @description Test that `get_id()` from the maturity module returns the correct id.
  expect_equal(maturity1$get_id(), 1)
  #' @description Test that the value of `inflection_point` can be set and get correctly.
  expect_equal(maturity1$inflection_point[1]$value, 10.0)
  #' @description Test that the `estimation_type` of `inflection_point` can be set and get correctly.
  expect_equal(maturity1$inflection_point[1]$estimation_type$get(), "fixed_effects")
  #' @description Test that the value of `slope` can be set and get correctly.
  expect_equal(maturity1$slope[1]$value, 0.2)
  #' @description Test that the `evaluate()` method from the maturity module works correctly.
  expect_equal(maturity1$evaluate(10.0), 0.5)

  # Create maturity2
  maturity2 <- methods::new(LogisticMaturity)
  #' @description Test that rcpp maturity returns the correct id.
  expect_equal((maturity2$get_id()), 2)

  clear()
})

test_that("rcpp maturity parameters can have a prior", {
  maturity <- methods::new(LogisticMaturity)
  maturity$inflection_point[1]$value <- 3.0
  maturity$inflection_point[1]$estimation_type$set("fixed_effects")
  maturity$slope[1]$value <- 1.0
  maturity$slope[1]$estimation_type$set("fixed_effects")

  maturity_prior <- methods::new(DnormDistribution)
  maturity_prior$expected_values$resize(2)
  maturity_prior$expected_values[1]$value <- 3.5
  maturity_prior$expected_values[2]$value <- 1.2
  maturity_prior$log_sd$resize(1)
  maturity_prior$log_sd[1]$value <- log(0.5)
  maturity_prior$set_distribution_links(
    "prior",
    c(maturity$inflection_point$get_id(), maturity$slope$get_id())
  )

  # CreateTMBModel() finds the parameters a prior is linked to by their ids in
  # variable_map
  CreateTMBModel()
  parameters <- list(p = get_fixed(), re = get_random())
  obj <- TMB::MakeADFun(
    data = list(), parameters, DLL = "FIMS", silent = TRUE
  )
  #' @description Test that a normal prior on maturity inflection_point and slope returns their summed negative log density.
  expect_equal(
    obj[["report"]]()[["nll_components"]],
    -sum(dnorm(c(3.0, 1.0), mean = c(3.5, 1.2), sd = 0.5, log = TRUE))
  )

  clear()
})

## Edge handling ----
# No edge cases to test for this interface.

## Error handling ----
# No error handling to test for this interface.
