# Instructions ----
#' This file follows the format generated by FIMS:::use_testthat_template().
#' Necessary tests include input and output (IO) correctness [IO
#' correctness], edge-case handling [Edge handling], and built-in errors and
#' warnings [Error handling]. See `?FIMS:::use_testthat_template` for more
#' information. Every test should have a @description tag, which can only span
#' one lines, that will be used in the bookdown report of the results from
#' {testthat}. This line can be more than 80 characters.

# setup_default_Population ----
## Setup ----
data <- FIMS::FIMSFrame(data_big)

## IO correctness ----
test_that("`setup_default_Population()` works with correct inputs", {
  result <- setup_default_Population(data = data)

  #' @description Test that output is a tibble with expected population labels.
  expect_s3_class(result, "tbl_df")
  expect_true(all(c("log_M", "log_init_naa", "proportion_female") %in% result[["label"]]))

  #' @description Test that row count matches years-by-ages plus extra rows.
  expect_equal(
    nrow(result),
    get_n_years(data) * get_n_ages(data) + get_n_ages(data) + 1
  )

  clear()
})

## Edge handling ----
test_that("`setup_default_Population()` works with edge cases", {
  result <- setup_default_Population(
    data = data,
    log_M = rep(log(0.2), get_n_years(data) * get_n_ages(data)),
    log_init_naa = rep(log(1000), get_n_ages(data))
  )

  #' @description Test that vectorized log_M and log_init_naa are accepted.
  expect_s3_class(result, "tbl_df")

  proportion_female_at_age <- seq(0.4, 0.6, length.out = get_n_ages(data))
  proportion_female_rows <- setup_default_Population(
    data = data,
    proportion_female = proportion_female_at_age
  ) |>
    dplyr::filter(.data[["label"]] == "proportion_female")
  #' @description Test that a proportion_female vector by age gives 1 row per age in age order.
  expect_equal(proportion_female_rows[["age"]], get_ages(data))
  expect_equal(proportion_female_rows[["value"]], proportion_female_at_age)

  clear()
})

## Error handling ----
test_that("`setup_default_Population()` returns correct error messages", {
  #' @description Test that out-of-range proportion_female returns expected error.
  expect_error(
    object = setup_default_Population(data = data, proportion_female = 2),
    regexp = "between 0 and 1"
  )

  #' @description Test that a proportion_female vector not of length 1 or the number of ages returns expected error.
  expect_error(
    object = setup_default_Population(data = data, proportion_female = c(0.4, 0.6)),
    regexp = "proportion_female"
  )

  #' @description Test that invalid log_M length returns expected error.
  expect_error(
    object = setup_default_Population(data = data, log_M = c(log(0.2), log(0.3), log(0.4))),
    regexp = "log_M"
  )

  clear()
})
