# Instructions ----
#' This file follows the format generated by FIMS:::use_testthat_template().
#' Necessary tests include input and output (IO) correctness [IO
#' correctness], edge-case handling [Edge handling], and built-in errors and
#' warnings [Error handling]. See `?FIMS:::use_testthat_template` for more
#' information. Every test should have a @description tag that takes up just
#' one line, which will be used in the bookdown report of {testthat} results.

# get_input ----
## Setup ----
# Load or prepare any necessary data for testing
## IO correctness ----
test_that("get_input() works with correct inputs", {
  # Load the test data from an RDS file containing model fits.
  # List all RDS files in the fixtures directory that match the pattern "fit*_.RDS"
  fit_files <- list.files(
    path = test_path("fixtures"),
    pattern = "^fit.*\\.RDS$",
    full.names = TRUE
  )

  # Function to read the RDS file and get input
  check_input <- function(fit_file) {
    fit_data <- readRDS(fit_file)
    input <- get_input(fit_data)
    #' @description Test that get_input() returns correct output for the input slot.
    expect_equal(
      object = input,
      expected = fit_data@input
    )
    #' @description Test that get_input() returns correct names for the input slot.
    expect_equal(
      object = names(input),
      expected = "parameters"
    )
  }

  # Use purrr::map to apply the function to each file
  result <- purrr::map(fit_files, check_input)
})

## Edge handling ----
test_that("get_input() returns correct outputs for edge cases", {
  #' @description Test that get_input("invalid_input") returns an error.
  expect_error(
    object = get_input("invalid_input")
  )
})

## Error handling ----
# No built-in errors to test.
