# Instructions ----
#' This file follows the format generated by FIMS:::use_testthat_template().
#' Necessary tests include input and output (IO) correctness [IO
#' correctness], edge-case handling [Edge handling], and built-in errors and
#' warnings [Error handling]. See `?FIMS:::use_testthat_template` for more
#' information. Every test should have a @description tag, which can only span
#' one lines, that will be used in the bookdown report of the results from
#' {testthat}. This line can be more than 80 characters.

# rcpp recruitment interface ----
## Setup ----
# Load or prepare any necessary data for testing

## IO correctness ----
test_that("rcpp recruitment interface works with correct inputs", {
  # Create recruitment
  recruitment <- methods::new(BevertonHoltRecruitment)
  recruitment_process <- new(LogDevsRecruitmentProcess)
  h <- 0.75
  r0 <- 1000000.0
  spawns <- 9.55784 * 10^6
  phi_0 <- 0.0102562

  recruitment$logit_steep[1]$value <- -log(1.0 - h) + log(h - 0.2)
  recruitment$logit_steep[1]$estimation_type$set("random_effects")
  recruitment$log_rzero[1]$value <- log(r0)

  #' @description Test that the recruitment id is 1.
  expect_equal(
    object = recruitment$get_id(),
    expected = 1
  )
  #' @description Test that the logit_steep value is 0.78845736.
  expect_equal(
    object = recruitment$logit_steep[1]$value,
    expected = 0.78845736
  )
  #' @description Test that the logit_steep is a random effect.
  expect_equal(
    object = recruitment$logit_steep[1]$estimation_type$get(), "random_effects"
  )
  #' @description Test that the log_rzero value is log(1000000.0).
  expect_equal(
    object = recruitment$log_rzero[1]$value,
    expected = log(1000000.0)
  )
  #' @description Test that recruitment$evaluate(spawns, phi_0) returns 1090802.68.
  expect_equal(
    object = recruitment$evaluate_mean(spawns, phi_0),
    expected = 1090802.68
  )
  log_devs <- c(-1.0, 2.0, 3.0)
  recruitment$log_devs[] <- log_devs


  #' @description Test that the log_devs are set correctly.
  for (i in seq_along(log_devs)) {
    expect_equal(
      object = recruitment$log_devs[i]$value,
      expected = log_devs[i]
    )
  }

  # expected_lpdf <- sum(log(stats::dnorm(log_devs, 0, 0.7)))
  clear()
})

test_that("rcpp recruitment process interfaces work with correct inputs", {
  #' @description Test that LogDevsRecruitmentProcess can be instantiated and evaluated.
  log_devs <- methods::new(LogDevsRecruitmentProcess)
  expect_true(log_devs$get_id() > 0)

  #' @description Test that LogRRecruitmentProcess can be instantiated and evaluated.
  log_r <- methods::new(LogRRecruitmentProcess)
  expect_true(log_r$get_id() > 0)

  clear()
})

test_that("log recruitment deviations process scales expected recruitment by exp(delta)", {
  clear()

  frame <- FIMSFrame(data_big)
  parameters <- create_default_configurations(frame) |>
    create_default_parameters(data = frame) |>
    tidyr::unnest(cols = data)

  target_time <- 10
  delta <- 0.4

  baseline_fit <- parameters |>
    initialize_fims(data = frame) |>
    fit_fims(optimize = FALSE, get_sd = FALSE)
  baseline_recruitment <- get_report(baseline_fit)[["expected_recruitment"]][[1]]

  modified_parameters <- parameters
  target_row <- which(
    modified_parameters$module_name == "Recruitment" &
      modified_parameters$label == "log_devs" &
      modified_parameters$time == target_time
  )

  expect_length(target_row, 1)

  modified_parameters$value[target_row] <-
    modified_parameters$value[target_row] + delta

  modified_fit <- modified_parameters |>
    initialize_fims(data = frame) |>
    fit_fims(optimize = FALSE, get_sd = FALSE)
  modified_recruitment <- get_report(modified_fit)[["expected_recruitment"]][[1]]

  #' @description Test that adding `delta` to one `log_devs` value multiplies expected recruitment at that year by `exp(delta)`.
  expect_equal(
    object = modified_recruitment[target_time] / baseline_recruitment[target_time],
    expected = exp(delta),
    tolerance = 1e-6
  )

  clear()
})

## Edge handling ----
# No Edge handling for now.

## Error handling ----
test_that("test rcpp recruitment interface returns correct error messages", {
  # Create recruitment
  recruitment <- methods::new(BevertonHoltRecruitment)
  h <- 0.75
  r0 <- 1000000.0
  spawns <- 9.55784 * 10^6
  phi_0 <- 0.0102562

  recruitment$logit_steep[1]$value <- 1
  recruitment$logit_steep[1]$estimation_type$set("random_effects")
  recruitment$log_rzero[1]$value <- log(r0)


  #' @description Test that recruitment errors if logit_steep==1.
  expect_warning(
    object = recruitment$evaluate_mean(spawns, phi_0),
    regexp = "Steepness is subject to a logit transformation. Fixing it at 1.0 is not currently possible."
  )
  clear()
})
