# Instructions ----
#' This file follows the format generated by FIMS:::use_testthat_template().
#' Necessary tests include input and output (IO) correctness [IO
#' correctness], edge-case handling [Edge handling], and built-in errors and
#' warnings [Error handling]. See `?FIMS:::use_testthat_template` for more
#' information. Every test should have a @description tag, which can only span
#' one lines, that will be used in the bookdown report of the results from
#' {testthat}. This line can be more than 80 characters.

# rcpp maturity ----
## Setup ----
# Load or prepare any necessary data for testing

## IO correctness ----
test_that("rcpp maturity works with correct inputs", {
  # Create maturity1
  maturity1 <- create_maturity("logistic")

  set_variable_vector(maturity1, "inflection_point", 10.0, "fixed_effects")
  set_variable_vector(maturity1, "slope", 0.2, "assumed_known")

  #' @description Test that the maturity module reports the correct id.
  expect_equal(get_module_id(maturity1), 1)
  #' @description Test that the value of `inflection_point` can be set and get correctly.
  expect_equal(
    get_variable_vector(maturity1, "inflection_point")[["values"]], 10.0
  )
  #' @description Test that the `estimation_status` of `inflection_point` can be set and get correctly.
  expect_equal(
    get_variable_vector(maturity1, "inflection_point")[["estimation_status"]],
    "fixed_effects"
  )
  #' @description Test that the value of `slope` can be set and get correctly.
  expect_equal(get_variable_vector(maturity1, "slope")[["values"]], 0.2)
  #' @description Test that evaluating the maturity module works correctly.
  expect_equal(evaluate_maturity(maturity1, 10.0), 0.5)

  # Create maturity2
  maturity2 <- create_maturity("logistic")
  #' @description Test that rcpp maturity returns the correct id.
  expect_equal(get_module_id(maturity2), 2)

  clear()
})

## Edge handling ----
# No edge cases to test for this interface.

## Error handling ----
# No error handling to test for this interface.
