# Instructions ----
#' This file follows the format generated by FIMS:::use_testthat_template().
#' Necessary tests include input and output (IO) correctness [IO
#' correctness], edge-case handling [Edge handling], and built-in errors and
#' warnings [Error handling]. See `?FIMS:::use_testthat_template` for more
#' information. Every test should have a @description tag, which can span
#' multiple lines, that will be used in the bookdown report of the results from
#' {testthat}.

# fims_retrospective ----
## Setup ----
# Load or prepare any necessary data for testing
# clear memory
clear()
## Testing how to remove one year of data and run multiple FIMS models
# Load sample data
data("data_big")
# Prepare data for FIMS model
data_4_model <- FIMSFrame(data_big)
# Create parameters
parameters <- data_4_model |>
  create_default_configurations() |>
  create_default_parameters(data = data_4_model)

## IO correctness ----
test_that("run_fims_retrospective() works with correct inputs", {
  #' @description Test that run_fims_retrospective(x) returns y.

  retro_fit <- run_fims_retrospective(
    years_to_remove = 0:2,
    data = data_big,
    parameters = parameters,
    n_cores = 1
  )

  expect_equal(
    object = names(retro_fit),
    expected = c("years_to_remove", "estimates")
  )

  #' @description Test that fims_retrospective(x) returns y.
  expect_equal(
    object = length(retro_fit[["years_to_remove"]]),
    expected = 3
  )

  retro_ssb <- retro_fit[["estimates"]] |>
    dplyr::filter(label == "spawning_biomass") |>
    dplyr::select(label, year_i, estimated, retrospective_peel) |>
    tidyr::pivot_wider(names_from = retrospective_peel, values_from = estimated) |>
    dplyr::filter(year_i == 31) |>
    dplyr::select(-c(1, 2)) |>
    as.numeric()

  #' @description Test that fims_retrospective(x) returns y.
  expect_equal(
    object = retro_ssb,
    expected = c(1728.686, 1654.160, 1500.182),
    tolerance = .1
  )
})

## Edge handling ----
test_that("run_fims_retrospective() handles edge cases correctly", {
  #' @description Test that run_fims_retrospective works with years_to_remove = 0.
  retro_fit_zero <- run_fims_retrospective(
    years_to_remove = 0,
    data = data_big,
    parameters = parameters,
    n_cores = 1
  )
  expect_equal(
    object = length(retro_fit_zero[["years_to_remove"]]),
    expected = 1
  )
  expect_equal(
    object = retro_fit_zero[["years_to_remove"]],
    expected = 0
  )

  #' @description Test that run_fims_retrospective works with n_cores = 1 (sequential).
  retro_fit_seq <- run_fims_retrospective(
    years_to_remove = 0:1,
    data = data_big,
    parameters = parameters,
    n_cores = 1
  )
  expect_equal(
    object = length(retro_fit_seq[["years_to_remove"]]),
    expected = 2
  )
})

## Error handling ----
test_that("run_fims_retrospective() returns correct error messages", {
  #' @description Test that run_fims_retrospective errors with invalid n_cores (non-integer).
  expect_error(
    object = run_fims_retrospective(
      years_to_remove = 0:1,
      data = data_big,
      parameters = parameters,
      n_cores = 2.5
    ),
    regexp = "n_cores must be a positive integer"
  )

  #' @description Test that run_fims_retrospective errors with invalid n_cores (zero).
  expect_error(
    object = run_fims_retrospective(
      years_to_remove = 0:1,
      data = data_big,
      parameters = parameters,
      n_cores = 0
    ),
    regexp = "n_cores must be a positive integer"
  )

  #' @description Test that run_fims_retrospective errors with invalid n_cores (negative).
  expect_error(
    object = run_fims_retrospective(
      years_to_remove = 0:1,
      data = data_big,
      parameters = parameters,
      n_cores = -1
    ),
    regexp = "n_cores must be a positive integer"
  )

  #' @description Test that run_fims_retrospective errors with empty years_to_remove.
  expect_error(
    object = run_fims_retrospective(
      years_to_remove = numeric(0),
      data = data_big,
      parameters = parameters,
      n_cores = 1
    ),
    regexp = "must have at least one value"
  )

  #' @description Test that run_fims_retrospective errors with negative years_to_remove.
  expect_error(
    object = run_fims_retrospective(
      years_to_remove = -1,
      data = data_big,
      parameters = parameters,
      n_cores = 1
    ),
    regexp = "must contain non-negative values"
  )
})
