# Instructions ----
#' This file follows the format generated by FIMS:::use_testthat_template().
#' Necessary tests include input and output (IO) correctness [IO
#' correctness], edge-case handling [Edge handling], and built-in errors and
#' warnings [Error handling]. See `?FIMS:::use_testthat_template` for more
#' information. Every test should have a @description tag, which can only span
#' one lines, that will be used in the bookdown report of the results from
#' {testthat}. This line can be more than 80 characters.

# edm user workflows ----
## Setup ----
# Shared FIMSFrame with one pre-built delay embedding used across all tests.

local_ff <- local({
  data("data_big", package = "FIMS")
  ff <- FIMSFrame(data_big)
  create_edm_embedding(
    ff,
    series_type = "catch",
    series_name = "fleet1",
    E = 3L,
    tau = 1L
  )
})

# fit_edm() ----
## IO correctness ----

test_that("fit_edm() returns an EDMFit for simplex method", {
  #' @description fit_edm() with method='simplex' returns a valid EDMFit object.
  fit <- fit_edm(local_ff, method = "simplex")
  expect_true(is.EDMFit(fit))
  expect_equal(get_method(fit), "simplex")
})

test_that("fit_edm() returns an EDMFit for smap method", {
  #' @description fit_edm() with method='smap' returns a valid EDMFit object.
  fit <- fit_edm(local_ff, method = "smap")
  expect_true(is.EDMFit(fit))
  expect_equal(get_method(fit), "smap")
})

test_that("fit_edm() returns an EDMFit for gp method", {
  #' @description fit_edm() with method='gp' returns a valid EDMFit object.
  fit <- fit_edm(local_ff, method = "gp")
  expect_true(is.EDMFit(fit))
  expect_equal(get_method(fit), "gp")
})

test_that("fit_edm() predictions are finite numerics", {
  #' @description Predictions from all three EDM methods are finite numeric vectors.
  for (m in c("simplex", "smap", "gp")) {
    fit <- fit_edm(local_ff, method = m)
    preds <- get_predictions(fit)
    expect_true(is.numeric(preds), info = paste("method:", m))
    expect_true(all(is.finite(preds)), info = paste("method:", m))
    expect_gt(length(preds), 0L)
  }
})

test_that("fit_edm() stores correct embedding metadata", {
  #' @description EDMFit object stores the correct embedding_dimension and time_lag slots.
  fit <- fit_edm(local_ff, method = "simplex")
  expect_equal(fit@embedding_dimension, 3L)
  expect_equal(fit@time_lag, 1L)
  expect_equal(fit@n_library, length(get_predictions(fit)))
})

test_that("fit_edm() stores correct embedding name", {
  #' @description EDMFit@embedding_name matches the name used by create_edm_embedding().
  fit <- fit_edm(local_ff, method = "simplex",
                 embedding_name = "catch_fleet1_E3_tau1")
  expect_equal(get_embedding_name(fit), "catch_fleet1_E3_tau1")
})

test_that("fit_edm() simplex stores n_neighbors in parameters", {
  #' @description Simplex EDMFit parameters slot contains n_neighbors.
  fit <- fit_edm(local_ff, method = "simplex", n_neighbors = 5L)
  expect_equal(get_parameters(fit)[["n_neighbors"]], 5L)
})

test_that("fit_edm() smap stores theta in parameters", {
  #' @description S-Map EDMFit parameters slot contains the supplied theta value.
  fit <- fit_edm(local_ff, method = "smap", theta = 2.5)
  expect_equal(get_parameters(fit)[["theta"]], 2.5)
})

test_that("fit_edm() gp stores fitted hyperparameters in parameters", {
  #' @description GP-EDM EDMFit parameters slot contains phi, sigma2, and ve after fitting.
  fit <- fit_edm(local_ff, method = "gp")
  params <- get_parameters(fit)
  expect_true("phi" %in% names(params))
  expect_true("sigma2" %in% names(params))
  expect_true("ve" %in% names(params))
  expect_length(params[["phi"]], 3L)   # E = 3
})

test_that("fit_edm() gp stores init values alongside fitted values", {
  #' @description GP-EDM parameters slot stores user-supplied init values for traceability.
  fit <- fit_edm(local_ff, method = "gp",
                 gp_sigma2_init = 2.0, gp_ve_init = 0.05)
  params <- get_parameters(fit)
  expect_equal(params[["sigma2_init"]], 2.0)
  expect_equal(params[["ve_init"]], 0.05)
})

test_that("fit_edm() auto_select picks optimal n_neighbors", {
  #' @description auto_select=TRUE sets auto_selected=TRUE in the parameters slot.
  fit <- fit_edm(local_ff, method = "simplex", auto_select = TRUE)
  expect_true(get_parameters(fit)[["auto_selected"]])
  expect_true(is.integer(get_parameters(fit)[["n_neighbors"]]))
})

test_that("fit_edm() version slot matches package version", {
  #' @description EDMFit@version is set to the current FIMS package version.
  fit <- fit_edm(local_ff, method = "simplex")
  expect_equal(fit@version, utils::packageVersion("FIMS"))
})

## Error handling ----

test_that("fit_edm() errors when data is not a FIMSFrame", {
  #' @description fit_edm() throws an informative error if data is not a FIMSFrame.
  expect_error(fit_edm(list(), method = "simplex"), regexp = "FIMSFrame")
})

test_that("fit_edm() errors when FIMSFrame has no embeddings", {
  #' @description fit_edm() throws an error when no delay embeddings exist in data.
  data("data_big", package = "FIMS")
  empty_ff <- FIMSFrame(data_big)
  expect_error(fit_edm(empty_ff, method = "simplex"), regexp = "No delay embeddings")
})

test_that("fit_edm() errors for unknown embedding_name", {
  #' @description fit_edm() throws an error when the requested embedding_name does not exist.
  expect_error(
    fit_edm(local_ff, embedding_name = "does_not_exist"),
    regexp = "not found"
  )
})

test_that("fit_edm() errors when gp_phi_init has wrong length", {
  #' @description fit_edm() throws an error when gp_phi_init length does not equal E.
  expect_error(
    fit_edm(local_ff, method = "gp", gp_phi_init = c(0.1, 0.2)),
    regexp = "gp_phi_init"
  )
})

# edm_forecast() ----
## IO correctness ----

test_that("edm_forecast() returns a tibble with correct columns", {
  #' @description edm_forecast() returns a four-column tibble (step, time, forecast, se).
  fit <- fit_edm(local_ff, method = "simplex")
  fc  <- edm_forecast(fit, local_ff, n_ahead = 1L)
  expect_s3_class(fc, "tbl_df")
  expect_named(fc, c("step", "time", "forecast", "se"))
})

test_that("edm_forecast() n_ahead=1 returns a one-row tibble", {
  #' @description edm_forecast() with n_ahead=1 returns exactly one forecast row.
  fit <- fit_edm(local_ff, method = "simplex")
  fc  <- edm_forecast(fit, local_ff, n_ahead = 1L)
  expect_equal(nrow(fc), 1L)
  expect_equal(fc$step, 1L)
})

test_that("edm_forecast() step and time sequences are correct for n_ahead=5", {
  #' @description step runs 1:n_ahead and time runs last_time+1:last_time+n_ahead.
  fit <- fit_edm(local_ff, method = "simplex")
  fc  <- edm_forecast(fit, local_ff, n_ahead = 5L)
  expect_equal(nrow(fc), 5L)
  expect_equal(fc$step, 1:5)
  expect_equal(fc$time, 31:35)   # data_big has 30 years
})

test_that("edm_forecast() forecasts are finite for all methods", {
  #' @description Forecast values from simplex, smap, and gp are all finite.
  for (m in c("simplex", "smap", "gp")) {
    fit <- fit_edm(local_ff, method = m)
    fc  <- edm_forecast(fit, local_ff, n_ahead = 3L)
    expect_true(all(is.finite(fc$forecast)), info = paste("method:", m))
  }
})

test_that("edm_forecast() se column is all NA", {
  #' @description se column contains only NA_real_ (GP posterior variance not yet exposed).
  fit <- fit_edm(local_ff, method = "simplex")
  fc  <- edm_forecast(fit, local_ff, n_ahead = 3L)
  expect_true(all(is.na(fc$se)))
})

test_that("edm_forecast() h=1 matches last in-library prediction direction", {
  #' @description One-step forecast uses the most recent state vector as the query point.
  fit <- fit_edm(local_ff, method = "simplex")
  fc  <- edm_forecast(fit, local_ff, n_ahead = 1L)
  # Forecast must be a single positive number for a catch series
  expect_true(is.numeric(fc$forecast))
  expect_true(is.finite(fc$forecast))
})

## Error handling ----

test_that("edm_forecast() errors when fit is not an EDMFit", {
  #' @description edm_forecast() throws an error if fit is not an EDMFit object.
  expect_error(edm_forecast(list(), local_ff), regexp = "EDMFit")
})

test_that("edm_forecast() errors when data is not a FIMSFrame", {
  #' @description edm_forecast() throws an error if data is not a FIMSFrame object.
  fit <- fit_edm(local_ff, method = "simplex")
  expect_error(edm_forecast(fit, list()), regexp = "FIMSFrame")
})

test_that("edm_forecast() errors when embedding not found in data", {
  #' @description edm_forecast() errors when the FIMSFrame does not contain the fitted embedding.
  fit <- fit_edm(local_ff, method = "simplex")
  data("data_big", package = "FIMS")
  empty_ff <- FIMSFrame(data_big)
  expect_error(edm_forecast(fit, empty_ff), regexp = "not found")
})

test_that("edm_forecast() errors when n_ahead < 1", {
  #' @description edm_forecast() throws an error when n_ahead is zero or negative.
  fit <- fit_edm(local_ff, method = "simplex")
  expect_error(edm_forecast(fit, local_ff, n_ahead = 0L), regexp = "n_ahead")
})

# select_n_neighbors() ----
## IO correctness ----

test_that("select_n_neighbors() returns a tibble with correct columns", {
  #' @description select_n_neighbors() returns a tibble with n_neighbors, rho, rmse, optimal.
  skill <- select_n_neighbors(local_ff)
  expect_s3_class(skill, "tbl_df")
  expect_named(skill, c("n_neighbors", "rho", "rmse", "optimal"))
})

test_that("select_n_neighbors() has exactly one optimal row", {
  #' @description Exactly one row in the select_n_neighbors() result has optimal=TRUE.
  skill <- select_n_neighbors(local_ff)
  expect_equal(sum(skill$optimal), 1L)
})

test_that("select_n_neighbors() optimal row maximises rho", {
  #' @description The row flagged as optimal has the highest rho value.
  skill <- select_n_neighbors(local_ff)
  expect_equal(skill$n_neighbors[skill$optimal], skill$n_neighbors[which.max(skill$rho)])
})

test_that("select_n_neighbors() rho values are in [-1, 1]", {
  #' @description All rho values from select_n_neighbors() are valid Pearson correlations.
  skill <- select_n_neighbors(local_ff)
  expect_true(all(skill$rho >= -1 & skill$rho <= 1))
})

test_that("select_n_neighbors() rmse values are non-negative", {
  #' @description All RMSE values from select_n_neighbors() are non-negative.
  skill <- select_n_neighbors(local_ff)
  expect_true(all(skill$rmse >= 0))
})

test_that("select_n_neighbors() respects k_min and k_max", {
  #' @description k_min and k_max bound the n_neighbors search range.
  skill <- select_n_neighbors(local_ff, k_min = 5L, k_max = 8L)
  expect_equal(min(skill$n_neighbors), 5L)
  expect_equal(max(skill$n_neighbors), 8L)
  expect_equal(nrow(skill), 4L)
})

test_that("select_n_neighbors() auto-selects first embedding when embedding_name is NULL", {
  #' @description Passing NULL for embedding_name silently uses the first embedding.
  expect_no_error(select_n_neighbors(local_ff, embedding_name = NULL))
})

## Error handling ----

test_that("select_n_neighbors() errors when data is not a FIMSFrame", {
  #' @description select_n_neighbors() throws an error if data is not a FIMSFrame.
  expect_error(select_n_neighbors(list()), regexp = "FIMSFrame")
})

test_that("select_n_neighbors() errors when FIMSFrame has no embeddings", {
  #' @description select_n_neighbors() throws an error when no embeddings exist.
  data("data_big", package = "FIMS")
  empty_ff <- FIMSFrame(data_big)
  expect_error(select_n_neighbors(empty_ff), regexp = "No delay embeddings")
})

test_that("select_n_neighbors() errors for unknown embedding_name", {
  #' @description select_n_neighbors() errors when the requested embedding_name is not found.
  expect_error(
    select_n_neighbors(local_ff, embedding_name = "nonexistent"),
    regexp = "not found"
  )
})

# select_embedding_dimension() ----
## IO correctness ----

test_that("select_embedding_dimension() returns a tibble with correct columns", {
  #' @description select_embedding_dimension() returns a tibble with E, rho, rmse, optimal.
  edim <- select_embedding_dimension(local_ff, series_type = "catch",
                                     series_name = "fleet1")
  expect_s3_class(edim, "tbl_df")
  expect_named(edim, c("E", "rho", "rmse", "optimal"))
})

test_that("select_embedding_dimension() default sweep covers E=1 to 10", {
  #' @description Default E_min=1 and E_max=10 produce 10 rows.
  edim <- select_embedding_dimension(local_ff, series_type = "catch",
                                     series_name = "fleet1")
  expect_equal(nrow(edim), 10L)
  expect_equal(min(edim$E), 1L)
  expect_equal(max(edim$E), 10L)
})

test_that("select_embedding_dimension() has exactly one optimal row", {
  #' @description Exactly one row in the result has optimal=TRUE.
  edim <- select_embedding_dimension(local_ff, series_type = "catch",
                                     series_name = "fleet1")
  expect_equal(sum(edim$optimal), 1L)
})

test_that("select_embedding_dimension() optimal row maximises rho", {
  #' @description The optimal row has the highest rho value in the sweep.
  edim <- select_embedding_dimension(local_ff, series_type = "catch",
                                     series_name = "fleet1")
  expect_equal(edim$E[edim$optimal],
               edim$E[which.max(edim$rho)])
})

test_that("select_embedding_dimension() rho values are in [-1, 1]", {
  #' @description All non-NA rho values from the sweep are valid Pearson correlations.
  edim <- select_embedding_dimension(local_ff, series_type = "catch",
                                     series_name = "fleet1")
  finite_rho <- edim$rho[!is.na(edim$rho)]
  expect_true(all(finite_rho >= -1 & finite_rho <= 1))
})

test_that("select_embedding_dimension() rmse values are non-negative", {
  #' @description All non-NA RMSE values from the sweep are non-negative.
  edim <- select_embedding_dimension(local_ff, series_type = "catch",
                                     series_name = "fleet1")
  finite_rmse <- edim$rmse[!is.na(edim$rmse)]
  expect_true(all(finite_rmse >= 0))
})

test_that("select_embedding_dimension() respects E_min and E_max", {
  #' @description E_min and E_max bound the sweep range and row count.
  edim <- select_embedding_dimension(local_ff, series_type = "catch",
                                     series_name = "fleet1",
                                     E_min = 2L, E_max = 6L)
  expect_equal(nrow(edim), 5L)
  expect_equal(min(edim$E), 2L)
  expect_equal(max(edim$E), 6L)
})

test_that("select_embedding_dimension() E column is integer", {
  #' @description The E column in the output tibble is integer-typed.
  edim <- select_embedding_dimension(local_ff, series_type = "catch",
                                     series_name = "fleet1")
  expect_type(edim$E, "integer")
})

## Error handling ----

test_that("select_embedding_dimension() errors when data is not a FIMSFrame", {
  #' @description select_embedding_dimension() throws an error if data is not a FIMSFrame.
  expect_error(
    select_embedding_dimension(list(), "catch", "fleet1"),
    regexp = "FIMSFrame"
  )
})

test_that("select_embedding_dimension() errors when E_max < E_min", {
  #' @description select_embedding_dimension() throws an error when E_max is less than E_min.
  expect_error(
    select_embedding_dimension(local_ff, "catch", "fleet1",
                               E_min = 5L, E_max = 2L),
    regexp = "E_max"
  )
})

test_that("select_embedding_dimension() errors for unknown series", {
  #' @description select_embedding_dimension() throws an error for series not found in data.
  expect_error(
    select_embedding_dimension(local_ff, "catch", "no_such_fleet"),
    regexp = "No data found"
  )
})

# edm_skill() ----
## IO correctness ----

test_that("edm_skill() returns a one-row tibble with correct columns", {
  #' @description edm_skill() returns a tibble with columns rho, rmse, mae, n, method, embedding_name.
  fit  <- fit_edm(local_ff, method = "simplex")
  sk   <- edm_skill(fit, local_ff)
  expect_s3_class(sk, "tbl_df")
  expect_equal(nrow(sk), 1L)
  expect_named(sk, c("rho", "rmse", "mae", "n", "method", "embedding_name"))
})

test_that("edm_skill() rho is a valid Pearson correlation", {
  #' @description edm_skill() rho lies in [-1, 1] for all three methods.
  for (m in c("simplex", "smap", "gp")) {
    fit <- fit_edm(local_ff, method = m)
    sk  <- edm_skill(fit, local_ff)
    expect_true(sk$rho >= -1 & sk$rho <= 1, info = paste("method:", m))
  }
})

test_that("edm_skill() rmse is non-negative", {
  #' @description edm_skill() rmse is non-negative for all methods.
  for (m in c("simplex", "smap", "gp")) {
    fit <- fit_edm(local_ff, method = m)
    sk  <- edm_skill(fit, local_ff)
    expect_true(sk$rmse >= 0, info = paste("method:", m))
  }
})

test_that("edm_skill() mae is non-negative", {
  #' @description edm_skill() mae is non-negative for all methods.
  for (m in c("simplex", "smap", "gp")) {
    fit <- fit_edm(local_ff, method = m)
    sk  <- edm_skill(fit, local_ff)
    expect_true(sk$mae >= 0, info = paste("method:", m))
  }
})

test_that("edm_skill() n matches number of predictions", {
  #' @description edm_skill() n equals the length of predictions in the EDMFit object.
  fit <- fit_edm(local_ff, method = "simplex")
  sk  <- edm_skill(fit, local_ff)
  expect_equal(sk$n, length(get_predictions(fit)))
})

test_that("edm_skill() method column matches fit method", {
  #' @description edm_skill() method column matches the method stored in the EDMFit.
  for (m in c("simplex", "smap", "gp")) {
    fit <- fit_edm(local_ff, method = m)
    sk  <- edm_skill(fit, local_ff)
    expect_equal(sk$method, m)
  }
})

test_that("edm_skill() embedding_name column matches fit embedding_name", {
  #' @description edm_skill() embedding_name column matches the slot in EDMFit.
  fit <- fit_edm(local_ff, method = "simplex")
  sk  <- edm_skill(fit, local_ff)
  expect_equal(sk$embedding_name, get_embedding_name(fit))
})

test_that("edm_skill() simplex rmse is zero for perfect in-library self-prediction", {
  #' @description Simplex in-library rmse should be ~0 when predictions perfectly track targets.
  fit <- fit_edm(local_ff, method = "simplex")
  sk  <- edm_skill(fit, local_ff)
  expect_lt(sk$rmse, 1e-6)
})

## Error handling ----

test_that("edm_skill() errors when fit is not an EDMFit", {
  #' @description edm_skill() throws an error if fit is not an EDMFit object.
  expect_error(edm_skill(list(), local_ff), regexp = "EDMFit")
})

test_that("edm_skill() errors when data is not a FIMSFrame", {
  #' @description edm_skill() throws an error if data is not a FIMSFrame object.
  fit <- fit_edm(local_ff, method = "simplex")
  expect_error(edm_skill(fit, list()), regexp = "FIMSFrame")
})

test_that("edm_skill() errors when embedding not found in data", {
  #' @description edm_skill() errors when the FIMSFrame does not contain the fitted embedding.
  fit <- fit_edm(local_ff, method = "simplex")
  data("data_big", package = "FIMS")
  empty_ff <- FIMSFrame(data_big)
  expect_error(edm_skill(fit, empty_ff), regexp = "not found")
})

# autoplot.EDMFit() ----
## IO correctness ----

test_that("autoplot.EDMFit() returns a ggplot object", {
  #' @description autoplot.EDMFit() returns a ggplot object (or patchwork).
  fit <- fit_edm(local_ff, method = "simplex")
  p <- ggplot2::autoplot(fit, local_ff)
  expect_true(inherits(p, "ggplot") || inherits(p, "patchwork"))
})

## Error handling ----

test_that("autoplot.EDMFit() errors when object is not an EDMFit", {
  #' @description autoplot.EDMFit() throws an error if object is not an EDMFit.
  expect_error(autoplot.EDMFit(list(), local_ff), regexp = "EDMFit")
})

test_that("autoplot.EDMFit() errors when data is not a FIMSFrame", {
  #' @description autoplot.EDMFit() throws an error if data is not a FIMSFrame.
  fit <- fit_edm(local_ff, method = "simplex")
  expect_error(autoplot.EDMFit(fit, list()), regexp = "FIMSFrame")
})

test_that("autoplot.EDMFit() errors when embedding is missing from data", {
  #' @description autoplot.EDMFit() throws an error if embedding is not found in data.
  fit <- fit_edm(local_ff, method = "simplex")
  data("data_big", package = "FIMS")
  empty_ff <- FIMSFrame(data_big)
  expect_error(autoplot.EDMFit(fit, empty_ff), regexp = "not found")
})

# edm_compare() ----
## IO correctness ----

test_that("edm_compare() returns a tibble comparing requested methods", {
  #' @description edm_compare() fits multiple methods and returns a ranked skill tibble.
  cmp <- edm_compare(local_ff)
  expect_s3_class(cmp, "tbl_df")
  expect_named(cmp, c("rho", "rmse", "mae", "n", "method", "embedding_name", "best"))
  expect_equal(nrow(cmp), 3L)
  expect_equal(sum(cmp$best), 1L)
})

test_that("edm_compare() respects custom methods and arguments", {
  #' @description edm_compare() runs only specified methods and passes custom arguments.
  cmp <- edm_compare(
    local_ff,
    methods = c("simplex", "smap"),
    simplex_args = list(auto_select = TRUE),
    smap_args = list(theta = 2.0)
  )
  expect_equal(nrow(cmp), 2L)
  expect_true(all(cmp$method %in% c("simplex", "smap")))
})

## Error handling ----

test_that("edm_compare() errors when data is not a FIMSFrame", {
  #' @description edm_compare() throws an error if data is not a FIMSFrame object.
  expect_error(edm_compare(list()), regexp = "FIMSFrame")
})

test_that("edm_compare() errors for unknown methods", {
  #' @description edm_compare() throws an error if invalid method names are given.
  expect_error(edm_compare(local_ff, methods = c("invalid_method")), regexp = "Unknown method")
})

test_that("edm_compare() errors when methods vector is empty", {
  #' @description edm_compare() throws an error if methods vector is empty.
  expect_error(edm_compare(local_ff, methods = character(0)), regexp = "at least one method")
})

test_that("edm_compare() errors when embedding is missing", {
  #' @description edm_compare() throws an error if requested embedding_name is not found.
  expect_error(edm_compare(local_ff, embedding_name = "nonexistent"), regexp = "not found")
})

