# Instructions ----
#' This file follows the format generated by FIMS:::use_testthat_template().
#' Necessary tests include input and output (IO) correctness [IO
#' correctness], edge-case handling [Edge handling], and built-in errors and
#' warnings [Error handling]. See `?FIMS:::use_testthat_template` for more
#' information. Every test should have a @description tag, which can only span
#' one lines, that will be used in the bookdown report of the results from
#' {testthat}. This line can be more than 80 characters.

# recruitment_beverton_holt ----
## IO correctness ----
test_that("`recruitment_beverton_holt_create()` returns a backend handle", {
    #' @description Test that `recruitment_beverton_holt_create()` returns an integer handle.
    expect_type(
        object = recruitment_beverton_holt_create(0.78845736, log(1000000.0)),
        type = "integer"
    )
})

test_that("`recruitment_beverton_holt()` matches expected recruitment", {
    #' @description Test that `recruitment_beverton_holt()` returns 1090802.68 for a known Beverton-Holt input set.
    expect_equal(
        object = recruitment_beverton_holt(
            spawners = 9.55784 * 10^6,
            phi_0 = 0.0102562,
            logit_steep = 0.78845736,
            log_rzero = log(1000000.0)
        ),
        expected = 1090802.68,
        tolerance = 1
    )
})

## Error handling ----
test_that("`recruitment_beverton_holt()` rejects mismatched spawner/phi_0 lengths", {
    #' @description Test that `recruitment_beverton_holt()` errors when `phi_0` does not have length 1 or the same length as `spawners`.
    expect_error(
        object = recruitment_beverton_holt(
            spawners = c(1, 2, 3),
            phi_0 = c(0.1, 0.2),
            logit_steep = 0.78845736,
            log_rzero = log(1000000.0)
        ),
        regexp = "must have length 1 or match the length of the paired input"
    )
})

test_that("`recruitment_beverton_holt_create()` registers fixed and random effects", {
    #' @description Test that recruitment create calls register fixed and random effects when estimation types are provided.
    clear()

    before <- native_information_parameter_counts()

    recruitment_beverton_holt_create(
        logit_steep = 0.78845736,
        log_rzero = log(1000000.0),
        logit_steep_estimation_type = "fixed_effects",
        log_rzero_estimation_type = "random_effects"
    )

    after <- native_information_parameter_counts()

    expect_equal(
        object = after[["fixed_effects_parameters"]] - before[["fixed_effects_parameters"]],
        expected = 1L
    )
    expect_equal(
        object = after[["random_effects_parameters"]] - before[["random_effects_parameters"]],
        expected = 1L
    )
})
