# Instructions ----
#' This file follows the format generated by FIMS:::use_testthat_template().
#' Necessary tests include input and output (IO) correctness [IO
#' correctness], edge-case handling [Edge handling], and built-in errors and
#' warnings [Error handling]. See `?FIMS:::use_testthat_template` for more
#' information. Every test should have a @description tag, which can only span
#' one lines, that will be used in the bookdown report of the results from
#' {testthat}. This line can be more than 80 characters.

# check_mle_convergence ----
## Setup ----
make_mock_mle_input <- function() {
  list(dummy = TRUE)
}

make_mock_mle_obj <- function() {
  list(env = list(random = numeric()))
}

make_mock_mle_opt <- function(convergence = 0, message = NULL, par = numeric()) {
  list(
    convergence = convergence,
    message = message,
    par = par
  )
}

mock_gradient <- c(0.001, 0.5, -0.02)
mock_parameter_names <- c(
  "Recruitment.1.log_rzero.1",
  "Selectivity.2.slope.47",
  "Fleet.1.log_q.3"
)

mock_fimsfit <- function(input, obj, opt, sdreport, run_time) {
  list(
    tag = "mock_fit",
    input = input,
    obj = obj,
    opt = opt,
    sdreport = sdreport,
    run_time = run_time
  )
}

## IO correctness ----
test_that("check_mle_convergence() works with correct inputs", {
  #' @description Test that `check_mle_convergence()` returns NULL when convergence code is zero and the gradient is low.
  input <- make_mock_mle_input()
  obj <- make_mock_mle_obj()
  opt <- make_mock_mle_opt(convergence = 0)

  expect_no_warning(
    out <- FIMS:::check_mle_convergence(input, obj, opt, maxgrad = 1e-4)
  )
  expect_null(out)

  #' @description Test that `check_mle_convergence()` names the parameter with the largest absolute gradient when the gradient is above 1.
  expect_warning(
    object = FIMS:::check_mle_convergence(
      input,
      obj,
      opt,
      maxgrad = 5,
      gradient = c(0.001, 5, -0.02),
      parameter_names = mock_parameter_names
    ),
    regexp = "Largest absolute gradient is on \"Selectivity 2: slope (parameter_id 47)\"",
    fixed = TRUE
  )

  #' @description Test that `check_mle_convergence()` names the parameter with the largest absolute gradient when nlminb did not converge.
  expect_warning(
    object = FIMS:::check_mle_convergence(
      input,
      obj,
      make_mock_mle_opt(convergence = 1, message = "iteration limit reached"),
      maxgrad = 0.03,
      gradient = c(0.001, 0.01, -0.03),
      parameter_names = mock_parameter_names
    ),
    regexp = "Largest absolute gradient is on \"Fleet 1: log_q (parameter_id 3)\"",
    fixed = TRUE
  )
})

## Edge handling ----
test_that("check_mle_convergence() returns correct outputs for edge cases", {
  #' @description Test that `check_mle_convergence()` warns when nlminb convergence code is non-zero.
  input <- make_mock_mle_input()
  obj <- make_mock_mle_obj()
  opt <- make_mock_mle_opt(convergence = 1, message = "false convergence")

  expect_warning(
    object = FIMS:::check_mle_convergence(input, obj, opt, maxgrad = 1e-4),
    regexp = "Optimization failed convergence checks"
  )

  warning_text <- tryCatch(
    FIMS:::check_mle_convergence(input, obj, make_mock_mle_opt(), maxgrad = 5),
    warning = conditionMessage
  )
  #' @description Test that `check_mle_convergence()` keeps the gradient message when `gradient` is `NULL`.
  expect_match(warning_text, "Model does not seem converged")
  #' @description Test that `check_mle_convergence()` leaves out the gradient name when `gradient` is `NULL`.
  expect_no_match(warning_text, "Largest absolute gradient")

  #' @description Test that `check_mle_convergence()` falls back to indexed labels when the names do not line up with the gradient.
  expect_warning(
    object = FIMS:::check_mle_convergence(
      input,
      obj,
      make_mock_mle_opt(),
      maxgrad = 5,
      gradient = c(0.001, 5, -0.02),
      parameter_names = mock_parameter_names[1:2]
    ),
    regexp = "Largest absolute gradient is on \"p[2]\"",
    fixed = TRUE
  )

  #' @description Test that `check_mle_convergence()` names a parameter when every gradient is infinite.
  expect_warning(
    object = FIMS:::check_mle_convergence(
      input,
      obj,
      make_mock_mle_opt(),
      maxgrad = Inf,
      gradient = c(Inf, -Inf, Inf),
      parameter_names = mock_parameter_names
    ),
    regexp = "Largest absolute gradient is on \"Recruitment 1: log_rzero (parameter_id 1)\"",
    fixed = TRUE
  )

  #' @description Test that `check_mle_convergence()` leaves out the gradient name when every gradient is NaN.
  warning_text <- tryCatch(
    FIMS:::check_mle_convergence(
      input,
      obj,
      make_mock_mle_opt(),
      maxgrad = 5,
      gradient = c(NaN, NaN, NaN),
      parameter_names = mock_parameter_names
    ),
    warning = conditionMessage
  )
  expect_no_match(warning_text, "Largest absolute gradient")
})

## Error handling ----
test_that("check_mle_convergence() returns correct error messages", {
  #' @description Test that `check_mle_convergence()` warns for moderately high gradients and returns a diagnostic fit object.
  input <- make_mock_mle_input()
  obj <- make_mock_mle_obj()
  opt <- make_mock_mle_opt(convergence = 0)
  maxgrad <- 0.1
  out <- NULL

  testthat::with_mocked_bindings(
    FIMSFit = mock_fimsfit,
    print = function(x, ...) invisible(x),
    {
      expect_warning(
        object = out <- FIMS:::check_mle_convergence(input, obj, opt, maxgrad),
        regexp = "Optimization resulted in high gradients"
      )
    },
    .package = "FIMS"
  )

  expect_equal(object = out$tag, expected = "mock_fit")
  expect_identical(object = out$input, expected = input)

  #' @description Test that `check_mle_convergence()` names the parameter with the largest absolute gradient for moderately high gradients.
  testthat::with_mocked_bindings(
    FIMSFit = mock_fimsfit,
    print = function(x, ...) invisible(x),
    {
      expect_warning(
        object = FIMS:::check_mle_convergence(
          input,
          obj,
          opt,
          maxgrad = 0.5,
          gradient = mock_gradient,
          parameter_names = mock_parameter_names
        ),
        regexp = "Largest absolute gradient is on \"Selectivity 2: slope (parameter_id 47)\"",
        fixed = TRUE
      )
    },
    .package = "FIMS"
  )
})
