# Instructions ----
#' This file follows the format generated by FIMS:::use_testthat_template().
#' Necessary tests include input and output (IO) correctness [IO
#' correctness], edge-case handling [Edge handling], and built-in errors and
#' warnings [Error handling]. See `?FIMS:::use_testthat_template` for more
#' information. Every test should have a @description tag, which can only span
#' one lines, that will be used in the bookdown report of the results from
#' {testthat}. This line can be more than 80 characters.

# setup_default_DlnormDistribution ----
## Setup ----
data <- FIMS::FIMSFrame(data_big)

## IO correctness ----
test_that("`setup_default_DlnormDistribution()` works with correct inputs", {
  result <- FIMS:::setup_default_DlnormDistribution(value = 0.2, data = data)

  #' @description Test that output values are on the log scale for Dlnorm.
  expect_s3_class(result, "tbl_df")
  expect_true(all(result[["distribution"]] == "Dlnorm"))
  expect_true(all(result[["value"]] == log(0.2)))

  clear()
})

## Edge handling ----
test_that("`setup_default_DlnormDistribution()` works with edge cases", {
  #' @description Test that vector input currently errors because row sizing follows years, not input length.
  expect_error(
    object = FIMS:::setup_default_DlnormDistribution(value = c(0.2, 0.4), data = data),
    regexp = "must be size"
  )

  clear()
})

## Error handling ----
test_that("`setup_default_DlnormDistribution()` returns correct error messages", {
  #' @description Test that non-positive values return expected error.
  expect_error(
    object = FIMS:::setup_default_DlnormDistribution(value = 0, data = data),
    regexp = "positive and numeric"
  )

  clear()
})
