# Instructions ----
#' This file follows the format generated by FIMS:::use_testthat_template().
#' Necessary tests include input and output (IO) correctness [IO
#' correctness], edge-case handling [Edge handling], and built-in errors and
#' warnings [Error handling]. See `?FIMS:::use_testthat_template` for more
#' information. Every test should have a @description tag, which can only span
#' one lines, that will be used in the bookdown report of the results from
#' {testthat}. This line can be more than 80 characters.

# rcpp selectivity ----
## Setup ----
# Load or prepare any necessary data for testing

## IO correctness ----
test_that("rcpp logistic selectivity works with correct inputs", {
  # Create selectivity1
  selectivity1 <- create_selectivity("Logistic")

  set_variable_vector(selectivity1, "inflection_point", 10.0, "random_effects")
  set_variable_vector(selectivity1, "slope", 0.2, "assumed_known")
  #' @description Test that `get_id()` for `LogisticSelectivity` works.
  expect_equal(get_module_id(selectivity1), 1)
  #' @description Test that the `inflection_point` value is set to 10.0.
  expect_equal(get_variable_vector(selectivity1, "inflection_point")[["values"]], 10.0)
  #' @description Test that the `inflection_point` estimation status is set to "random_effects".
  expect_equal(get_variable_vector(selectivity1, "inflection_point")[["estimation_status"]], "random_effects")
  #' @description Test that the `slope` value is set to 0.2.
  expect_equal(get_variable_vector(selectivity1, "slope")[["values"]], 0.2)
  #' @description Test that the `evaluate()` works for `LogisticSelectivity`.
  expect_equal(evaluate_selectivity(selectivity1, 10.0), 0.5)

  # Create selectivity2
  selectivity2 <- create_selectivity("Logistic")
  #' @description Test that `get_id()` for `LogisticSelectivity` works when a second object is created.
  expect_equal(get_module_id(selectivity2), 2)

  clear()
})

test_that("rcpp double logistic selectivity works with correct inputs", {
  # Create selectivity1
  selectivity1 <- create_selectivity("DoubleLogistic")

  set_variable_vector(
    selectivity1, "inflection_point_asc",
    10.5, "assumed_known"
  )
  set_variable_vector(selectivity1, "slope_asc", 0.2, "fixed_effects")
  set_variable_vector(
    selectivity1, "inflection_point_desc",
    15.0, "assumed_known"
  )
  set_variable_vector(selectivity1, "slope_desc", 0.05, "assumed_known")

  #' @description Test that `get_id()` for `DoubleLogisticSelectivity` works.
  expect_equal(get_module_id(selectivity1), 1)
  #' @description Test that the `inflection_point_asc` value is set to 10.5.
  expect_equal(get_variable_vector(selectivity1, "inflection_point_asc")[["values"]], 10.5)
  #' @description Test that the `slope_asc` value is set to 0.2.
  expect_equal(get_variable_vector(selectivity1, "slope_asc")[["values"]], 0.2)
  #' @description Test that `evaluate()` works for `DoubleLogisticSelectivity`.
  expect_equal(
    evaluate_selectivity(selectivity1, 34.5),
    # Line below equals 0.2716494
    1.0 / (1.0 + exp(-(34.5 - 10.5) * 0.2)) * (1.0 - 1.0 / (1.0 + exp(-(34.5 - 15) * 0.05))),
    tolerance = 0.0000001
  )

  # Create selectivity2
  selectivity2 <- create_selectivity("DoubleLogistic")

  set_variable_vector(
    selectivity2, "inflection_point_asc",
    10.5, "random_effects"
  )
  set_variable_vector(selectivity2, "slope_asc", 0.2, "random_effects")
  set_variable_vector(
    selectivity2, "inflection_point_desc",
    15.0, "random_effects"
  )
  set_variable_vector(selectivity2, "slope_desc", 0.05, "random_effects")


  #' @description Test that `get_id()` for `DoubleLogisticSelectivity` works when a second object is created.
  expect_equal(get_module_id(selectivity2), 2)
  #' @description Test that the `inflection_point_asc` value is set to 10.5.
  expect_equal(get_variable_vector(selectivity2, "inflection_point_asc")[["values"]], 10.5)
  #' @description Test that the `slope_asc` value is set to 0.2.
  expect_equal(get_variable_vector(selectivity2, "slope_asc")[["values"]], 0.2)
  #' @description Test that the `inflection_point_asc` estimation status is set to "random_effects".
  expect_equal(get_variable_vector(selectivity2, "inflection_point_asc")[["estimation_status"]], "random_effects")
  #' @description Test that the `inflection_point_desc` estimation status is set to "random_effects".
  expect_equal(get_variable_vector(selectivity2, "inflection_point_desc")[["estimation_status"]], "random_effects")
  #' @description Test that the `slope_asc` estimation status is set to "random_effects".
  expect_equal(get_variable_vector(selectivity2, "slope_asc")[["estimation_status"]], "random_effects")
  #' @description Test that the `slope_desc` estimation status is set to "random_effects".
  expect_equal(get_variable_vector(selectivity2, "slope_desc")[["estimation_status"]], "random_effects")
  #' @description Test that `evaluate()` works for `DoubleLogisticSelectivity` when all parameters are set to "random_effects".
  expect_equal(
    evaluate_selectivity(selectivity2, 34.5),
    # Line below equals 0.2716494
    1.0 / (1.0 + exp(-(34.5 - 10.5) * 0.2)) * (1.0 - 1.0 / (1.0 + exp(-(34.5 - 15) * 0.05))),
    tolerance = 0.0000001
  )
  clear()
})

test_that("rcpp age specific selectivity works with correct inputs", {
  # Create selectivity1
  selectivity1 <- create_selectivity("AgeSpecific")
  set_variable_vector(
    selectivity1, "logit_sel_at_age",
    c(1, 2), rep("fixed_effects", 2)
  )

  set_selectivity_ages(selectivity1, ages = c(2, 3))

  #' @description Test that `get_id()` for `AgeSpecific` works.
  expect_equal(get_module_id(selectivity1), 1)
  #' @description Test that the first `logit_sel_at_age` value is set to 1.
  expect_equal(
    get_variable_vector(selectivity1, "logit_sel_at_age")[["values"]][1], 1
  )
  #' @description Test that `evaluate()` works for `AgeSpecific` (age=2).
  expect_equal(
    evaluate_selectivity(selectivity1, 2.0),
    1.0 / (1.0 + exp(-1.0)), # inverse logit equation
    tolerance = 0.0000001
  )
  #' @description Test that `evaluate()` works for `AgeSpecific` (age=3).
  expect_equal(
    evaluate_selectivity(selectivity1, 3.0),
    1.0 / (1.0 + exp(-2.0)), # inverse logit equation
    tolerance = 0.0000001
  )
  #' @description Test that out-of-range ages throw an informative error.
  expect_error(evaluate_selectivity(selectivity1, 10), "out of bounds")

  # Create selectivity2
  selectivity2 <- create_selectivity("AgeSpecific")
  set_variable_vector(selectivity2, "logit_sel_at_age",
                      1, "random_effects")
  set_selectivity_ages(selectivity2, ages = 1)

  #' @description Test that `get_id()` for `AgeSpecific` works when a second object is created.
  expect_equal(get_module_id(selectivity2), 2)
  #' @description Test that the `logit_sel_at_age` value is set to 1.
  expect_equal(
    get_variable_vector(selectivity2, "logit_sel_at_age")[["values"]][1], 1.0)
  #' @description Test that the `logit_sel_at_age` estimation type is set to "random_effects".
  expect_equal(
    get_variable_vector(selectivity2, "logit_sel_at_age")[["estimation_status"]][1],
                        "random_effects")
  #' @description Test that `evaluate()` works for `AgeSpecific` with "random_effects".
  expect_equal(
    evaluate_selectivity(selectivity2, 1),
    # Line below equals 0.2716494
    1.0 / (1.0 + exp(-1.0)), # inverse logit equation
    tolerance = 0.0000001
  )
  clear()
})

## Edge handling ----
test_that("rcpp selectivity returns correct outputs for edge cases", {
  # emptyLogistic
  emptyLogistic <- create_selectivity("Logistic")
  #' @description Test that rcpp selectivity returns default values when no parameters are set for input values of 20.
  expect_equal(
    object = evaluate_selectivity(emptyLogistic, 20),
    expected = 0.5
  )

  # emptyDoubleLogistic
  emptyDoubleLogistic <- create_selectivity("DoubleLogistic")
  #' @description Test that rcpp double selectivity returns default values when no parameters are set for input values of 20.
  expect_equal(
    object = evaluate_selectivity(emptyDoubleLogistic, 20),
    expected = 0.25
  )

  # Did not specify a default value test for AgeSpecific
  # This test is not appropriate: inputs are used in indices and not calculation
  # Test of 'out of bounds', above, is already supplied above
})

## Error handling ----
test_that("rcpp age specific selectivity validates age inputs", {
  selectivity <- create_selectivity("AgeSpecific")

  #' @description Test that `set_selectivity_ages()` requires either `min_age` or `ages`.
  expect_error(
    set_selectivity_ages(selectivity),
    "requires either `min_age` or `ages`"
  )

  #' @description Test that `set_selectivity_ages()` requires `n_ages` when `min_age` is provided.
  expect_error(
    set_selectivity_ages(selectivity, min_age = 1),
    "requires `n_ages` when an `ages` vector"
  )

  #' @description Test that `set_selectivity_ages()` rejects mismatched `n_ages` and `ages` lengths.
  expect_error(
    set_selectivity_ages(selectivity, n_ages = 2, ages = c(1, 2, 3)),
    "requires `n_ages` to equal the length of `ages`"
  )

  clear()
})
