write("test-check_fims.R", file = "debug_log.txt", append = TRUE)

# Instructions ----
#' This file follows the format generated by FIMS:::use_testthat_template().
#' Necessary tests include input and output (IO) correctness [IO
#' correctness], edge-case handling [Edge handling], and built-in errors and
#' warnings [Error handling]. See `?FIMS:::use_testthat_template` for more
#' information. Every test should have a @description tag, which can span
#' multiple lines, that will be used in the bookdown report of the results from
#' {testthat}.

# check_fims ----
## Setup ----
# Load or prepare any necessary data for testing

## IO correctness ----
# Currently there are no checks. We could make a fake package to run through
# all of the functions inside of check_fims() but this is difficult with all of
# the specialized folders and google testing.

## Edge handling ----
# No edge case handling right now.

## Error handling ----
# Please remove/comment out the test template below if there are no built-in errors/warnings.
test_that("check_fims() returns correct error messages", {
  #' @description Test that check_fims() returns expected error because it is
  #' not in the appropriate directory.
  current_directory <- getwd()
  setwd(tempdir())
  on.exit(setwd(current_directory), add = TRUE)
  expect_error(
    object = check_fims(),
    regexp = "does not end in FIMS"
  )
})
