# Instructions ----
#' This file follows the format generated by FIMS:::use_testthat_template().
#' Necessary tests include input and output (IO) correctness [IO
#' correctness], edge-case handling [Edge handling], and built-in errors and
#' warnings [Error handling]. See `?FIMS:::use_testthat_template` for more
#' information. Every test should have a @description tag, which can only span
#' one lines, that will be used in the bookdown report of the results from
#' {testthat}. This line can be more than 80 characters.

# EmpiricalMaturity ----
## Setup ----
clear()
maturity_values <- c(0.1, 0.5, 0.9)
empirical_maturity <- methods::new(EmpiricalMaturity)
empirical_maturity$n_ages$set(3)
empirical_maturity$min_age$set(2)
empirical_maturity$maturity_at_age$resize(3)
for (i in seq_along(maturity_values)) {
  empirical_maturity$maturity_at_age[i][["value"]] <- maturity_values[i]
}
empirical_maturity2 <- methods::new(EmpiricalMaturity)

## IO correctness ----
test_that("EmpiricalMaturity evaluate() works with correct inputs", {
  #' @description Test that evaluate() returns the input proportion mature for each age.
  expect_equal(empirical_maturity$evaluate(2), 0.1)
  expect_equal(empirical_maturity$evaluate(3), 0.5)
  expect_equal(empirical_maturity$evaluate(4), 0.9)
})

test_that("EmpiricalMaturity get_id() works with correct inputs", {
  #' @description Test that the ids of two EmpiricalMaturity objects increase by one.
  expect_equal(empirical_maturity2$get_id() - empirical_maturity$get_id(), 1)
})

## Edge handling ----
# No edge cases to test.

## Error handling ----
test_that("EmpiricalMaturity evaluate() returns correct error messages", {
  #' @description Test that evaluate() errors for an age outside the modeled ages.
  expect_error(empirical_maturity$evaluate(5), "outside the modeled ages")
})

clear()
