# Instructions ----
#' This file follows the format generated by FIMS:::use_testthat_template().
#' Necessary tests include input and output (IO) correctness [IO
#' correctness], edge-case handling [Edge handling], and built-in errors and
#' warnings [Error handling]. See `?FIMS:::use_testthat_template` for more
#' information. Every test should have a @description tag, which can span
#' multiple lines, that will be used in the bookdown report of the results from
#' {testthat}.

# Deterministic test ----
## Setup ----

## IO correctness ----
test_that("deterministic run works with correct inputs", {
  # Run FIMS surplus production without wrappers
  result <- setup_and_run_surplus_production_model(
    bayesian_mode = TRUE, estimation_mode = FALSE)

  #' @description Compare FIMS growth rate with correct value
  expect_equal(
    result[["obj"]][["par"]][1] |> unname(), 
    data_limited_tuna_results |>
    dplyr::filter(label == "growth_rate") |> dplyr::pull(median))

  #' @description Compare FIMS carrying capacity with correct value
  expect_equal(
    result[["obj"]][["par"]][2] |> unname(), 
    data_limited_tuna_results |>
    dplyr::filter(label == "carrying_capacity") |> dplyr::pull(median))

  #' @description Compare FIMS carrying capacity with correct value, use tolerance as value is approximated using marginalization method
  expect_equal(
    result[["report"]][["mean_q"]][2] |> unlist(), 
    data_limited_tuna_results |>
    dplyr::filter(label == "q") |> dplyr::pull(median), tolerance = 1e-6)
  

  #' @description Compare FIMS biomass with correct biomass.
  for(i in 1:24) {
    expect_equal(
      (result$report$biomass |> unlist())[i],
      (data_limited_tuna_results |>
        dplyr::filter(label == "biomass") |> dplyr::pull(median))[i],
        tolerance = 1e-6
    )
  }

  #' @description Compare FIMS depletion with correct depletion.
  for(i in 1:24) {
    expect_equal(
      (result$report$depletion |> unlist())[i],
      (data_limited_tuna_results |>
        dplyr::filter(label == "depletion") |> dplyr::pull(median))[i]
    )
  }

  #' @description Compare FIMS reference points with JABBA reference points.
  #' TODO: uncomment after fixing tests; differences are due to rounding in JABBA output
#   expect_equal(
#     result$report$fmsy |> unlist() |> unname(),
#     jabba_output$estimates |> 
#       dplyr::filter(rownames(jabba_output$estimates) == "Hmsy") |> 
#       dplyr::select(mu) |> as.vector() |> unlist() |> unname()
#   )
#   expect_equal(
#       result$report$bmsy |> unlist() |> unname(),
#       jabba_output$estimates |> 
#         dplyr::filter(rownames(jabba_output$estimates) == "SBmsy") |> 
#         dplyr::select(mu) |> as.vector() |> unlist() |> unname()
#   )
#   expect_equal(
#       result$report$msy |> unlist() |> unname(),
#       jabba_output$estimates |> 
#         dplyr::filter(rownames(jabba_output$estimates) == "MSY") |> 
#         dplyr::select(mu) |> as.vector() |> unlist() |> unname()
#   )

    # depletion nll
    nll_depletion <- 0
    sd_depletion <- data_limited_tuna_results |>
        dplyr::filter(label == "sigma2_depletion") |> dplyr::pull(median) |>
        sqrt()
    for(i in seq_along(result[["report"]][["depletion"]] |> unlist())) {
    nll_depletion <- nll_depletion + 
        -dnorm(log((result[["report"]][["depletion"]] |> unlist())[i]),
        (result$report$log_depletion_expected |> unlist())[i],
        sd_depletion, 
        TRUE
        )
    }
   
    survey_index_data <- data_limited_tuna |> dplyr::filter(type == "index")
    idx <- which(survey_index_data$value != -999)
    survey_index <- survey_index_data[idx,] |> dplyr::select(value) |> 
        as.vector() |> unlist() |> unname()
    nll_index <- rep(0, length(survey_index))
    sd_index <- data_limited_tuna_results |>
        dplyr::filter(label == "sigma2_obs") |> dplyr::pull(median) |>
        sqrt()
    survey_index_expected <- (result$report$log_index_expected)[[2]][idx] 
    for(i in seq_along(survey_index)){
    nll_index[i] = -dlnorm(
        survey_index[i],
        survey_index_expected[i],
        sd_index,
        TRUE
    )
    }
    #' @description Check that FIMS nll matches expected nlls
    skip("nll values are not matching, need to investigate further")
    expect_equal(c(nll_depletion, sum(nll_index)), result$report$nll_components,
      tolerance = 1e-6)

})

test_that("MLE run works", {
  # Run FIMS surplus production without wrappers
  result <- setup_and_run_surplus_production_model(
    bayesian_mode = FALSE, estimation_mode = TRUE)

  
  #' @description Compare FIMS growth rate with stan value
  skip("Need to redo tests for MLE run using new testing criteria")
  expect_near(
    result[["opt"]][["par"]][1] |> exp()|> unname(), 
    data_limited_tuna_results |>
    dplyr::filter(label == "growth_rate") |> dplyr::pull(median))

  #' @description Compare FIMS carrying capacity with stan value
  skip("Need to redo tests for MLE run using new testing criteria")
  expect_near(
    result[["opt"]][["par"]][2] |> exp() |> unname(), 
    data_limited_tuna_results |>
    dplyr::filter(label == "carrying_capacity") |> dplyr::pull(median))

  #' @description Compare FIMS q with stan value
  skip("Need to redo tests for MLE run using new testing criteria")
  expect_near(
    result[["report"]][["mean_q"]][2] |> unlist(), 
    data_limited_tuna_results |>
    dplyr::filter(label == "q") |> dplyr::pull(median))

   #' @description Compare FIMS biomass with stan biomass.
  skip("Need to redo tests for MLE run using new testing criteria")
  for(i in c(1:3, 23, 24)) {
    idx <- 1
    expect_near(
      (result$report$biomass |> unlist())[i],
      (data_limited_tuna_results |>
        dplyr::filter(label == "biomass") |> dplyr::pull(median))[idx]
    )
    idx <- idx + 1
  }

  #' @description Compare FIMS depletion with stan depletion.
  skip("Need to redo tests for MLE run using new testing criteria")
  for(i in c(1:3, 23, 24)) {
    idx <- 1
    expect_near(
      (result$report$depletion |> unlist())[i],
      (data_limited_tuna_results |>
        dplyr::filter(label == "depletion") |> dplyr::pull(median))[idx]
    )
    idx <- idx + 1
  }

  
})
