# Instructions ----
#' This file follows the format generated by FIMS:::use_testthat_template().
#' Necessary tests include input and output (IO) correctness [IO
#' correctness], edge-case handling [Edge handling], and built-in errors and
#' warnings [Error handling]. See `?FIMS:::use_testthat_template` for more
#' information. Every test should have a @description tag, which can span
#' multiple lines, that will be used in the bookdown report of the results from
#' {testthat}.

# rcpp fleet ----
## Setup ----

# Load or prepare any necessary data for testing
## IO correctness ----
test_that("rcpp fleet works with correct inputs", {
  # Create selectivity for fleet 1
  selectivity_fleet1 <- methods::new(LogisticSelectivity)
  #' @description Test that one selectivity module can be set up without any errors and it has the appropriate id.
  expect_equal((selectivity_fleet1$get_id()), 1)

  # Create selectivity for fleet 2
  selectivity_fleet2 <- methods::new(LogisticSelectivity)
  #' @description Test that two selectivity modules can be set up without any errors and they have the appropriate ids.
  expect_equal((selectivity_fleet2$get_id()), 2)

  # Add selectivity to fleet
  fleet1 <- methods::new(Fleet)
  fleet2 <- methods::new(Fleet)
  #' @description Test that rcpp fleet interface works with the first `LogisticSelectivity` module and no output, errors, messages, or warnings are produced when setting the SelectivityIDs for the fleets.
  expect_silent(fleet1$SetSelectivityID(selectivity_fleet1$get_id()))
  #' @description Test that rcpp fleet interface works with the second `LogisticSelectivity` module and no output, errors, messages, or warnings are produced when setting the SelectivityIDs for the fleets.
  expect_silent(fleet2$SetSelectivityID(selectivity_fleet2$get_id()))

  #' @description Test that setting the age-composition ID works within the fleet module.
  expect_silent(fleet1$SetObservedAgeCompDataID(1))
  #' @description Test that getting the age-composition ID works within the fleet module.
  expect_equal(fleet1$GetObservedAgeCompDataID(), 1)

  #' @description Test that setting the index ID works within the fleet module.
  expect_silent(fleet1$SetObservedIndexDataID(1))
  #' @description Test that getting the index ID works within the fleet module.
  expect_equal(fleet1$GetObservedIndexDataID(), 1)

  clear()
})

## Edge handling ----
# No edge cases to test for this interface.


## Error handling ----
test_that("rcpp fleet returns correct error messages", {
  fleet1 <- methods::new(Fleet)
  #' @description Test that the rcpp fleet interface returns an error when given a string as a selectivity ID rather than an integer.
  expect_error(fleet1$SetSelectivityID("id"))
  #' @description Test that the rcpp fleet interface returns an error when given a string as an age-composition ID rather than an integer.
  expect_error(fleet1$SetObservedAgeCompDataID("id"))
  #' @description Test that the rcpp fleet interface returns an error when given a string as an length-composition ID rather than an integer.
  expect_error(fleet1$SetObservedLengthCompDataID("id"))
  #' @description Test that the rcpp fleet interface returns an error when given a string as an index ID rather than an integer.
  expect_error(fleet1$SetObservedIndexDataID("id"))
  clear()
})
