# Instructions ----
#' This file follows the format generated by FIMS:::use_testthat_template().
#' Necessary tests include input and output (IO) correctness [IO
#' correctness], edge-case handling [Edge handling], and built-in errors and
#' warnings [Error handling]. See `?FIMS:::use_testthat_template` for more
#' information. Every test should have a @description tag, which can only span
#' one lines, that will be used in the bookdown report of the results from
#' {testthat}. This line can be more than 80 characters.

# get_number_of_parameters ----
## Setup ----
# Load or prepare any necessary data for testing
fit_with_optimization_big <- FIMS::fit_with_optimization_big
fit_without_optimization_big <- FIMS::fit_without_optimization_big

## IO correctness ----
test_that("`get_number_of_parameters()` works with fit_with_optimization_big", {
  expected_n_total <- length(fit_with_optimization_big@obj[["env"]][["last.par.best"]])
  expected_n_fixed_effects <- length(fit_with_optimization_big@obj[["par"]])
  expected_n_random_effects <- length(fit_with_optimization_big@obj[["env"]]$parList()[["re"]])
  number_of_parameters <- get_number_of_parameters(fit_with_optimization_big)
  expected_vector <- c(
    fixed_effects = expected_n_fixed_effects,
    random_effects = expected_n_random_effects
  )
  #' @description Test that `get_number_of_parameters()` returns correct output for the `number_of_parameters` slot.
  expect_equal(
    object = number_of_parameters,
    expected = fit_with_optimization_big@number_of_parameters
  )
  #' @description Test that `get_number_of_parameters()` returns correct names for the `number_of_parameters` slot.
  expect_equal(
    object = number_of_parameters,
    expected = expected_vector
  )
})

test_that("`get_number_of_parameters()` works with fit_without_optimization_big", {
  expected_n_total <- length(fit_without_optimization_big@obj[["env"]][["last.par.best"]])
  expected_n_fixed_effects <- length(fit_without_optimization_big@obj[["par"]])
  expected_n_random_effects <- length(fit_without_optimization_big@obj[["env"]]$parList()[["re"]])
  number_of_parameters <- get_number_of_parameters(fit_without_optimization_big)
  expected_vector <- c(
    fixed_effects = expected_n_fixed_effects,
    random_effects = expected_n_random_effects
  )
  #' @description Test that `get_number_of_parameters()` returns correct output for the `number_of_parameters` slot.
  expect_equal(
    object = number_of_parameters,
    expected = fit_without_optimization_big@number_of_parameters
  )
  #' @description Test that `get_number_of_parameters()` returns correct names for the `number_of_parameters` slot.
  expect_equal(
    object = number_of_parameters,
    expected = expected_vector
  )
})

## Edge handling ----
test_that("`get_number_of_parameters()` returns correct outputs for edge cases", {
  #' @description Test that `get_number_of_parameters()` returns an error when given invalid input.
  expect_error(
    object = get_number_of_parameters("invalid_input")
  )
})

## Error handling ----
# No built-in errors to test.
