# Instructions ----
#' This file follows the format generated by FIMS:::use_testthat_template().
#' Necessary tests include input and output (IO) correctness [IO
#' correctness], edge-case handling [Edge handling], and built-in errors and
#' warnings [Error handling]. See `?FIMS:::use_testthat_template` for more
#' information. Every test should have a @description tag, which can span
#' multiple lines, that will be used in the bookdown report of the results from
#' {testthat}.

# create_default_* ----
## Setup ----
data <- FIMS::FIMSFrame(data1)

default_configurations <- create_default_configurations(data)

# create_default_parameters ----
## IO correctness ----
test_that("`create_default_parameters()` works with correct inputs", {
  result <- create_default_parameters(
    configurations = default_configurations,
    data = data
  )
  result_unnested <- result |>
    tidyr::unnest(cols = data)

  #' @description Test that the main output is a `tbl_df`.
  expect_s3_class(result, "tbl_df")
  #' @description Test that the main output table has the correct column structure.
  expect_equal(
    colnames(result),
    c("model_family", "module_name", "fleet_name", "data")
  )
  #' @description Test that the `data` column is structured to hold nested information.
  expect_true(is.list(result[["data"]]))
  #' @description Test that the nested information within the `data` column is also a `tbl_df`.
  expect_s3_class(result[["data"]][[1]], "tbl_df")
  #' @description Test that the nested data table has the correct column structure.
  expect_equal(
    colnames(result[["data"]][[1]]),
    c(
      "module_type", "label", "distribution_link", "age", "length", "time",
      "value", "estimation_type", "distribution_type", "distribution"
    )
  )
  #' @description Test that the generated parameter values have not changed 
  #' from the accepted snapshot.
  expect_snapshot_file(
    save_csv(result_unnested),
    "default_parameters.csv",
    compare = compare_file_text
  )
})

## Edge handling ----
# No edge cases to test.

## Error handling ----
# No built-in errors to test.

# TODO: Add additional tests for internal (unexposed) functions,
# such as create_default_population().
