# Instructions ----
#' This file follows the format generated by FIMS:::use_testthat_template().
#' Necessary tests include input and output (IO) correctness [IO
#' correctness], edge-case handling [Edge handling], and built-in errors and
#' warnings [Error handling]. See `?FIMS:::use_testthat_template` for more
#' information. Every test should have a @description tag, which can only span
#' one lines, that will be used in the bookdown report of the results from
#' {testthat}. This line can be more than 80 characters.

# rcpp fleet ----
## Setup ----

# Load or prepare any necessary data for testing
## IO correctness ----
test_that("rcpp fleet works with correct inputs", {
  # Create selectivity for fleet 1
  selectivity_fleet1 <- create_selectivity("Logistic")
  #' @description Test that one selectivity module can be set up without any errors and it has the appropriate id.
  expect_equal(get_module_id(selectivity_fleet1), 1)

  # Create selectivity for fleet 2
  selectivity_fleet2 <- create_selectivity("Logistic")
  #' @description Test that two selectivity modules can be set up without any errors and they have the appropriate ids.
  expect_equal(get_module_id(selectivity_fleet2), 2)

  # Add selectivity to fleet
  fleet1 <- create_fleet()
  fleet2 <- create_fleet()
  #' @description Test that rcpp fleet interface works with the first `LogisticSelectivity` module and no output, errors, messages, or warnings are produced when setting the selectivity for the fleets.
  expect_silent(set_fleet_selectivity(fleet1, selectivity_fleet1))
  #' @description Test that rcpp fleet interface works with the second `LogisticSelectivity` module and no output, errors, messages, or warnings are produced when setting the selectivity for the fleets.
  expect_silent(set_fleet_selectivity(fleet2, selectivity_fleet2))
  #' @description Test that the linked selectivity can be read back from the fleet module.
  expect_equal(
    get_fleet_selectivity_id(fleet1), get_module_id(selectivity_fleet1)
  )

  #' @description Test that setting the observed data links works within the fleet module.
  age_comp <- create_data("age_comp", 1, 1)
  index <- create_data("index", 1)
  expect_silent(
    set_fleet_observed_data(fleet1, age_comp = age_comp, index = index)
  )
  #' @description Test that getting the observed data ids works within the fleet module.
  expect_equal(
    get_fleet_observed_data_ids(fleet1)[["age_comp"]], get_module_id(age_comp)
  )
  expect_equal(
    get_fleet_observed_data_ids(fleet1)[["index"]], get_module_id(index)
  )
  #' @description Test that a data kind the fleet was not given reads back as -999.
  expect_equal(get_fleet_observed_data_ids(fleet1)[["catch"]], -999)

  #' @description Test that setting and getting the fleet name continue to work.
  expect_silent(set_fleet_name(fleet1, "fleet one"))
  expect_equal(get_fleet_name(fleet1), "fleet one")

  #' @description Test that observed units can be assigned through the interface.
  expect_silent(set_fleet_units(fleet1, "numbers", "numbers"))

  clear()
})


## Error handling ----
test_that("rcpp fleet returns correct error messages", {
  fleet1 <- create_fleet()
  selectivity <- create_selectivity("Logistic")
  #' @description Test that the fleet interface rejects a module of the wrong kind as a selectivity.
  expect_error(set_fleet_selectivity(fleet1, fleet1), "must be a .*Selectivity")
  #' @description Test that the fleet interface rejects a module of the wrong kind as observed data.
  expect_error(
    set_fleet_observed_data(fleet1, age_comp = selectivity),
    "must be a .*Data"
  )
  #' @description Test that the fleet interface rejects an object that is not a module at all.
  expect_error(
    set_fleet_selectivity(fleet1, "id"),
    "must be a FIMS module or a single numeric module ID"
  )
  clear()
})
