# Instructions ----
#' This file follows the format generated by FIMS:::use_testthat_template().
#' Necessary tests include input and output (IO) correctness [IO
#' correctness], edge-case handling [Edge handling], and built-in errors and
#' warnings [Error handling]. See `?FIMS:::use_testthat_template` for more
#' information. Every test should have a @description tag, which can only span
#' one lines, that will be used in the bookdown report of the results from
#' {testthat}. This line can be more than 80 characters.

load(testthat::test_path("fixtures", "integration_test_data.RData"))

test_that("CatchAtAge derived quantity report requests reach TMB reports", {
  #' @description Test that a requested derived quantity is reported with the requested front-end name.
  result <- setup_and_run_FIMS_without_wrappers(
    iter_id = 1,
    om_input_list = om_input_list,
    om_output_list = om_output_list,
    em_input_list = em_input_list,
    estimation_mode = FALSE,
    random_effects = c(recruitment = "log_devs"),
    derived_quantity_report_requests = list(
      list(
        component_type = "population",
        quantity_name = "spawning_biomass",
        report_se = TRUE,
        report_value = TRUE,
        report_name = "requested_spawning_biomass"
      )
    )
  )

  expect_true("requested_spawning_biomass" %in% names(result[["report"]]))
  expect_length(
    result[["report"]][["requested_spawning_biomass"]],
    om_input_list[[1]][["nyr"]] + 1
  )
})

test_that("CatchAtAge derived quantity report requests get backend uncertainty", {
  #' @description Test that requested derived quantity uncertainty is calculated through the FIMS backend.
  result <- suppressWarnings(
    setup_and_run_FIMS_without_wrappers(
      iter_id = 1,
      om_input_list = om_input_list,
      om_output_list = om_output_list,
      em_input_list = em_input_list,
      estimation_mode = TRUE,
      random_effects = NULL,
      preserve_state = TRUE,
      derived_quantity_report_requests = list(
        list(
          component_type = "population",
          quantity_name = "spawning_biomass",
          report_se = TRUE,
          report_value = TRUE,
          report_name = "requested_spawning_biomass"
        )
      )
    )
  )
  withr::defer(FIMS::clear())

  parameter_names <- names(FIMS:::get_parameter_names(result[["obj"]][["par"]]))
  names(result[["obj"]][["par"]]) <- parameter_names
  names(result[["sdr"]][["par.fixed"]]) <- parameter_names
  dimnames(result[["sdr"]][["cov.fixed"]]) <- list(parameter_names, parameter_names)

  backend_report_std <- attr(result[["sdr"]], "fims_backend_report")
  adreport_payload <- attr(result[["sdr"]], "fims_adreport_payload")
  expect_equal(adreport_payload[["method"]], "fixed")
  expect_equal(
    ncol(adreport_payload[["jacobian"]]),
    length(result[["sdr"]][["par.fixed"]])
  )
  expect_false(is.null(backend_report_std))

  gradient <- as.numeric(result[["obj"]][["gr"]](result[["opt"]][["par"]]))
  estimates <- FIMS:::reshape_tmb_estimates(
    obj = result[["obj"]],
    sdreport = result[["sdr"]],
    opt = result[["opt"]],
    parameter_names = parameter_names,
    precomputed_gradient = gradient
  )
  requested_estimates <- estimates |>
    dplyr::filter(.data$label == "requested_spawning_biomass")
  requested_backend <- utils::tail(
    backend_report_std,
    om_input_list[[1]][["nyr"]] + 1
  )

  expect_equal(nrow(requested_estimates), om_input_list[[1]][["nyr"]] + 1)
  expect_true(all(is.finite(requested_estimates[["uncertainty"]])))
  expect_equal(
    unname(requested_estimates[["uncertainty"]]),
    unname(requested_backend[, "Std. Error"]),
    tolerance = 1e-8
  )
})

test_that("CatchAtAge random-effect derived quantity reports get backend uncertainty", {
  #' @description Test that requested random-effect derived quantity uncertainty is calculated through the FIMS backend.
  result <- setup_and_run_FIMS_without_wrappers(
    iter_id = 1,
    om_input_list = om_input_list,
    om_output_list = om_output_list,
    em_input_list = em_input_list,
    estimation_mode = TRUE,
    random_effects = c(recruitment = "log_devs"),
    derived_quantity_report_requests = list(
      list(
        component_type = "population",
        quantity_name = "spawning_biomass",
        report_se = TRUE,
        report_value = TRUE,
        report_name = "requested_spawning_biomass_random"
      )
    )
  )

  backend_report_std <- attr(result[["sdr"]], "fims_backend_report")
  adreport_payload <- attr(result[["sdr"]], "fims_adreport_payload")
  expect_equal(adreport_payload[["method"]], "laplace")
  expect_equal(
    ncol(adreport_payload[["random_jacobian"]]),
    length(result[["obj"]][["env"]][["random"]])
  )
  expect_equal(
    nrow(adreport_payload[["random_hessian"]]),
    length(result[["obj"]][["env"]][["random"]])
  )
  expect_false(is.null(backend_report_std))

  requested_backend <- utils::tail(
    backend_report_std,
    om_input_list[[1]][["nyr"]] + 1
  )
  requested_tmb <- utils::tail(
    result[["sdr_report"]],
    om_input_list[[1]][["nyr"]] + 1
  )

  expect_equal(
    rownames(requested_backend),
    rep("requested_spawning_biomass_random", om_input_list[[1]][["nyr"]] + 1)
  )
  expect_true(all(is.finite(requested_backend[, "Std. Error"])))
  expect_equal(
    unname(requested_backend[, "Estimate"]),
    unname(requested_tmb[, "Estimate"]),
    tolerance = 1e-8
  )
  expect_equal(
    unname(requested_backend[, "Std. Error"]),
    unname(requested_tmb[, "Std. Error"]),
    tolerance = 1e-8
  )
})
