# Instructions ----
#' This file follows the format generated by FIMS:::use_testthat_template().
#' Necessary tests include input and output (IO) correctness [IO
#' correctness], edge-case handling [Edge handling], and built-in errors and
#' warnings [Error handling]. See `?FIMS:::use_testthat_template` for more
#' information. Every test should have a @description tag, which can only span
#' one lines, that will be used in the bookdown report of the results from
#' {testthat}. This line can be more than 80 characters.

# get_number_of_parameters ----
## Setup ----
fit_with_optimization_big <- FIMS::fit_with_optimization_big
fit_without_optimization_big <- FIMS:::fit_without_optimization_big
## IO correctness ----
test_that("`get_number_of_parameters()` works with correct inputs", {
  for (fit in list(fit_with_optimization_big, fit_without_optimization_big)) {
    number_of_parameters <- get_number_of_parameters(fit)
    #' @description Test that `get_number_of_parameters()` returns the FIMSFit slot.
    expect_equal(number_of_parameters, fit@number_of_parameters)
    expected <- c(
      fixed_effects = length(fit@obj[["par"]]),
      random_effects = length(fit@obj[["env"]]$parList()[["re"]])
    )
    #' @description Test that `get_number_of_parameters()` counts fixed and random effects.
    expect_equal(number_of_parameters, expected)
  }
})

## Edge handling ----
test_that("`get_number_of_parameters()` returns correct outputs for edge cases", {
  #' @description Test that `get_number_of_parameters()` returns an error when given invalid input.
  expect_error(
    object = get_number_of_parameters("invalid_input")
  )
})

## Error handling ----
# No built-in errors to test.
