write("test-fimsfit.R", file = "debug_log.txt", append = TRUE)

# Instructions ----
#' This file follows the format generated by FIMS:::use_testthat_template().
#' Necessary tests include input and output (IO) correctness [IO
#' correctness], edge-case handling [Edge handling], and built-in errors and
#' warnings [Error handling]. See `?FIMS:::use_testthat_template` for more
#' information. Every test should have a @description tag, which can span
#' multiple lines, that will be used in the bookdown report of the results from
#' {testthat}.

# FIMSFit ----
## Setup ----
# Load the test data from an RDS file containing the fitted model estimates
if (!file.exists(test_path("fixtures", "fit_age_length_comp.RDS"))) {
  prepare_test_data()
}

fit_age_length_comp <- readRDS(test_path("fixtures", "fit_age_length_comp.RDS"))
fit_agecomp <- readRDS(test_path("fixtures", "fit_agecomp.RDS"))
fit_list <- list(fit_age_length_comp, fit_agecomp)
on.exit(rm(fit_list), add = TRUE)

## IO correctness ----
test_that("is.FIMSFit() works with correct inputs", {
  #' @description Test that is.FIMSFit(fit_age_length_comp) returns TRUE.
  expect_true(
    object = is.FIMSFit(fit_age_length_comp)
  )

  #' @description Test that as.list(fit_age_length_comp) returns a nested list.
  expect_equal(
    object = typeof(as.list(fit_age_length_comp)),
    expected = "list"
  )

  #' @description Test that as.list(fit_age_length_comp) contains correct components.
  expected_names <- c(
    "input", "obj", "opt", "max_gradient", "report", "sdreport", "estimates",
    "fits", "number_of_parameters", "timing", "version"
  )
  expect_equal(
    object = names(as.list(fit_age_length_comp)),
    expected = expected_names
  )
})

## Edge handling ----
test_that("is.FIMSFit() returns correct outputs for edge cases", {
  #' @description Test that is.FIMSFit("not_a_FIMSFit") returns FALSE.
  expect_false(is.FIMSFit("not_a_FIMSFit"))

  #' @description Test that print(FIMSFit) returns no error when the total time
  #' is more than a day.
  # Modify the total time to be more than a day
  fit_age_length_comp@timing[["time_total"]] <- 86401 # 60*60*24+1
  expect_no_error(print(fit_age_length_comp))

  #' @description Test that print(FIMSFit) returns no error when the total time
  #' is more than an hour.
  # Modify the total time to be more than a hour
  fit_age_length_comp@timing[["time_total"]] <- 3601 # 60*60+1
  expect_no_error(print(fit_age_length_comp))

  #' @description Test that print(FIMSFit) returns no error when the total time
  #' is more than a minute.
  # Modify the total time to be more than a minute
  fit_age_length_comp@timing[["time_total"]] <- 61 # 60+1
  expect_no_error(print(fit_age_length_comp))
})

## Error handling ----
# No built-in errors to test.
