# Instructions ----
#' This file follows the format generated by FIMS:::use_testthat_template().
#' Necessary tests include input and output (IO) correctness [IO
#' correctness], edge-case handling [Edge handling], and built-in errors and
#' warnings [Error handling]. See `?FIMS:::use_testthat_template` for more
#' information. Every test should have a @description tag, which can span
#' multiple lines, that will be used in the bookdown report of the results from
#' {testthat}.

# Deterministic test ----
## Setup ----
# Load necessary data for the integration test
if (!file.exists(test_path("fixtures", "fit_age_length_comp.RDS"))) {
  prepare_test_data()
}

load(test_path("fixtures", "integration_test_data.RData"))

# Set the iteration ID to 1 for accessing specific input/output list
iter_id <- 1

## IO correctness ----
test_that("catch-at-age model (deterministic MLE with wrappers) works with correct inputs", {
  # Load the test data from an RDS file containing the model fit
  deterministic_age_length_comp <- readRDS(test_path("fixtures", "deterministic_age_length_comp.RDS"))

  #' @description Test that the output from FIMS deterministic run matches the model comparison project OM values.
  verify_fims_deterministic(
    report = get_report(deterministic_age_length_comp),
    estimates = get_estimates(deterministic_age_length_comp),
    om_input = om_input_list[[iter_id]],
    om_output = om_output_list[[iter_id]],
    em_input = em_input_list[[iter_id]],
    use_fimsfit = TRUE
  )
})

test_that("catch-at-age model (deterministic MLE with wrappers) returns correct NLLs", {
  # Load the test data from an RDS file containing the model fit
  deterministic_age_length_comp <- readRDS(test_path("fixtures", "deterministic_age_length_comp.RDS"))

  #' @description Test that the NLLs from FIMS match the "true" NLLs from the model comparison project.
  verify_fims_nll(
    report = get_report(deterministic_age_length_comp),
    om_input = om_input_list[[iter_id]],
    om_output = om_output_list[[iter_id]],
    em_input = em_input_list[[iter_id]]
  )

  test_that("catch-at-age model (deterministic MLE with wrappers) returns correct number of parameters and random effects", {
    #' @description Test that the number of fixed parameters are correct.
    expect_equal(get_number_of_parameters(deterministic_age_length_comp)["fixed_effects"] |> unname(), 77)
    #' @description Test that the number of random effects are correct.
    expect_equal(get_number_of_parameters(deterministic_age_length_comp)["random_effects"] |> unname(), 0)
  })
})

## Edge handling ----
# No edge cases to test

## Error handling ----
# No built-in errors to test

# Estimation test ----
## Setup ----

## IO correctness ----
test_that("catch-at-age model (estimation MLE with wrappers) works with age and length comp", {
  # Load the test data from an RDS file containing the model fit
  fit_age_length_comp <- readRDS(test_path("fixtures", "fit_age_length_comp.RDS"))

  #' @description Test that the output from FIMS matches the model comparison project OM values.
  validate_fims(
    report = get_report(fit_age_length_comp),
    estimates = get_estimates(fit_age_length_comp),
    om_input = om_input_list[[iter_id]],
    om_output = om_output_list[[iter_id]],
    em_input = em_input_list[[iter_id]],
    use_fimsfit = TRUE
  )
})

## Edge handling ----
test_that("catch-at-age model (estimation MLE with wrappers) works with age comp only using wrappers", {
  # Load the test data from an RDS file containing the model fit
  fit_agecomp <- readRDS(test_path("fixtures", "fit_agecomp.RDS"))

  #' @description Test that the output from FIMS matches the model comparison project OM values.
  validate_fims(
    report = get_report(fit_agecomp),
    estimates = get_estimates(fit_agecomp),
    om_input = om_input_list[[iter_id]],
    om_output = om_output_list[[iter_id]],
    em_input = em_input_list[[iter_id]],
    use_fimsfit = TRUE
  )

  # Load the test data from an RDS file containing the model fit
  fit_agecomp_na <- readRDS(test_path("fixtures", "fit_agecomp_na.RDS"))

  #' @description Test that the output from FIMS matches the model comparison project OM values when there are NAs.
  validate_fims(
    report = get_report(fit_agecomp_na),
    estimates = get_estimates(fit_agecomp_na),
    om_input = om_input_list[[iter_id]],
    om_output = om_output_list[[iter_id]],
    em_input = em_input_list[[iter_id]],
    use_fimsfit = TRUE
  )
})

test_that("catch-at-age model (estimation MLE with wrappers) works with length comp only using wrappers", {
  # Load the test data from an RDS file containing the model fit
  fit_lengthcomp <- readRDS(test_path("fixtures", "fit_lengthcomp.RDS"))

  #' @description Test that the output from FIMS matches the model comparison project OM values.
  validate_fims(
    report = get_report(fit_lengthcomp),
    estimates = get_estimates(fit_lengthcomp),
    om_input = om_input_list[[iter_id]],
    om_output = om_output_list[[iter_id]],
    em_input = em_input_list[[iter_id]],
    use_fimsfit = TRUE
  )

  # Load the test data from an RDS file containing the model fit
  fit_lengthcomp_na <- readRDS(test_path("fixtures", "fit_lengthcomp_na.RDS"))

  #' @description Test that the output from FIMS matches the model comparison project OM values when there are NAs.
  validate_fims(
    report = get_report(fit_lengthcomp_na),
    estimates = get_estimates(fit_lengthcomp_na),
    om_input = om_input_list[[iter_id]],
    om_output = om_output_list[[iter_id]],
    em_input = em_input_list[[iter_id]],
    use_fimsfit = TRUE
  )
})

test_that("catch-at-age model (estimation MLE with wrappers) works with age and length comp with NAs", {
  # Load the test data from an RDS file containing the model fit
  fit_age_length_comp_na <- readRDS(test_path("fixtures", "fit_age_length_comp_na.RDS"))

  #' @description Test that the output from FIMS matches the model comparison project OM values when there are NAs.
  validate_fims(
    report = get_report(fit_age_length_comp_na),
    estimates = get_estimates(fit_age_length_comp_na),
    om_input = om_input_list[[iter_id]],
    om_output = om_output_list[[iter_id]],
    em_input = em_input_list[[iter_id]],
    use_fimsfit = TRUE
  )
})

## Error handling ----
test_that("catch-at-age model (estimation MLE with wrappers) returns an error when there are no estimated parameters for optimization", {
  # Load data
  data_age_length_comp <- FIMSFrame(data1)
  # Load pre-configured parameters
  parameters <- readRDS(
    test_path("fixtures", "parameters_model_comparison_project.RDS")
  )
  # Set all non-NA estimation types to "constant" and initialize the model
  initialized_model <- parameters |>
    dplyr::mutate(
      estimation_type = dplyr::if_else(
        !is.na(estimation_type),
        "constant",
        estimation_type
      )
    ) |>
    initialize_fims(
      data = data_age_length_comp
    )
  # Fit model without optimization and get output from a deterministic run
  deterministic_output <- initialized_model |>
    fit_fims(optimize = FALSE) |>
    get_estimates() |>
    dplyr::filter(!is.na(input))

  #' @description Test that estimate column should match input column when not optimized.
  expect_equal(
    deterministic_output[["estimated"]],
    deterministic_output[["input"]]
  )

  #' @description Test that no warnings are produced when optimize = FALSE.
  expect_no_warning(
    initialized_model |>
      fit_fims(optimize = FALSE)
  )
  clear()

  #' @description Test that FIMS returns an error when there are no estimated parameters for optimization.
  expect_error(
    object = initialized_model |>
      fit_fims(optimize = TRUE),
    regexp = "FIMS must have at least one parameter to optimize."
  )
  clear()
})
