# Instructions ----
#' This file follows the format generated by FIMS:::use_testthat_template().
#' Necessary tests include input and output (IO) correctness [IO
#' correctness], edge-case handling [Edge handling], and built-in errors and
#' warnings [Error handling]. See `?FIMS:::use_testthat_template` for more
#' information. Every test should have a @description tag, which can only span
#' one lines, that will be used in the bookdown report of the results from
#' {testthat}. This line can be more than 80 characters.

# rcpp fleet ----
## Setup ----

# Load or prepare any necessary data for testing
## IO correctness ----
test_that("rcpp fleet works with correct inputs", {
  # Create selectivity for fleet 1
  selectivity_fleet1 <- create_selectivity("logistic")
  #' @description Test that one selectivity module can be set up without any errors and it has the appropriate id.
  expect_equal(get_module_id(selectivity_fleet1), 1)

  # Create selectivity for fleet 2
  selectivity_fleet2 <- create_selectivity("logistic")
  #' @description Test that two selectivity modules can be set up without any errors and they have the appropriate ids.
  expect_equal(get_module_id(selectivity_fleet2), 2)

  # Add selectivity to fleet
  fleet1 <- create_fleet()
  fleet2 <- create_fleet()
  #' @description Test that rcpp fleet interface works with the first `LogisticSelectivity` module and no output, errors, messages, or warnings are produced when setting the SelectivityIDs for the fleets.
  expect_silent(fleet1$SetSelectivityIDget_module_id(selectivity_fleet1))
  #' @description Test that rcpp fleet interface works with the second `LogisticSelectivity` module and no output, errors, messages, or warnings are produced when setting the SelectivityIDs for the fleets.
  expect_silent(fleet2$SetSelectivityIDget_module_id(selectivity_fleet2))

  #' @description Test that setting the age-composition ID works within the fleet module.
  expect_silent(fleet1$SetObservedAgeCompDataID(1))
  #' @description Test that getting the age-composition ID works within the fleet module.
  expect_equal(fleet1$GetObservedAgeCompDataID(), 1)

  #' @description Test that setting and getting the fleet name continue to work when the scalar field is stored directly.
  expect_silent(fleet1$SetName("fleet one"))
  expect_equal(fleet1$GetName(), "fleet one")

  #' @description Test that observed units can be assigned directly through the Rcpp field bindings.
  fleet1$observed_catch_units <- "numbers"
  fleet1$observed_index_units <- "numbers"
  expect_equal(fleet1$observed_catch_units, "numbers")
  expect_equal(fleet1$observed_index_units, "numbers")

  #' @description Test that setting the index ID works within the fleet module.
  expect_silent(fleet1$SetObservedIndexDataID(1))
  #' @description Test that getting the index ID works within the fleet module.
  expect_equal(fleet1$GetObservedIndexDataID(), 1)

  clear()
})


## Error handling ----
test_that("rcpp fleet returns correct error messages", {
  fleet1 <- create_fleet()
  #' @description Test that the rcpp fleet interface returns an error when given a string as a selectivity ID rather than an integer.
  expect_error(fleet1$SetSelectivityID("id"))
  #' @description Test that the rcpp fleet interface returns an error when given a string as an age-composition ID rather than an integer.
  expect_error(fleet1$SetObservedAgeCompDataID("id"))
  #' @description Test that the rcpp fleet interface returns an error when given a string as an length-composition ID rather than an integer.
  expect_error(fleet1$SetObservedLengthCompDataID("id"))
  #' @description Test that the rcpp fleet interface returns an error when given a string as an index ID rather than an integer.
  expect_error(fleet1$SetObservedIndexDataID("id"))
  clear()
})
