# Instructions ----
#' This file follows the format generated by FIMS:::use_testthat_template().
#' Necessary tests include input and output (IO) correctness [IO
#' correctness], edge-case handling [Edge handling], and built-in errors and
#' warnings [Error handling]. See `?FIMS:::use_testthat_template` for more
#' information. Every test should have a @description tag, which can only span
#' one lines, that will be used in the bookdown report of the results from
#' {testthat}. This line can be more than 80 characters.

# get_max_gradient ----
## Setup ----
fit_with_optimization_big <- FIMS::fit_with_optimization_big
fit_without_optimization_big <- FIMS:::fit_without_optimization_big
## IO correctness ----
test_that("`get_max_gradient()` works with correct inputs", {
  optimized_gradient <- get_max_gradient(fit_with_optimization_big)
  #' @description Test that `get_max_gradient()` returns the optimized fit slot.
  expect_equal(optimized_gradient, fit_with_optimization_big@max_gradient)
  #' @description Test that `get_max_gradient()` returns a numeric value.
  expect_type(optimized_gradient, "double")

  deterministic_gradient <- get_max_gradient(fit_without_optimization_big)
  #' @description Test that the deterministic fit has no optimized gradient.
  expect_equal(deterministic_gradient, fit_without_optimization_big@max_gradient)
  expect_true(is.na(deterministic_gradient))
})

## Edge handling ----
test_that("`get_max_gradient()` returns correct outputs for edge cases", {
  #' @description Test that `get_max_gradient()` returns an error when given invalid input.
  expect_error(
    object = get_max_gradient("invalid_input")
  )
})

## Error handling ----
# No built-in errors to test.
