test_that("native logging records and filters messages", {
  clear()
  on.exit(clear())
  log_info("native info marker")
  log_warning("native warning marker")
  log_error("native error marker")
  expect_true(jsonlite::validate(get_log()))
  expect_match(get_log_info(), "native info marker")
  expect_false(grepl("native warning marker", get_log_info()))
  expect_match(get_log_warnings(), "native warning marker")
  expect_match(get_log_errors(), "native error marker")
  clear()
  expect_false(grepl("native info marker", get_log()))
})

test_that("native logging validates controls and translates exceptions", {
  old_path <- get_log_path()
  on.exit({
    set_log_path(old_path)
    set_log_throw_on_error(FALSE)
    clear()
  })
  set_log_path("native-test.json")
  expect_identical(get_log_path(), "native-test.json")
  expect_error(write_log(NA), "single non-missing logical")
  expect_error(log_info(NA_character_), "single non-missing string")
  set_log_throw_on_error(TRUE)
  expect_error(log_error("native thrown marker"), "native thrown marker")
  expect_match(get_log_errors(), "native thrown marker")
  set_log_throw_on_error(FALSE)
  expect_no_error(log_error("native nonthrowing marker"))
})
