# Instructions ----
#' This file follows the format generated by FIMS:::use_testthat_template().
#' Necessary tests include input and output (IO) correctness [IO
#' correctness], edge-case handling [Edge handling], and built-in errors and
#' warnings [Error handling]. See `?FIMS:::use_testthat_template` for more
#' information. Every test should have a @description tag, which can only span
#' one lines, that will be used in the bookdown report of the results from
#' {testthat}. This line can be more than 80 characters.

# check_sdreport_convergence ----
## Setup ----
make_mock_obj <- function(
  random = numeric(),
  hessian = diag(3),
  hessian_error = FALSE
) {
  list(
    env = list(
      random = random,
      spHess = function(random = TRUE) {
        if (hessian_error) {
          stop("Failed to compute sparse Hessian")
        }
        hessian
      }
    ),
    he = function(par) {
      if (hessian_error) {
        stop("Failed to compute dense Hessian")
      }
      hessian
    }
  )
}

make_mock_sdreport <- function(
  pdHess = TRUE,
  fixed_se = c(0.1, 0.2),
  random_se = c(0.3, 0.4),
  report_se = c(0.5, 0.6),
  fail_on = character()
) {
  structure(
    list(
      pdHess = pdHess,
      fixed_se = fixed_se,
      random_se = random_se,
      report_se = report_se,
      fail_on = fail_on
    ),
    class = "mock_sdreport"
  )
}

summary.mock_sdreport <- function(object, ...) {
  dots <- list(...)
  type <- if (length(dots) > 0) dots[[1]] else NULL
  if (is.null(type)) {
    type <- "all"
  }
  if (type %in% object[["fail_on"]]) {
    stop("Forced summary failure")
  }

  to_summary_mat <- function(se, prefix = "par") {
    if (is.null(se) || length(se) == 0) {
      return(NULL)
    }
    out <- matrix(se, ncol = 1)
    colnames(out) <- "Std. Error"
    rownames(out) <- paste0(prefix, seq_along(se))
    out
  }

  if (identical(type, "fixed")) {
    return(to_summary_mat(object[["fixed_se"]], prefix = "fixed_"))
  }
  if (identical(type, "random")) {
    return(to_summary_mat(object[["random_se"]], prefix = "random_"))
  }
  if (identical(type, "report")) {
    return(to_summary_mat(object[["report_se"]], prefix = "report_"))
  }
  if (identical(type, "all")) {
    all_se <- c(
      object[["fixed_se"]],
      object[["random_se"]],
      object[["report_se"]]
    )
    return(to_summary_mat(all_se, prefix = "all_"))
  }

  stop("Unknown summary type")
}

register_mock_sdreport_summary <- function() {
  registerS3method("summary", "mock_sdreport", summary.mock_sdreport)
}

## IO correctness ----
test_that("check_sdreport_convergence() works with correct inputs", {
  #' @description Test that `check_sdreport_convergence()` has no warnings with clean inputs and stable Hessian.
  obj <- make_mock_obj(random = numeric(), hessian = diag(3))
  opt <- list(par = c(0, 0, 0))
  sdreport <- make_mock_sdreport(
    pdHess = TRUE,
    fixed_se = c(0.1, 0.2),
    random_se = numeric(),
    report_se = c(0.3, 0.4)
  )
  register_mock_sdreport_summary()

  expect_no_warning(
    out <- FIMS:::check_sdreport_convergence(list(), obj, opt, sdreport)
  )
  expect_null(out)

  #' @description Test early return path when pdHess is FALSE.
  obj <- make_mock_obj()
  opt <- list(par = numeric())
  sdreport <- make_mock_sdreport(pdHess = FALSE)
  out <- NULL

  testthat::with_mocked_bindings(
    FIMSFit = function(input, obj, opt, sdreport, timing) {
      list(
        tag = "mock_fit",
        input = input,
        obj = obj,
        opt = opt,
        sdreport = sdreport,
        timing = timing
      )
    },
    print = function(x, ...) invisible(x),
    {
      expect_warning(
        object = out <- FIMS:::check_sdreport_convergence(
          list(dummy = TRUE),
          obj,
          opt,
          sdreport
        ),
        regexp = "Standard error calculations failed convergence checks"
      )
    },
    .package = "FIMS"
  )

  expect_equal(object = out$tag, expected = "mock_fit")
  expect_identical(object = out$sdreport, expected = sdreport)
})

## Edge handling ----
test_that("check_sdreport_convergence() returns correct outputs for edge cases", {
  #' @description Test that `check_sdreport_convergence()` gracefully handles when summary extraction throws an error.
  obj <- make_mock_obj(random = 1)
  opt <- list(par = numeric())
  sdreport <- make_mock_sdreport(
    pdHess = TRUE,
    fail_on = "fixed"
  )
  register_mock_sdreport_summary()

  expect_warning(
    object = FIMS:::check_sdreport_convergence(list(), obj, opt, sdreport),
    regexp = "Unable to extract summary from sdreport"
  )
})

## Error handling ----
test_that("check_sdreport_convergence() returns correct error messages", {
  #' @description Test that `check_sdreport_convergence()` has graceful handling when Hessian extraction throws an error.
  obj <- make_mock_obj(random = 1, hessian_error = TRUE)
  opt <- list(par = numeric())
  sdreport <- make_mock_sdreport(pdHess = TRUE)
  register_mock_sdreport_summary()

  expect_warning(
    object = FIMS:::check_sdreport_convergence(list(), obj, opt, sdreport),
    regexp = "Unable to extract Hessian for condition number check"
  )

  #' @description Test that `check_sdreport_convergence()` warns when there are NA standard errors in fixed, random, and derived summaries.
  obj <- make_mock_obj(random = 1)
  opt <- list(par = numeric())
  sdreport <- make_mock_sdreport(
    pdHess = TRUE,
    fixed_se = c(0.2, NA_real_),
    random_se = c(NA_real_, 0.3),
    report_se = c(0.4, NA_real_)
  )
  register_mock_sdreport_summary()

  expect_warning(
    object = FIMS:::check_sdreport_convergence(list(), obj, opt, sdreport),
    regexp = "sdreport convergence issues detected"
  )

  #' @description Test that `check_sdreport_convergence()` warns when high condition number warning for near-singular Hessian is present.
  obj <- make_mock_obj(random = numeric(), hessian = diag(c(1, 1e-8, 1e-8)))
  opt <- list(par = c(0, 0, 0))
  sdreport <- make_mock_sdreport(
    pdHess = TRUE,
    fixed_se = c(10, 9),
    random_se = numeric(),
    report_se = c(8, 7)
  )
  register_mock_sdreport_summary()

  expect_warning(
    object = FIMS:::check_sdreport_convergence(list(), obj, opt, sdreport),
    regexp = "Large condition number detected in Hessian"
  )
})
