# Instructions ----
#' This file follows the format generated by FIMS:::use_testthat_template().

test_that("`year_index_to_timing()` maps annual indices to calendar years", {
  #' @description Test that ordinary annual indices map to modeled calendar years.
  expect_equal(
    year_index_to_timing(1:3, 2001:2003),
    2001:2003
  )

  #' @description Test that a terminal-state index maps to the following calendar year.
  expect_equal(
    year_index_to_timing(1:4, 2001:2003),
    2001:2004
  )

  #' @description Test that legacy JSON without modeled years retains numeric indices as timing.
  expect_equal(
    year_index_to_timing(c(1, 2, NA), numeric()),
    c(1, 2, NA)
  )
})
