# Instructions ----
#' This file follows the format generated by FIMS:::use_testthat_template().
#' Necessary tests include input and output (IO) correctness [IO
#' correctness], edge-case handling [Edge handling], and built-in errors and
#' warnings [Error handling]. See `?FIMS:::use_testthat_template` for more
#' information. Every test should have a @description tag, which can only span
#' one lines, that will be used in the bookdown report of the results from
#' {testthat}. This line can be more than 80 characters.

# get_timing ----
## Setup ----
# Load or prepare any necessary data for testing
fit_with_optimization_big <- FIMS::fit_with_optimization_big
fit_without_optimization_big <- FIMS::fit_without_optimization_big

## IO correctness ----
test_that("`get_timing()` works with correct inputs", {
  expected_names <- c(
    "time_optimization", "time_sdreport", "time_total"
  )
  timing_with_optimization <- get_timing(fit_with_optimization_big)
  #' @description Test that `get_timing()` returns correct output for the `timing` slot.
  expect_equal(
    object = timing_with_optimization,
    expected = fit_with_optimization_big@timing
  )
  #' @description Test that `get_timing()` returns correct names for the `timing` slot.
  expect_equal(
    object = names(timing_with_optimization),
    expected = expected_names
  )
  #' @description Test that `get_timing()` returns > 0 values for the `timing` slot.
  expect_true(object = all(timing_with_optimization > 0))
})

test_that("`get_timing()` works with correct inputs without optimization", {
  timing_without_optimization <- get_timing(fit_without_optimization_big)
  #' @description Test that `get_timing()` returns correct output for the `timing` slot.
  expect_equal(
    object = timing_without_optimization,
    expected = fit_without_optimization_big@timing
  )
  #' @description Test that `get_timing()` returns correct names for the `timing` slot.
  expect_equal(
    object = names(timing_without_optimization),
    expected = "time_total"
  )
  #' @description Test that `get_timing()` returns 0 seconds for the `timing` slot when optimization is not performed.
  expect_true(object = all(timing_without_optimization == 0))
})

## Edge handling ----
test_that("`get_timing()` returns correct outputs for edge cases", {
  #' @description Test that `get_timing()` returns an error when given invalid input.
  expect_error(
    object = get_timing("invalid_input")
  )
})

## Error handling ----
# No built-in errors to test.
