# Instructions ----
#' This file follows the format generated by FIMS:::use_testthat_template().
#' Necessary tests include input and output (IO) correctness [IO
#' correctness], edge-case handling [Edge handling], and built-in errors and
#' warnings [Error handling]. See `?FIMS:::use_testthat_template` for more
#' information. Every test should have a @description tag, which can only span
#' one lines, that will be used in the bookdown report of the results from
#' {testthat}. This line can be more than 80 characters.

# setup_default_data_composition ----
## Setup ----
data <- FIMS::FIMSFrame(data_big)
source_row <- get_data(data) |>
  dplyr::filter(.data[["type"]] %in% c("age_comp", "length_comp")) |>
  dplyr::slice(1)
fleet <- source_row[["name"]]
module_type <- FIMS:::snake_to_pascal(source_row[["type"]])

## IO correctness ----
test_that("`setup_default_data_composition()` works with correct inputs", {
  result <- setup_default_data_composition(
    data = data,
    fleet = fleet,
    module_type = module_type
  )

  #' @description Test that output is a one-row `tbl_df` for the requested composition module.
  expect_s3_class(result, "tbl_df")
  expect_equal(nrow(result), 1)
  expect_equal(unique(result[["module_name"]]), "Data")

  #' @description Test that output keeps the requested fleet and module type.
  expect_equal(unique(result[["fleet"]]), fleet)
  expect_equal(unique(result[["module_type"]]), module_type)

  clear()
})

## Edge handling ----
test_that("`setup_default_data_composition()` works with edge cases", {
  result <- setup_default_data_composition(
    data = data,
    fleet = fleet,
    module_type = module_type,
    distribution = "Ddirichlet"
  )

  #' @description Test that distribution argument is reflected in output.
  expect_equal(unique(result[["distribution"]]), "Ddirichlet")

  clear()
})

## Error handling ----
test_that("`setup_default_data_composition()` returns correct error messages", {
  #' @description Test that invalid fleet length returns expected error.
  expect_error(
    object = setup_default_data_composition(data = data, fleet = c("a", "b"), module_type = module_type),
    regexp = "fleet"
  )

  #' @description Test that unavailable module type for a fleet returns expected error.
  expect_error(
    object = setup_default_data_composition(data = data, fleet = fleet, module_type = "Index"),
    regexp = "must be one of"
  )

  clear()
})
