# Instructions ----
#' This file follows the format generated by FIMS:::use_testthat_template().
#' Necessary tests include input and output (IO) correctness [IO
#' correctness], edge-case handling [Edge handling], and built-in errors and
#' warnings [Error handling]. See `?FIMS:::use_testthat_template` for more
#' information. Every test should have a @description tag, which can only span
#' one lines, that will be used in the bookdown report of the results from
#' {testthat}. This line can be more than 80 characters.

# get_model_output ----
## Setup ----
# Load or prepare any necessary data for testing
fit_with_optimization_big <- FIMS::fit_with_optimization_big
fit_without_optimization_big <- FIMS::fit_without_optimization_big

## IO correctness ----
test_that("`get_model_output()` works with correct inputs", {
  expected_names <- c(
    "name", "type", "estimation_framework", "id", "objective_function_value",
    "growth", "recruitment", "maturity",
    "selectivity", "population_ids", "fleet_ids", "populations", "fleets",
    "density_components", "data"
  )

  model_output_with_optimization <- get_model_output(fit_with_optimization_big)
  json_list_with_optimization <- jsonlite::fromJSON(model_output_with_optimization, simplifyVector = FALSE)
  #' @description Test that `get_model_output(fit_with_optimization_big)` returns correct names for the `model_output` slot.
  expect_equal(
    object = names(json_list_with_optimization),
    expected = expected_names
  )

  model_output_without_optimization <- get_model_output(fit_without_optimization_big)
  json_list_without_optimization <- jsonlite::fromJSON(model_output_without_optimization, simplifyVector = FALSE)
  #' @description Test that `get_model_output(fit_without_optimization_big)` returns correct names for the `model_output` slot.
  expect_equal(
    object = names(json_list_without_optimization),
    expected = expected_names
  )
})

## Edge handling ----
# No edge handling tests for this function.

## Error handling ----
# No built-in errors to test.
