# Instructions ----
#' This file follows the format generated by FIMS:::use_testthat_template().
#' Necessary tests include input and output (IO) correctness [IO
#' correctness], edge-case handling [Edge handling], and built-in errors and
#' warnings [Error handling]. See `?FIMS:::use_testthat_template` for more
#' information. Every test should have a @description tag, which can only span
#' one lines, that will be used in the bookdown report of the results from
#' {testthat}. This line can be more than 80 characters.


# model rebuild ----
## Setup ----
# CreateTMBModel() clears the two C++ Information singletons and repopulates
# them from the R registry, which it does not clear. A module therefore survives
# a rebuild, so a second scenario can change one value on one module instead of
# rebuilding every module from the parameters tibble. This is the power-user
# path; initialize_fims() calls clear() first and so cannot be used this way.
load(test_path("fixtures", "integration_test_data.RData"))

# Pull one module back out of the registry by name.
registry_module <- function(module_name) {
  modules <- FIMS:::.fims_registry[["objects"]]
  names_held <- vapply(modules, function(x) x[["module_name"]], character(1))
  modules[[which(names_held == module_name)[1]]]
}

## IO correctness ----
test_that("a module survives a rebuild and its new value reaches the model", {
  clear()
  data_frame <- FIMSFrame(data_big)
  input <- setup_default_parameters(data = data_frame) |>
    initialize_fims(data = data_frame)

  recruitment <- registry_module("Recruitment")
  id_before <- get_module_id(recruitment)
  handle_before <- FIMS:::.fims_registry[["model_handle"]]
  module_count <- length(FIMS:::.fims_registry[["objects"]])
  log_rzero_before <- get_variable_vector(recruitment, "log_rzero")[["values"]]

  # Change one value in one module, leaving every other module untouched.
  set_variable_vector(
    recruitment, "log_rzero", log_rzero_before + 0.5, "fixed_effects"
  )
  handle_after <- CreateTMBModel()

  #' @description Test that a module keeps its id across a rebuild, so links to it stay valid.
  expect_equal(get_module_id(recruitment), id_before)

  #' @description Test that a module is still usable after a rebuild.
  expect_equal(
    get_variable_vector(recruitment, "log_rzero")[["values"]],
    log_rzero_before + 0.5
  )

  #' @description Test that `CreateTMBModel()` does not clear the R registry, so the other modules survive too.
  expect_length(FIMS:::.fims_registry[["objects"]], module_count)

  #' @description Test that a second `CreateTMBModel()` call reports a different build than the first.
  expect_gt(handle_after, handle_before)

  #' @description Test that the changed value reaches the rebuilt model's fixed-effect vector.
  expect_true(any(abs(get_fixed() - (log_rzero_before + 0.5)) < 1e-8))

  #' @description Test that the parameter vector captured by the first build is stale after a rebuild.
  # The practical consequence: a second fit has to read get_fixed() again
  # rather than reuse the list initialize_fims() returned.
  expect_false(isTRUE(all.equal(input[["parameters"]][["p"]], get_fixed())))

  clear()
})

test_that("a rebuild leaves untouched modules as they were", {
  clear()
  data_frame <- FIMSFrame(data_big)
  setup_default_parameters(data = data_frame) |>
    initialize_fims(data = data_frame)

  recruitment <- registry_module("Recruitment")
  fleet <- registry_module("Fleet")
  fleet_log_q_before <- get_variable_vector(fleet, "log_q")[["values"]]

  log_rzero <- get_variable_vector(recruitment, "log_rzero")[["values"]]
  set_variable_vector(recruitment, "log_rzero", log_rzero + 0.5, "fixed_effects")
  CreateTMBModel()

  #' @description Test that changing one module does not disturb the values held by another.
  expect_equal(
    get_variable_vector(fleet, "log_q")[["values"]],
    fleet_log_q_before
  )

  clear()
})

## Error handling ----
test_that("`CreateTMBModel()` refuses to build with nothing registered", {
  clear()

  #' @description Test that rebuilding after `clear()` is an error rather than building an empty model.
  expect_error(CreateTMBModel(), "No model components have been registered")
})
