# Instructions ----
#' This file follows the format generated by FIMS:::use_testthat_template().
#' Necessary tests include input and output (IO) correctness [IO
#' correctness], edge-case handling [Edge handling], and built-in errors and
#' warnings [Error handling]. See `?FIMS:::use_testthat_template` for more
#' information. Every test should have a @description tag, which can only span
#' one lines, that will be used in the bookdown report of the results from
#' {testthat}. This line can be more than 80 characters.

# setup_default_DoubleLogistic ----
## Setup ----
# No setup required.

## IO correctness ----
test_that("`setup_default_DoubleLogistic()` works with correct inputs", {
  result <- FIMS:::setup_default_DoubleLogistic()

  #' @description Test that output has the expected labels and default values.
  expect_s3_class(result, "tbl_df")
  expect_equal(
    result[["label"]],
    c("inflection_point_asc", "slope_asc", "inflection_point_desc", "slope_desc")
  )
  expect_equal(result[["value"]], c(2, 1, 4, 1))

  clear()
})

## Edge handling ----
# Please remove/comment out the test template below if no edge cases are being tested.
# No edge cases to test.

## Error handling ----
# Please remove/comment out the test template below if there are no built-in errors/warnings.
# No built-in errors to test.
