// Instructions ----
// This file follows the format generated by FIMS:::use_gtest_template().
// Necessary tests include input and output (IO) correctness [IO
// correctness], edge-case handling [Edge handling], and built-in errors and
// warnings [Error handling]. See `?FIMS:::use_gtest_template` for more
// information. Every test should have a description comment.
// More assertion macros provided by GoogleTest can be found at
// https://google.github.io/googletest/reference/assertions.html.

#include "gtest/gtest.h"
#include "population_dynamics/maturity/functors/logistic.hpp"

namespace {

// LogisticMaturity_evaluate
// IO correctness
TEST(LogisticMaturity_evaluate, HandlesCorrectInput) {
  fims_popdy::LogisticMaturity<double> maturity;
  maturity.inflection_point.resize(1);
  maturity.inflection_point[0] = 20.5;
  maturity.slope.resize(1);
  maturity.slope[0] = 0.15;
  double maturity_x = 40.5;
  // 1.0/(1.0+exp(-(40.5-20.5)*0.15)) = 0.9525741
  double expect_maturity = 0.9525741;
  EXPECT_NEAR(maturity.evaluate(maturity_x), expect_maturity, 0.0001);
}

TEST(LogisticMaturity_evaluate, ObservationAgeRetainsAnnualParameters) {
  fims_popdy::LogisticMaturity<double> maturity;
  maturity.inflection_point = {4, 6};
  maturity.slope = {1, 2};
  EXPECT_NEAR(maturity.EvaluateAtObservation(5, .5, 1), 1 / (1 + std::exp(1.0)),
              1e-12);
  EXPECT_EQ(maturity.EvaluateAtObservation(5, 0, 1), maturity.evaluate(5, 1));
}

}  // namespace
