// Instructions ----
// This file follows the format generated by FIMS:::use_gtest_template().
// Necessary tests include input and output (IO) correctness [IO
// correctness], edge-case handling [Edge handling], and built-in errors and
// warnings [Error handling]. See `?FIMS:::use_gtest_template` for more
// information. Every test should have a description comment.
// More assertion macros provided by GoogleTest can be found at 
// https://google.github.io/googletest/reference/assertions.html.

#include "gtest/gtest.h"
// Include the header file for the function being tested
// For example, if testing the `evaluate` member function of the 
// `LogisticSelectivity` class, include the corresponding header in the test 
// file `tests/gtest/test_population_dynamics_selectivity_logistic.cpp`:
// #include "population_dynamics/selectivity/functors/logistic.hpp"
#include "population_dynamics/selectivity/functors/double_logistic.hpp"
// Include additional headers as needed
// For example, include <iostream> to use `std::cerr` and `std::cout`:
// #include <iostream>

namespace
{
  // DoubleLogisticSelectivity_Evaluate 
  // IO correctness
  TEST(DoubleLogisticSelectivity_Evaluate, HandlesCorrectInput)
  {
    
    fims_popdy::DoubleLogisticSelectivity<double> fishery_selectivity;
    fishery_selectivity.inflection_point_asc.resize(1);
    fishery_selectivity.slope_asc.resize(1);
    fishery_selectivity.inflection_point_desc.resize(1);
    fishery_selectivity.slope_desc.resize(1);
    fishery_selectivity.inflection_point_asc[0] = 10.5;
    fishery_selectivity.slope_asc[0] = 0.2;
    fishery_selectivity.inflection_point_desc[0] = 15.0;
    fishery_selectivity.slope_desc[0] = 0.05;
    double fishery_x = 34.5;
    // 1.0/(1.0+exp(-(34.5-10.5)*0.2)) * (1.0 - 1.0/(1.0+exp(-(34.5-15.0)*0.05))) = 0.2716494
    double expect_fishery = 0.2716494;
    EXPECT_NEAR(fishery_selectivity.evaluate(fishery_x), expect_fishery, 0.0001);

  }

  // Edge handling
  // Test the use of get_force_scalar across multiple timesteps.
  TEST(DoubleLogisticSelectivity_Evaluate, HandlesThreeTimeSteps) {
    // Setup 
    // Load or prepare any necessary data for testing
    fims_popdy::DoubleLogisticSelectivity<double> fishery_selectivity;
    fishery_selectivity.inflection_point_asc.resize(1);
    fishery_selectivity.slope_asc.resize(3);
    fishery_selectivity.inflection_point_desc.resize(1);
    fishery_selectivity.slope_desc.resize(1);
    fishery_selectivity.inflection_point_asc[0] = 10.5;
    fishery_selectivity.slope_asc[0] = 0.2;
    fishery_selectivity.slope_asc[1] = 0.3;
    fishery_selectivity.slope_asc[2] = 0.4;
    fishery_selectivity.inflection_point_desc[0] = 15.0;
    fishery_selectivity.slope_desc[0] = 0.05;
    // Uses get_force_scalar internally to have the same inflection point for
    // all 3 values but only the first one is set
    double fishery_x = 34.5;
    // Expected values by position:
    // pos 0: 1.0/(1.0+exp(-(34.5-10.5)*0.2)) * (1.0 - 1.0/(1.0+exp(-(34.5-15.0)*0.05))) = 0.2716494
    // pos 1: 1.0/(1.0+exp(-(34.5-10.5)*0.3)) * (1.0 - 1.0/(1.0+exp(-(34.5-15.0)*0.05))) = 0.2736807
    // pos 2: 1.0/(1.0+exp(-(34.5-10.5)*0.4)) * (1.0 - 1.0/(1.0+exp(-(34.5-15.0)*0.05))) = 0.2738665
    double expected_fishery[3] = {0.2716494, 0.2736807, 0.2738665};
    
    // Test that evaluate(x, pos) returns the expected value at each timestep.
    for (size_t pos = 0; pos < 3; ++pos) {
      EXPECT_NEAR(fishery_selectivity.evaluate(fishery_x, pos),
                  expected_fishery[pos], 0.0001);
    }
  
  }

  // Error handling
  // No built-in errors/warnings.
}