// Instructions ----
// This file follows the format generated by FIMS:::use_gtest_template().
// Necessary tests include input and output (IO) correctness [IO
// correctness], edge-case handling [Edge handling], and built-in errors and
// warnings [Error handling]. See `?FIMS:::use_gtest_template` for more
// information. Every test should have a description comment.
// More assertion macros provided by GoogleTest can be found at
// https://google.github.io/googletest/reference/assertions.html.

#include "gtest/gtest.h"
#include "population/population.hpp"
#include "../../tests/gtest/test_population_test_fixture.hpp"

namespace
{
    // CatchAtAge_CalculateMaturityAA
    // IO correctness
    TEST_F(CAAEvaluateTestFixture, HandlesHandlesCorrectInput_CatchAtAge_CalculateMaturityAACorrectInput)
    {        
        double inflection_point = 6;
        double slope = 0.15;
        std::vector<double> expect_maturity(n_years * n_ages, 0);

        for (size_t year = 0; year < n_years; year++) {
           for (size_t age = 0; age < n_ages; age++){
               int i_age_year = year * population->n_ages + age;
               catch_at_age_model->CalculateMaturityAA(population, i_age_year, age);
               expect_maturity[i_age_year] = 1.0/(1.0+exp(-(population->ages[age]-inflection_point)*slope));
           }
        }
        EXPECT_NEAR(population->proportion_mature_at_age[10], expect_maturity[10], 0.0001);
   }
}