// Instructions ----
// This file follows the format generated by FIMS:::use_gtest_template().
// Necessary tests include input and output (IO) correctness [IO
// correctness], edge-case handling [Edge handling], and built-in errors and
// warnings [Error handling]. See `?FIMS:::use_gtest_template` for more
// information. Every test should have a description comment.
// More assertion macros provided by GoogleTest can be found at
// https://google.github.io/googletest/reference/assertions.html.

#include "gtest/gtest.h"
#include "fims_math.hpp"

namespace {

// fimsMath_logistic
// IO correctness
// Test logistic using multiple input values
TEST(fimsMath_logistic, HandlesCorrectInput) {
  std::vector<double> inflection_point_value = {1.0, 10.0, 20.5};
  std::vector<double> slope_value = {0.0, 0.2, 0.05};
  std::vector<double> x_value = {2.0, 20.0, 40.5};

  // R code that generates true values for the test
  // 1.0/(1.0+exp(-(2.0-1.0)*0.0)) = 0.5
  // 1.0/(1.0+exp(-(20.0-10.0)*0.2)) = 0.8807971
  // 1.0/(1.0+exp(-(40.5-20.5)*0.05)) = 0.7310586
  std::vector<double> expect_value = {0.5, 0.8807971, 0.7310586};

  for (int i = 0; i < expect_value.size(); ++i) {
    EXPECT_NEAR(fims::math::logistic(inflection_point_value[i], slope_value[i],
                                     x_value[i]),
                expect_value[i], 0.0001);
  }
}

}  // namespace
