// Instructions ----
// This file follows the format generated by FIMS:::use_gtest_template().
// Necessary tests include input and output (IO) correctness [IO
// correctness], edge-case handling [Edge handling], and built-in errors and
// warnings [Error handling]. See `?FIMS:::use_gtest_template` for more
// information. Every test should have a description comment.
// More assertion macros provided by GoogleTest can be found at
// https://google.github.io/googletest/reference/assertions.html.

#include "gtest/gtest.h"
// Include the header file for the function being tested
// For example, if testing the `evaluate` member function of the
// `LogisticSelectivity` class, include the corresponding header in the test
// file `tests/gtest/test_population_dynamics_selectivity_logistic.cpp`:
// #include "population_dynamics/selectivity/functors/logistic.hpp"
#include "common/fims_math.hpp"
#include "population_dynamics/selectivity/functors/age_specific.hpp"

// Include additional headers as needed
// For example, include <iostream> to use `std::cerr` and `std::cout`:
// #include <iostream>

namespace {
// AgeSpecificSelectivity_Evaluate
// IO correctness
TEST(AgeSpecificSelectivity_Evaluate, HandlesCorrectInput) {
  // consider expanding Google Test by testing a vector with more than one
  // element
  fims_popdy::AgeSpecificSelectivity<double> fishery_selectivity;

  fishery_selectivity.logit_sel_at_age.resize(1);
  fishery_selectivity.logit_sel_at_age[0] = 1;
  fishery_selectivity.min_age = 1;
  fishery_selectivity.n_ages = 1;
  double fishery_x = 1.0;
  // 1.0/(1.0+exp(-1)) = 0.7310586
  double expect_fishery = 0.7310586;
  EXPECT_NEAR(fishery_selectivity.evaluate(fishery_x), expect_fishery, 0.0001);
}

// Edge handling
// Test that 1 value is used for every timestep with a single age.
TEST(AgeSpecificSelectivity_Evaluate, HandlesThreeTimeSteps) {
  // Setup
  // Load or prepare any necessary data for testing
  fims_popdy::AgeSpecificSelectivity<double> fishery_selectivity;
  fishery_selectivity.logit_sel_at_age.resize(1);
  fishery_selectivity.logit_sel_at_age[0] = 1;
  fishery_selectivity.min_age = 1;
  fishery_selectivity.n_ages = 1;
  double fishery_x = 1.0;
  // Expected values identical for all positions:
  // pos = 0/1/2: 1.0/(1.0+exp(-1)) = 0.7310586
  double expected_fishery = 0.7310586;

  // Test that evaluate(x, pos) returns the expected value at each timestep.
  for (size_t pos = 0; pos < 3; ++pos) {
    EXPECT_NEAR(fishery_selectivity.evaluate(fishery_x, pos), expected_fishery,
                0.0001);
  }
}

// Edge handling
// Test multiple ages for a single timestep.
TEST(AgeSpecificSelectivity_Evaluate, HandlesThreeAges) {
  // Setup
  // Load or prepare any necessary data for testing
  fims_popdy::AgeSpecificSelectivity<double> fishery_selectivity;
  fishery_selectivity.logit_sel_at_age.resize(3);
  fishery_selectivity.logit_sel_at_age[0] = -1;
  fishery_selectivity.logit_sel_at_age[1] = 0;
  fishery_selectivity.logit_sel_at_age[2] = 1;
  fishery_selectivity.min_age = 1;
  fishery_selectivity.n_ages = 1;
  double expected_fishery[3] = {0.2689414, 0.5, 0.7310586};

  // Test that evaluate(x, pos) returns the expected value at each timestep.
  for (size_t fishery_x = 1; fishery_x < 4; ++fishery_x) {
    EXPECT_NEAR(fishery_selectivity.evaluate(fishery_x),
                expected_fishery[fishery_x - 1], 0.0001);
  }
}

// Edge handling
// Test that n_ages values are used for every timestep.
TEST(AgeSpecificSelectivity_Evaluate, HandlesThreeAgesAndTimeSteps) {
  // Setup
  // Load or prepare any necessary data for testing
  fims_popdy::AgeSpecificSelectivity<double> fishery_selectivity;
  fishery_selectivity.logit_sel_at_age.resize(3);
  fishery_selectivity.logit_sel_at_age[0] = -1;
  fishery_selectivity.logit_sel_at_age[1] = 0;
  fishery_selectivity.logit_sel_at_age[2] = 1;
  fishery_selectivity.min_age = 1;
  fishery_selectivity.n_ages = 3;
  // Expected values by age:
  // age = 1: -1.0/(-1.0+exp(1)) = 0.2689414
  // age = 2: 0/(0+exp(0)) = 0.5
  // age = 3: 1.0/(1.0+exp(-1)) = 0.7310586
  double expected_fishery[3] = {0.2689414, 0.5, 0.7310586};

  // Test that evaluate(x, pos) returns the expected value at each timestep.
  for (size_t pos = 0; pos < 3; ++pos) {
    for (size_t fishery_x = 1; fishery_x < 4; ++fishery_x) {
      EXPECT_NEAR(fishery_selectivity.evaluate(fishery_x, pos),
                  expected_fishery[fishery_x - 1], 0.0001);
    }
  }
}

// IO correctness
// Test that n_ages values per year are used by year when the vector is
// time-varying.
TEST(AgeSpecificSelectivity_Evaluate, HandlesTimeVaryingValues) {
  fims_popdy::AgeSpecificSelectivity<double> fishery_selectivity;
  fishery_selectivity.logit_sel_at_age.resize(4);
  // year 1: ages 1 and 2; year 2: ages 1 and 2
  fishery_selectivity.logit_sel_at_age[0] = -1;
  fishery_selectivity.logit_sel_at_age[1] = 0;
  fishery_selectivity.logit_sel_at_age[2] = 1;
  fishery_selectivity.logit_sel_at_age[3] = 2;
  fishery_selectivity.min_age = 1;
  fishery_selectivity.n_ages = 2;

  // 1 / (1 + exp(-2)) = 0.8807971
  EXPECT_NEAR(fishery_selectivity.evaluate(2.0, 1), 0.8807971, 0.0001);
  EXPECT_NEAR(fishery_selectivity.evaluate(1.0, 0), 0.2689414, 0.0001);
}

// Error handling
// Test that a logit_sel_at_age length that is not 1 or a multiple of n_ages
// throws instead of reusing values for the wrong ages.
TEST(AgeSpecificSelectivity_Evaluate, ThrowsForWrongLength) {
  fims_popdy::AgeSpecificSelectivity<double> fishery_selectivity;
  fishery_selectivity.logit_sel_at_age.resize(3);
  fishery_selectivity.min_age = 1;
  fishery_selectivity.n_ages = 2;

  EXPECT_THROW(fishery_selectivity.evaluate(1.0, 0), std::invalid_argument);
}

// Error handling
// Test that a year beyond the time-varying values throws.
TEST(AgeSpecificSelectivity_Evaluate, ThrowsForYearBeyondValues) {
  fims_popdy::AgeSpecificSelectivity<double> fishery_selectivity;
  fishery_selectivity.logit_sel_at_age.resize(4);
  fishery_selectivity.min_age = 1;
  fishery_selectivity.n_ages = 2;

  EXPECT_THROW(fishery_selectivity.evaluate(1.0, 2), std::invalid_argument);
}
}  // namespace