// Instructions ----
// This file follows the format generated by FIMS:::use_gtest_template().
// Necessary tests include input and output (IO) correctness [IO
// correctness], edge-case handling [Edge handling], and built-in errors and
// warnings [Error handling]. See `?FIMS:::use_gtest_template` for more
// information. Every test should have a description comment.
// More assertion macros provided by GoogleTest can be found at
// https://google.github.io/googletest/reference/assertions.html.

#include "gtest/gtest.h"
#include "../../inst/include/interface/TMB/tmb_derived_quantity_uncertainty.hpp"
#include <stdexcept>
#include <vector>

namespace {

class FakeADFun {
 public:
  size_t Domain() const { return static_cast<size_t>(2); }

  std::vector<double> operator()(const std::vector<double>& parameters) {
    if (parameters.size() != Domain()) {
      throw std::invalid_argument("parameters size mismatch");
    }
    return std::vector<double>{
        parameters[0] + parameters[1],
        parameters[0] * parameters[1]};
  }

  std::vector<double> Jacobian(const std::vector<double>& parameters) {
    if (parameters.size() != Domain()) {
      throw std::invalid_argument("parameters size mismatch");
    }
    return std::vector<double>{
        1.0, 1.0,
        parameters[1], parameters[0]};
  }
};

class FakeNativeTMBADReportHandle : public fims_tmb::NativeTMBADReportHandle {
 public:
  fims_tmb::ADReportPayloadExtractionInput GetADReportExtractionInput()
      const override {
    fims_tmb::ADReportPayloadExtractionInput input;
    input.estimate = fims::Vector<double>{-3.0, -1.0};
    input.jacobian = fims::Vector<double>{1.0, 2.0, 2.0, 1.0};
    input.fixed_effect_covariance =
        fims::Vector<double>{4.0, 0.0, 0.0, 9.0};
    input.n_parameters = 2;
    return input;
  }
};

class FakeLaplaceReverseSweepProvider
    : public fims_tmb::LaplaceReverseSweepProvider {
 public:
  fims::Vector<double> GetFixedEffectReverseSweep(
      const fims::Vector<double>& weights,
      const fims::Vector<int>& fixed_indices) const override {
    if (fixed_indices.size() != 2) {
      throw std::invalid_argument("expected two fixed indices");
    }
    fims::Vector<double> output;
    output.push_back((10.0 * weights[1]) + weights[3]);
    output.push_back((-1.0 * weights[1]) + (2.0 * weights[3]));
    return output;
  }
};

// TMBADFunADReportHandle
// IO correctness
TEST(TMBADFunADReportHandle, HandlesCorrectInput_ReturnsADFunInput) {
  FakeADFun adfun;
  fims_tmb::TMBADFunADReportHandle<FakeADFun> handle(
      adfun, fims::Vector<double>{2.0, 3.0},
      fims::Vector<double>{4.0, 0.0, 0.0, 9.0});
  fims_tmb::ADReportPayloadExtractionInput input =
      handle.GetADReportExtractionInput();

  EXPECT_EQ(input.n_parameters, static_cast<size_t>(2));
  EXPECT_EQ(input.estimate[0], 5.0);
  EXPECT_EQ(input.estimate[1], 6.0);
  EXPECT_EQ(input.jacobian[0], 1.0);
  EXPECT_EQ(input.jacobian[3], 2.0);
  EXPECT_EQ(input.fixed_effect_covariance[3], 9.0);
}

// IO correctness
TEST(TMBADFunADReportHandle,
     HandlesCorrectInput_ReturnsRandomEffectInputs) {
  FakeADFun adfun;
  fims_tmb::TMBADFunADReportHandle<FakeADFun> handle(
      adfun, fims::Vector<double>{2.0, 3.0},
      fims::Vector<double>{4.0});
  handle.SetRandomEffectInputs(
      fims::Vector<int>{1},
      fims::Vector<double>{9.0},
      fims::Vector<double>{-0.5});
  fims_tmb::ADReportPayloadExtractionInput input =
      handle.GetADReportExtractionInput();

  EXPECT_EQ(input.random_indices[0], 1);
  EXPECT_EQ(input.random_effect_hessian[0], 9.0);
  EXPECT_EQ(input.fixed_jacobian_adjustment[0], -0.5);
}

// Error handling
TEST(TMBADFunADReportHandle, ThrowsWhenParameterSizeDoesNotMatchADFunDomain) {
  FakeADFun adfun;
  fims_tmb::TMBADFunADReportHandle<FakeADFun> handle(
      adfun, fims::Vector<double>{2.0},
      fims::Vector<double>{4.0, 0.0, 0.0, 9.0});

  EXPECT_THROW(handle.GetADReportExtractionInput(), std::invalid_argument);
}

// FixedEffectADReportUncertaintyAdapter
// IO correctness
TEST(FixedEffectADReportUncertaintyAdapter,
     HandlesCorrectInput_CalculatesStandardErrors) {
  fims_tmb::FixedEffectADReport report;
  report.request.quantity_name = "derived";
  report.request.report_name = "derived";
  report.estimate = fims::Vector<double>{-3.0, -1.0};
  report.jacobian = fims::Vector<double>{1.0, 2.0, 2.0, 1.0};
  report.fixed_effect_covariance = fims::Vector<double>{4.0, 0.0, 0.0, 9.0};
  report.n_fixed_effects = 2;

  fims_tmb::FixedEffectADReportUncertaintyAdapter adapter;
  fims_report::DerivedQuantityEstimate estimate = adapter.Calculate(report);

  EXPECT_EQ(estimate.request.report_name, "derived");
  EXPECT_EQ(estimate.estimate[0], -3.0);
  EXPECT_EQ(estimate.estimate[1], -1.0);
  EXPECT_EQ(estimate.se[0], std::sqrt(40.0));
  EXPECT_EQ(estimate.se[1], 5.0);
}

// IO correctness
TEST(FixedEffectADReportUncertaintyAdapter,
     HandlesCorrectInput_CalculatesMultipleReports) {
  fims_tmb::FixedEffectADReport report1;
  report1.request.quantity_name = "derived_one";
  report1.request.report_name = "derived_one";
  report1.estimate = fims::Vector<double>{4.0};
  report1.jacobian = fims::Vector<double>{2.0};
  report1.fixed_effect_covariance = fims::Vector<double>{9.0};
  report1.n_fixed_effects = 1;

  fims_tmb::FixedEffectADReport report2;
  report2.request.quantity_name = "derived_two";
  report2.request.report_name = "derived_two";
  report2.estimate = fims::Vector<double>{5.0};
  report2.jacobian = fims::Vector<double>{3.0};
  report2.fixed_effect_covariance = fims::Vector<double>{4.0};
  report2.n_fixed_effects = 1;

  fims_tmb::FixedEffectADReportUncertaintyAdapter::report_vector reports;
  reports.push_back(report1);
  reports.push_back(report2);

  fims_tmb::FixedEffectADReportUncertaintyAdapter adapter;
  fims_tmb::FixedEffectADReportUncertaintyAdapter::estimate_vector estimates =
      adapter.Calculate(reports);

  EXPECT_EQ(estimates.size(), static_cast<size_t>(2));
  EXPECT_EQ(estimates[0].se[0], 6.0);
  EXPECT_EQ(estimates[1].se[0], 6.0);
}

// Error handling
TEST(FixedEffectADReportUncertaintyAdapter, ThrowsWhenPayloadIsInvalid) {
  fims_tmb::FixedEffectADReport report;
  report.request.quantity_name = "derived";
  report.request.report_name = "derived";
  report.estimate = fims::Vector<double>{1.0};
  report.jacobian = fims::Vector<double>{1.0};
  report.fixed_effect_covariance = fims::Vector<double>{1.0};
  report.n_fixed_effects = 0;

  fims_tmb::FixedEffectADReportUncertaintyAdapter adapter;

  EXPECT_THROW(adapter.Calculate(report), std::invalid_argument);
}

// LaplaceADReportUncertaintyAdapter
// IO correctness
TEST(LaplaceADReportUncertaintyAdapter,
     HandlesCorrectInput_CalculatesStandardErrors) {
  fims_tmb::LaplaceADReport report;
  report.request.quantity_name = "derived";
  report.request.report_name = "derived";
  report.estimate = fims::Vector<double>{10.0, 20.0};
  report.adjusted_fixed_jacobian =
      fims::Vector<double>{1.0, 2.0, 0.5, 1.0};
  report.fixed_effect_covariance =
      fims::Vector<double>{4.0, 0.0, 0.0, 9.0};
  report.random_jacobian = fims::Vector<double>{3.0, 0.0, 1.0, 2.0};
  report.random_effect_covariance =
      fims::Vector<double>{2.0, 0.5, 0.5, 1.0};
  report.n_fixed_effects = 2;
  report.n_random_effects = 2;

  fims_tmb::LaplaceADReportUncertaintyAdapter adapter;
  fims_report::DerivedQuantityEstimate estimate = adapter.Calculate(report);

  EXPECT_EQ(estimate.request.report_name, "derived");
  EXPECT_EQ(estimate.estimate[0], 10.0);
  EXPECT_EQ(estimate.estimate[1], 20.0);
  EXPECT_DOUBLE_EQ(estimate.se[0], std::sqrt(58.0));
  EXPECT_DOUBLE_EQ(estimate.se[1], std::sqrt(18.0));
}

// Error handling
TEST(LaplaceADReportUncertaintyAdapter, ThrowsWhenPayloadIsInvalid) {
  fims_tmb::LaplaceADReport report;
  report.request.quantity_name = "derived";
  report.request.report_name = "derived";
  report.estimate = fims::Vector<double>{1.0};
  report.adjusted_fixed_jacobian = fims::Vector<double>{1.0};
  report.fixed_effect_covariance = fims::Vector<double>{1.0};
  report.random_jacobian = fims::Vector<double>{1.0};
  report.random_effect_covariance = fims::Vector<double>{1.0};
  report.n_fixed_effects = 1;
  report.n_random_effects = 0;

  fims_tmb::LaplaceADReportUncertaintyAdapter adapter;

  EXPECT_THROW(adapter.Calculate(report), std::invalid_argument);
}

// ADReportPayloadUncertaintyCalculator
// IO correctness
TEST(ADReportPayloadUncertaintyCalculator,
     HandlesCorrectInput_DispatchesFixedPayload) {
  fims_tmb::ADReportPayload payload;
  payload.method = "fixed";
  payload.request.quantity_name = "derived";
  payload.request.report_name = "derived";
  payload.estimate = fims::Vector<double>{-3.0, -1.0};
  payload.jacobian = fims::Vector<double>{1.0, 2.0, 2.0, 1.0};
  payload.fixed_effect_covariance =
      fims::Vector<double>{4.0, 0.0, 0.0, 9.0};
  payload.n_fixed_effects = 2;

  fims_tmb::ADReportPayloadUncertaintyCalculator calculator;
  fims_report::DerivedQuantityEstimate estimate = calculator.Calculate(payload);

  EXPECT_EQ(estimate.request.report_name, "derived");
  EXPECT_EQ(estimate.estimate[0], -3.0);
  EXPECT_EQ(estimate.estimate[1], -1.0);
  EXPECT_EQ(estimate.se[0], std::sqrt(40.0));
  EXPECT_EQ(estimate.se[1], 5.0);
}

// IO correctness
TEST(ADReportPayloadUncertaintyCalculator,
     HandlesCorrectInput_DispatchesFixedAfterLaplacePayload) {
  fims_tmb::ADReportPayload payload;
  payload.method = "fixed_after_laplace";
  payload.request.quantity_name = "derived";
  payload.request.report_name = "derived";
  payload.estimate = fims::Vector<double>{-3.0, -1.0};
  payload.fixed_jacobian = fims::Vector<double>{1.0, 2.0, 2.0, 1.0};
  payload.fixed_effect_covariance =
      fims::Vector<double>{4.0, 0.0, 0.0, 9.0};
  payload.n_fixed_effects = 2;

  fims_tmb::ADReportPayloadUncertaintyCalculator calculator;
  fims_report::DerivedQuantityEstimate estimate = calculator.Calculate(payload);

  EXPECT_EQ(estimate.request.report_name, "derived");
  EXPECT_EQ(estimate.se[0], std::sqrt(40.0));
  EXPECT_EQ(estimate.se[1], 5.0);
}

// IO correctness
TEST(ADReportPayloadUncertaintyCalculator,
     HandlesCorrectInput_DispatchesLaplacePayload) {
  fims_tmb::ADReportPayload payload;
  payload.method = "laplace";
  payload.request.quantity_name = "derived";
  payload.request.report_name = "derived";
  payload.estimate = fims::Vector<double>{10.0, 20.0};
  payload.adjusted_fixed_jacobian =
      fims::Vector<double>{1.0, 2.0, 0.5, 1.0};
  payload.fixed_effect_covariance =
      fims::Vector<double>{4.0, 0.0, 0.0, 9.0};
  payload.random_jacobian = fims::Vector<double>{3.0, 0.0, 1.0, 2.0};
  payload.random_effect_covariance =
      fims::Vector<double>{2.0, 0.5, 0.5, 1.0};
  payload.n_fixed_effects = 2;
  payload.n_random_effects = 2;

  fims_tmb::ADReportPayloadUncertaintyCalculator calculator;
  fims_report::DerivedQuantityEstimate estimate = calculator.Calculate(payload);

  EXPECT_EQ(estimate.request.report_name, "derived");
  EXPECT_DOUBLE_EQ(estimate.se[0], std::sqrt(58.0));
  EXPECT_DOUBLE_EQ(estimate.se[1], std::sqrt(18.0));
}

// Error handling
TEST(ADReportPayloadUncertaintyCalculator, ThrowsWhenMethodIsUnknown) {
  fims_tmb::ADReportPayload payload;
  payload.method = "quadratic";
  payload.estimate = fims::Vector<double>{1.0};
  payload.jacobian = fims::Vector<double>{1.0};
  payload.fixed_effect_covariance = fims::Vector<double>{1.0};
  payload.n_fixed_effects = 1;

  fims_tmb::ADReportPayloadUncertaintyCalculator calculator;

  EXPECT_THROW(calculator.Calculate(payload), std::invalid_argument);
}

// ADReportPayloadExtractor
// IO correctness
TEST(ADReportPayloadExtractor, HandlesCorrectInput_AssemblesFixedPayload) {
  fims_tmb::ADReportPayloadExtractionInput input;
  input.estimate = fims::Vector<double>{-3.0, -1.0};
  input.jacobian = fims::Vector<double>{1.0, 2.0, 2.0, 1.0};
  input.fixed_effect_covariance = fims::Vector<double>{4.0, 0.0, 0.0, 9.0};
  input.n_parameters = 2;

  fims_tmb::ADReportPayloadExtractor extractor;
  fims_tmb::ADReportPayload payload = extractor.Extract(input);

  EXPECT_EQ(payload.method, "fixed");
  EXPECT_EQ(payload.n_fixed_effects, static_cast<size_t>(2));
  EXPECT_EQ(payload.n_random_effects, static_cast<size_t>(0));
  EXPECT_EQ(payload.fixed_indices[0], 0);
  EXPECT_EQ(payload.fixed_indices[1], 1);
  EXPECT_EQ(payload.jacobian[0], 1.0);
  EXPECT_EQ(payload.jacobian[3], 1.0);
}

// IO correctness
TEST(ADReportPayloadExtractor,
     HandlesCorrectInput_AssemblesFixedAfterLaplacePayload) {
  fims_tmb::ADReportPayloadExtractionInput input;
  input.estimate = fims::Vector<double>{-3.0, -1.0};
  input.jacobian = fims::Vector<double>{1.0, 0.0, 2.0, 0.0};
  input.fixed_effect_covariance = fims::Vector<double>{4.0};
  input.random_effect_hessian = fims::Vector<double>{9.0};
  input.fixed_jacobian_adjustment = fims::Vector<double>{0.0, 0.0};
  input.random_indices = fims::Vector<int>{1};
  input.n_parameters = 2;

  fims_tmb::ADReportPayloadExtractor extractor;
  fims_tmb::ADReportPayload payload = extractor.Extract(input);

  EXPECT_EQ(payload.method, "fixed_after_laplace");
  EXPECT_EQ(payload.n_fixed_effects, static_cast<size_t>(1));
  EXPECT_EQ(payload.n_random_effects, static_cast<size_t>(1));
  EXPECT_EQ(payload.fixed_indices[0], 0);
  EXPECT_EQ(payload.random_indices[0], 1);
  EXPECT_EQ(payload.fixed_jacobian[0], 1.0);
  EXPECT_EQ(payload.fixed_jacobian[1], 2.0);
}

// IO correctness
TEST(ADReportPayloadExtractor, HandlesCorrectInput_AssemblesLaplacePayload) {
  fims_tmb::ADReportPayloadExtractionInput input;
  input.estimate = fims::Vector<double>{10.0, 20.0};
  input.jacobian = fims::Vector<double>{1.0, 3.0, 0.5, 2.0};
  input.fixed_effect_covariance = fims::Vector<double>{4.0};
  input.random_effect_hessian = fims::Vector<double>{0.5};
  input.fixed_jacobian_adjustment = fims::Vector<double>{2.0, 0.5};
  input.random_indices = fims::Vector<int>{1};
  input.n_parameters = 2;

  fims_tmb::ADReportPayloadExtractor extractor;
  fims_tmb::ADReportPayload payload = extractor.Extract(input);

  EXPECT_EQ(payload.method, "laplace");
  EXPECT_EQ(payload.fixed_jacobian[0], 1.0);
  EXPECT_EQ(payload.fixed_jacobian[1], 0.5);
  EXPECT_EQ(payload.random_jacobian[0], 3.0);
  EXPECT_EQ(payload.random_jacobian[1], 2.0);
  EXPECT_EQ(payload.random_effect_covariance[0], 2.0);
  EXPECT_EQ(payload.adjusted_fixed_jacobian[0], 3.0);
  EXPECT_EQ(payload.adjusted_fixed_jacobian[1], 1.0);
}

// Error handling
TEST(ADReportPayloadExtractor, ThrowsWhenJacobianDimensionsAreInvalid) {
  fims_tmb::ADReportPayloadExtractionInput input;
  input.estimate = fims::Vector<double>{1.0};
  input.jacobian = fims::Vector<double>{1.0};
  input.fixed_effect_covariance = fims::Vector<double>{1.0};
  input.n_parameters = 2;

  fims_tmb::ADReportPayloadExtractor extractor;

  EXPECT_THROW(extractor.Extract(input), std::invalid_argument);
}

// StaticADReportDerivativeProvider
// IO correctness
TEST(StaticADReportDerivativeProvider, HandlesCorrectInput_ReturnsDerivativeBundle) {
  fims_tmb::ADReportPayloadExtractionInput input;
  input.estimate = fims::Vector<double>{4.0};
  input.jacobian = fims::Vector<double>{2.0};
  input.fixed_effect_covariance = fims::Vector<double>{9.0};
  input.n_parameters = 1;

  fims_tmb::StaticADReportDerivativeProvider provider(input);
  fims_tmb::ADReportPayloadExtractionInput output =
      provider.GetExtractionInput();

  EXPECT_EQ(output.estimate[0], 4.0);
  EXPECT_EQ(output.jacobian[0], 2.0);
  EXPECT_EQ(output.fixed_effect_covariance[0], 9.0);
  EXPECT_EQ(output.n_parameters, static_cast<size_t>(1));
}

// LaplaceFixedJacobianAdjustmentCalculator
// IO correctness
TEST(LaplaceFixedJacobianAdjustmentCalculator,
     HandlesCorrectInput_CalculatesAdjustment) {
  fims_tmb::LaplaceFixedJacobianAdjustmentCalculator calculator;
  FakeLaplaceReverseSweepProvider reverse_provider;

  fims::Vector<double> adjustment = calculator.Calculate(
      fims::Vector<double>{2.0, 0.0, 0.0, 4.0},
      fims::Vector<double>{2.0, 8.0, 4.0, 12.0},
      fims::Vector<int>{1, 3},
      fims::Vector<int>{0, 2},
      4,
      2,
      reverse_provider);

  ASSERT_EQ(adjustment.size(), static_cast<size_t>(4));
  EXPECT_DOUBLE_EQ(adjustment[0], -12.0);
  EXPECT_DOUBLE_EQ(adjustment[1], -3.0);
  EXPECT_DOUBLE_EQ(adjustment[2], -23.0);
  EXPECT_DOUBLE_EQ(adjustment[3], -4.0);
}

// Error handling
TEST(LaplaceFixedJacobianAdjustmentCalculator,
     ThrowsWhenRandomJacobianSizeIsInvalid) {
  fims_tmb::LaplaceFixedJacobianAdjustmentCalculator calculator;
  FakeLaplaceReverseSweepProvider reverse_provider;

  EXPECT_THROW(
      calculator.Calculate(
          fims::Vector<double>{2.0},
          fims::Vector<double>{1.0, 2.0},
          fims::Vector<int>{1},
          fims::Vector<int>{0},
          2,
          3,
          reverse_provider),
      std::invalid_argument);
}

// IO correctness
TEST(ADReportPayloadExtractor,
     HandlesCorrectInput_AssemblesPayloadFromProvider) {
  fims_tmb::ADReportPayloadExtractionInput input;
  input.estimate = fims::Vector<double>{-3.0, -1.0};
  input.jacobian = fims::Vector<double>{1.0, 2.0, 2.0, 1.0};
  input.fixed_effect_covariance = fims::Vector<double>{4.0, 0.0, 0.0, 9.0};
  input.n_parameters = 2;

  fims_tmb::StaticADReportDerivativeProvider provider(input);
  fims_tmb::ADReportPayloadExtractor extractor;
  fims_tmb::ADReportPayload payload = extractor.Extract(provider);

  EXPECT_EQ(payload.method, "fixed");
  EXPECT_EQ(payload.n_fixed_effects, static_cast<size_t>(2));
  EXPECT_EQ(payload.jacobian[0], 1.0);
  EXPECT_EQ(payload.jacobian[3], 1.0);
}

// NativeTMBADReportDerivativeProvider
// Edge handling
TEST(NativeTMBADReportDerivativeProvider, HandlesEdge_DefaultHasNoHandle) {
  fims_tmb::NativeTMBADReportDerivativeProvider provider;

  EXPECT_FALSE(provider.HasModelHandle());
  EXPECT_FALSE(provider.HasNativeHandle());
  EXPECT_FALSE(provider.HasAnyHandle());
}

// Error handling
TEST(NativeTMBADReportDerivativeProvider, ThrowsUntilNativeHandleAccessExists) {
  int model_handle = 1;
  fims_tmb::NativeTMBADReportDerivativeProvider provider(&model_handle);

  EXPECT_TRUE(provider.HasModelHandle());
  EXPECT_FALSE(provider.HasNativeHandle());
  EXPECT_TRUE(provider.HasAnyHandle());
  EXPECT_THROW(provider.GetExtractionInput(), std::logic_error);
}

// IO correctness
TEST(NativeTMBADReportDerivativeProvider,
     HandlesCorrectInput_ReturnsInputFromNativeHandle) {
  FakeNativeTMBADReportHandle native_handle;
  fims_tmb::NativeTMBADReportDerivativeProvider provider(native_handle);
  fims_tmb::ADReportPayloadExtractionInput input =
      provider.GetExtractionInput();

  EXPECT_FALSE(provider.HasModelHandle());
  EXPECT_TRUE(provider.HasNativeHandle());
  EXPECT_TRUE(provider.HasAnyHandle());
  EXPECT_EQ(input.estimate[0], -3.0);
  EXPECT_EQ(input.jacobian[3], 1.0);
  EXPECT_EQ(input.n_parameters, static_cast<size_t>(2));
}

// IO correctness
TEST(ADReportPayloadExtractor,
     HandlesCorrectInput_AssemblesPayloadFromNativeProvider) {
  FakeNativeTMBADReportHandle native_handle;
  fims_tmb::NativeTMBADReportDerivativeProvider provider(native_handle);
  fims_tmb::ADReportPayloadExtractor extractor;
  fims_tmb::ADReportPayload payload = extractor.Extract(provider);

  EXPECT_EQ(payload.method, "fixed");
  EXPECT_EQ(payload.n_fixed_effects, static_cast<size_t>(2));
  EXPECT_EQ(payload.jacobian[0], 1.0);
  EXPECT_EQ(payload.jacobian[3], 1.0);
}

}  // namespace
