// Instructions ----
// This file follows the format generated by FIMS:::use_gtest_template().
// Necessary tests include input and output (IO) correctness [IO
// correctness], edge-case handling [Edge handling], and built-in errors and
// warnings [Error handling]. See `?FIMS:::use_gtest_template` for more
// information. Every test should have a description comment.
// More assertion macros provided by GoogleTest can be found at 
// https://google.github.io/googletest/reference/assertions.html.

#include "gtest/gtest.h"
// Include the header file for the function being tested
// For example, if testing the `evaluate` member function of the 
// `LogisticSelectivity` class, include the corresponding header in the test 
// file `tests/gtest/test_population_dynamics_selectivity_logistic.cpp`:
// #include "population_dynamics/selectivity/functors/logistic.hpp"
#include "population_dynamics/selectivity/functors/age_specific.hpp"
// Include additional headers as needed
// For example, include <iostream> to use `std::cerr` and `std::cout`:
// #include <iostream>

namespace
{
  // AgeSpecificSelectivity_Evaluate 
  // IO correctness
  TEST(AgeSpecificSelectivity_Evaluate, HandlesCorrectInput)
  {
    // consider expanding Google Test by testing a vector with more than one element
    fims_popdy::AgeSpecificSelectivity<double> fishery_selectivity;
    EXPECT_EQ(fishery_selectivity.min_age, 1.0); // test intended default values
    EXPECT_EQ(fishery_selectivity.n_ages, 1.0); // test intended default values

    fishery_selectivity.logit_sel_at_age.resize(1);
    fishery_selectivity.logit_sel_at_age[0] = 1;
    fishery_selectivity.min_age.resize(1);
    fishery_selectivity.min_age[0] = 1;
    fishery_selectivity.n_ages.resize(1);
    fishery_selectivity.n_ages[0] = 1;
    double fishery_x = 1.0;
    // 1.0/(1.0+exp(-1)) = 0.7310586
    double expect_fishery = 0.7310586;
    EXPECT_NEAR(fishery_selectivity.evaluate(fishery_x), expect_fishery, 0.0001);

  }

  // Edge handling
  // Test the use of get_force_scalar_wrap across multiple timesteps with single age.
  TEST(AgeSpecificSelectivity_Evaluate, HandlesThreeTimeSteps) {
    // Setup 
    // Load or prepare any necessary data for testing
    fims_popdy::AgeSpecificSelectivity<double> fishery_selectivity;
    fishery_selectivity.logit_sel_at_age.resize(1);
    fishery_selectivity.logit_sel_at_age[0] = 1;
        fishery_selectivity.min_age.resize(1);
    fishery_selectivity.min_age[0] = 1;
    fishery_selectivity.n_ages.resize(1);
    fishery_selectivity.n_ages[0] = 1;
    // Uses get_force_scalar_wrap internally to have the same logit_sel_at_age 
    // for all 3 values 
    double fishery_x = 1.0;
    // Expected values identical for all positions:
    // pos = 0/1/2: 1.0/(1.0+exp(-1)) = 0.7310586
    double expected_fishery = 0.7310586;
    
    // Test that evaluate(x, pos) returns the expected value at each timestep.
    for (size_t pos = 0; pos < 3; ++pos) {
      EXPECT_NEAR(fishery_selectivity.evaluate(fishery_x, pos),
                  expected_fishery, 0.0001);
    }
  
  }

  // Edge handling
  // Test the use of get_force_scalar_wrap across multiple ages and timesteps.
  TEST(AgeSpecificSelectivity_Evaluate, HandlesThreeAgesandTimeSteps) {
    // Setup 
    // Load or prepare any necessary data for testing
    fims_popdy::AgeSpecificSelectivity<double> fishery_selectivity;
    fishery_selectivity.logit_sel_at_age.resize(3);
    fishery_selectivity.logit_sel_at_age[0] = -1;
    fishery_selectivity.logit_sel_at_age[1] = 0;
    fishery_selectivity.logit_sel_at_age[2] = 1;
    fishery_selectivity.min_age.resize(1);
    fishery_selectivity.min_age[0] = 1;
    fishery_selectivity.n_ages.resize(1);
    fishery_selectivity.n_ages[0] = 3;
    // Uses get_force_scalar_wrap internally to have the same logit_sel_at_age 
    // for all 3 timesteps for each age
    // Expected values by age:
    // age = 1: -1.0/(-1.0+exp(1)) = 0.2689414
    // age = 2: 0/(0+exp(0)) = 0.5
    // age = 3: 1.0/(1.0+exp(-1)) = 0.7310586
    double expected_fishery[3] = {0.2689414, 0.5, 0.7310586};
    
    // Test that evaluate(x, pos) returns the expected value at each timestep.
    for (size_t pos = 0; pos < 3; ++pos) {
      for (size_t fishery_x = 1; fishery_x < 4; ++fishery_x) {
        EXPECT_NEAR(fishery_selectivity.evaluate(fishery_x, pos),
                    expected_fishery[pos], 0.0001);
      }
    }
  
  }

  // Error handling
  // No built-in errors/warnings.
}