// Instructions ----
// This file follows the format generated by FIMS:::use_gtest_template().
// Necessary tests include input and output (IO) correctness [IO
// correctness], edge-case handling [Edge handling], and built-in errors and
// warnings [Error handling]. See `?FIMS:::use_gtest_template` for more
// information. Every test should have a description comment.
// More assertion macros provided by GoogleTest can be found at
// https://google.github.io/googletest/reference/assertions.html.

#include "gtest/gtest.h"
#include "population/population.hpp"
#include "../../tests/gtest/test_population_test_fixture.hpp"

namespace
{
    // CatchAtAge_CalculateCatchNumbersAA
    // IO correctness
    TEST_F(CAAEvaluateTestFixture, HandlesCorrectInput)
    {
        
        size_t pop_id = population->GetId();
        auto& dq_pop = catch_at_age_model->GetPopulationDerivedQuantities(pop_id);

        // calculate catch numbers at age in population module
        catch_at_age_model->CalculateCatchNumbersAA(population, i_age_year, year, age);
        catch_at_age_model->CalculateCatchWeightAA(population, year, age);

        std::vector<double> mortality_F(n_years * n_ages, 0);
        // dimension of test_catch_naa matches population module, not
        // fleet module
        std::vector<double> test_catch_naa(n_years * n_ages * n_fleets, 0);
        std::vector<double> test_catch_waa(n_years * n_ages * n_fleets, 0);
        std::vector<double> test_naa((n_years + 1) * n_ages, 0);
        
        double catch_temp;

        for (int i = 0; i < (n_years + 1) * n_ages; i++)
        {
          test_naa[i] = dq_pop["numbers_at_age"][i];
       }
        test_naa[i_age_year] = test_naa[i_agem1_yearm1] * exp(-dq_pop["mortality_Z"][i_agem1_yearm1]);

        // loop over fleets to get catch numbers at age for each fleet
        for (size_t fleet_index = 0; fleet_index < population->n_fleets; fleet_index++)
        {
            // indices for use in catch equation copied from
            //   \inst\include\population_dynamics\population\population.hpp
            int i_age_yearf = year * population->n_ages * population->n_fleets +
              age * population->n_fleets + fleet_index;

            uint32_t fleet_id = population->fleets[fleet_index]->GetId();
            auto& dq_fleet = catch_at_age_model->GetFleetDerivedQuantities(fleet_id);

            // Baranov Catch Equation adapted from 
            // \inst\include\population_dynamics\population\population.hpp
           catch_temp =
              (population->fleets[fleet_index]->Fmort[year] *
              population->fleets[fleet_index]->selectivity->evaluate(population->ages[age])) /
              dq_pop["mortality_Z"][i_age_year] *
              test_naa[i_age_year] *
              (1 - exp(-(dq_pop["mortality_Z"][i_age_year])));
            test_catch_naa[i_age_yearf] += catch_temp;
            test_catch_waa[i_age_yearf] += catch_temp * population->growth->evaluate(year, population->ages[age]);

            // test value
          EXPECT_EQ(dq_fleet["catch_numbers_at_age"][i_age_year], test_catch_naa[i_age_yearf]);
          EXPECT_EQ(dq_fleet["catch_weight_at_age"][i_age_year], test_catch_waa[i_age_yearf]);
          // Default pooled demand leaves partitioned catch untouched.
          EXPECT_EQ(dq_fleet["catch_numbers_at_age_by_partition"],
                    fims::Vector(
                        dq_fleet["catch_numbers_at_age_by_partition"].size(),
                        0.0));
          EXPECT_EQ(dq_fleet["catch_weight_at_age_by_partition"],
                    fims::Vector(
                        dq_fleet["catch_weight_at_age_by_partition"].size(),
                        0.0));

        }
    }

    // Female demand splits pooled catch into the female stratum only.
    TEST_F(CAAEvaluateTestFixture, FemaleDemandWritesCatchByPartition)
    {
        population->partition_spec = fims_popdy::MakeDefaultSexPartitionSpec();
        population->index_layout.n_strata = population->partition_spec.n_strata();
        population->index_layout.n_years = population->n_years;
        population->index_layout.n_ages = population->n_ages;
        population->partition_demand =
            fims_popdy::MakeSexPartitionDemand({"female"});
        const double p_female =
            population->proportion_female.get_force_scalar(age);

        catch_at_age_model->CalculateCatchNumbersAA(population, i_age_year,
                                                    year, age);
        catch_at_age_model->CalculateCatchWeightAA(population, year, age);

        for (size_t fleet_index = 0; fleet_index < population->n_fleets;
             fleet_index++) {
            uint32_t fleet_id = population->fleets[fleet_index]->GetId();
            auto &dq_fleet =
                catch_at_age_model->GetFleetDerivedQuantities(fleet_id);
            const size_t female_idx =
                population->index_layout.i_stratum_age_year(0, year, age);
            const size_t male_idx =
                population->index_layout.i_stratum_age_year(1, year, age);

            EXPECT_DOUBLE_EQ(
                dq_fleet["catch_numbers_at_age_by_partition"][female_idx],
                dq_fleet["catch_numbers_at_age"][i_age_year] * p_female);
            EXPECT_DOUBLE_EQ(
                dq_fleet["catch_numbers_at_age_by_partition"][male_idx], 0.0);
            EXPECT_DOUBLE_EQ(
                dq_fleet["catch_weight_at_age_by_partition"][female_idx],
                dq_fleet["catch_weight_at_age"][i_age_year] * p_female);
            EXPECT_DOUBLE_EQ(
                dq_fleet["catch_weight_at_age_by_partition"][male_idx], 0.0);
        }
    }
}