// Instructions ----
// This file follows the format generated by FIMS:::use_gtest_template().
// Necessary tests include input and output (IO) correctness [IO
// correctness], edge-case handling [Edge handling], and built-in errors and
// warnings [Error handling]. See `?FIMS:::use_gtest_template` for more
// information. Every test should have a description comment.
// More assertion macros provided by GoogleTest can be found at
// https://google.github.io/googletest/reference/assertions.html.

#include "gtest/gtest.h"
#include "recruitment/functors/recruitment_base.hpp"
#include "recruitment/functors/sr_beverton_holt.hpp"

namespace
{
  // SRBevertonHolt_PrepareConstrainedDeviations
  // IO correctness
  TEST(SRBevertonHolt_PrepareConstrainedDeviations, HandlesCorrectInput)
  {
    fims_popdy::SRBevertonHolt<double> recruit;
    recruit.log_recruit_devs.resize(3);
    recruit.log_recruit_devs[0] = -1.0;
    recruit.log_recruit_devs[1] = 2.0;
    recruit.log_recruit_devs[2] = 3.0;

    // Test if constrain_deviations = false works
    recruit.constrain_deviations = false;
    recruit.PrepareConstrainedDeviations();

    fims::Vector<double> expected_deviations_false(3, 0);
    expected_deviations_false[0] = -1.0;
    expected_deviations_false[1] = 2.0;
    expected_deviations_false[2] = 3.0;
    for (int i = 0; i < recruit.log_recruit_devs.size(); i++)
    {
      EXPECT_EQ(recruit.log_recruit_devs[i],
                expected_deviations_false[i]);
    }

    // Test if constrain_deviations = true works
    recruit.constrain_deviations = true;
    recruit.PrepareConstrainedDeviations();
    // c(-1.0, 2.0, 3.0)-sum(c(-1.0, 2.0, 3.0))/3 = -2.3333333  0.6666667  1.6666667
    std::vector<double> expected_deviations_true = {-2.3333333, 0.6666667, 1.6666667};

    for (int i = 0; i < recruit.log_recruit_devs.size(); i++)
    {
      EXPECT_NEAR(recruit.log_recruit_devs[i],
                  expected_deviations_true[i], 0.0000001);
    }
  }

}
