// Instructions ----
// This file follows the format generated by FIMS:::use_gtest_template().
// Necessary tests include input and output (IO) correctness [IO
// correctness], edge-case handling [Edge handling], and built-in errors and
// warnings [Error handling]. See `?FIMS:::use_gtest_template` for more
// information. Every test should have a description comment.
// More assertion macros provided by GoogleTest can be found at
// https://google.github.io/googletest/reference/assertions.html.

#include "gtest/gtest.h"
#include "population/population.hpp"
#include "../../tests/gtest/test_population_test_fixture.hpp"

namespace {

// CatchAtAge_CalculateMortality
// IO correctness
TEST_F(CAAPrepareTestFixture,
       HandlesCorrectInput_CatchAtAge_CalculateMortality) {
  this->InitializeCAA();
  catch_at_age_model->Prepare();
  size_t pop_id = population->GetId();
  auto& dq = catch_at_age_model->GetPopulationDerivedQuantities(pop_id);

  for (int year = 0; year < population->n_years; year++) {
    for (int age = 0; age < population->n_ages; age++) {
      int i_age_year = year * population->n_ages + age;
      // Call FIMS CalculateMortality() to compare FIMS mortality
      // values with expected values later.
      catch_at_age_model->CalculateMortality(population, i_age_year, year, age);
    }
  }

  std::vector<double> mortality_F(population->n_ages * population->n_years,
                                  0.0);
  std::vector<double> mortality_Z(population->n_ages * population->n_years,
                                  0.0);
  for (int year = 0; year < population->n_years; year++) {
    for (int age = 0; age < population->n_ages; age++) {
      int i_age_year = year * population->n_ages + age;

      for (int fleet_index = 0; fleet_index < population->n_fleets;
           fleet_index++) {
        mortality_F[i_age_year] +=
            population->fleets[fleet_index]->Fmort[year] *
            population->fleets[fleet_index]->selectivity->evaluate(
                population->ages[age]);
      }
      EXPECT_LT(abs(dq["mortality_F"][i_age_year] - mortality_F[i_age_year]),
                1e-7);

      mortality_Z[i_age_year] = fims_math::exp(population->log_M[i_age_year]) +
                                dq["mortality_F"][i_age_year];
      EXPECT_LT(abs(dq["mortality_Z"][i_age_year] - mortality_Z[i_age_year]),
                1e-7);
    }
  }
}

// CatchAtAge_CalculateInitialNumbersAA
// IO correctness
TEST_F(CAAEvaluateTestFixture,
       HandlesCorrectInput_CatchAtAge_CalculateInitialNumbersAA) {
  size_t pop_id = population->GetId();
  auto& dq = catch_at_age_model->GetPopulationDerivedQuantities(pop_id);

  std::vector<double> numbers_at_age(n_years * n_ages, 0);

  for (int year = 0; year < population->n_years; year++) {
    for (int age = 0; age < population->n_ages; age++) {
      int i_age_year = year * population->n_ages + age;

      catch_at_age_model->CalculateInitialNumbersAA(population, i_age_year,
                                                    age);

      numbers_at_age[i_age_year] =
          fims_math::exp(population->log_init_naa[age]);
      EXPECT_EQ(dq["numbers_at_age"][i_age_year], numbers_at_age[i_age_year]);
    }
  }
}

// CatchAtAge_CalculateUnfishedNumbersAA and
// CatchAtAge_CalculateUnfishedSpawningBiomass
// IO correctness
TEST_F(
    CAAEvaluateTestFixture,
    HandlesCorrectInput_CatchAtAge_CalculateUnfishedNumbersAA_CalculateUnfishedSpawningBiomass) {
  std::vector<double> test_unfished_numbers_at_age((n_years + 1) * n_ages, 0);
  std::vector<double> test_unfished_spawning_biomass(n_years + 1, 0);

  size_t pop_id = population->GetId();
  auto& dq = catch_at_age_model->GetPopulationDerivedQuantities(pop_id);

  for (int year = 0; year < (population->n_years + 1); year++) {
    for (int age = 0; age < population->n_ages; age++) {
      int i_age_year = year * population->n_ages + age;

      if (age == 0) {
        dq["unfished_numbers_at_age"][i_age_year] =
            fims_math::exp(population->recruitment->log_rzero[0]);
        test_unfished_numbers_at_age[i_age_year] =
            fims_math::exp(population->recruitment->log_rzero[0]);
      }

      if (year == 0 && age > 0) {
        catch_at_age_model->CalculateUnfishedInitialNumbersAA(population,
                                                              i_age_year, age);
        test_unfished_numbers_at_age[i_age_year] =
            test_unfished_numbers_at_age[i_age_year - 1] *
            fims_math::exp(-fims_math::exp(population->log_M[i_age_year - 1]));
        // The year-0 plus group is the equilibrium sum over all older ages
        if (age == (population->n_ages - 1)) {
          test_unfished_numbers_at_age[i_age_year] /=
              (1.0 - fims_math::exp(
                         -fims_math::exp(population->log_M[i_age_year])));
        }
      }

      if (year > 0 && age > 0) {
        int i_agem1_yearm1 = (year - 1) * population->n_ages + (age - 1);
        EXPECT_GT(population->M[i_agem1_yearm1], 0.0);
        catch_at_age_model->CalculateUnfishedNumbersAA(population, i_age_year,
                                                       i_agem1_yearm1, age);
        test_unfished_numbers_at_age[i_age_year] =
            test_unfished_numbers_at_age[i_agem1_yearm1] *
            fims_math::exp(-fims_math::exp(population->log_M[i_agem1_yearm1]));
      }

      if (year > 0 && age == (population->n_ages - 1)) {
        int i_agem1_yearm1 = (year - 1) * population->n_ages + (age - 1);
        test_unfished_numbers_at_age[i_age_year] +=
            test_unfished_numbers_at_age[i_agem1_yearm1 + 1] *
            fims_math::exp(
                -fims_math::exp(population->log_M[i_agem1_yearm1 + 1]));
      }

      catch_at_age_model->CalculateMaturityAA(population, i_age_year, year,
                                              age);
      catch_at_age_model->CalculateUnfishedSpawningBiomass(
          population, i_age_year, year, age);

      test_unfished_spawning_biomass[year] +=
          dq["proportion_mature_at_age"][i_age_year] *
          population->proportion_female[age] *
          test_unfished_numbers_at_age[i_age_year] *
          population->growth->evaluate(year, population->ages[age]);

      EXPECT_EQ(dq["unfished_numbers_at_age"][i_age_year],
                test_unfished_numbers_at_age[i_age_year]);
      EXPECT_GT(dq["unfished_numbers_at_age"][i_age_year], 0.0);
    }

    EXPECT_NEAR(dq["unfished_spawning_biomass"][year],
                test_unfished_spawning_biomass[year], 1e-7);
    EXPECT_GT(dq["unfished_spawning_biomass"][year], 0.0);
  }
}

// CatchAtAge_CalculateUnfishedInitialNumbersAA and CatchAtAge_CalculateSBPR0
// IO correctness
TEST_F(
    CAAEvaluateTestFixture,
    HandlesCorrectInput_CatchAtAge_UnfishedSpawningBiomassYear0EqualsR0TimesPhi0) {
  size_t pop_id = population->GetId();
  auto& dq = catch_at_age_model->GetPopulationDerivedQuantities(pop_id);
  double r0 = fims_math::exp(population->recruitment->log_rzero[0]);

  for (int age = 0; age < population->n_ages; age++) {
    if (age == 0) {
      dq["unfished_numbers_at_age"][age] = r0;
    } else {
      catch_at_age_model->CalculateUnfishedInitialNumbersAA(population, age,
                                                            age);
    }
    catch_at_age_model->CalculateMaturityAA(population, age, age);
    catch_at_age_model->CalculateUnfishedSpawningBiomass(population, age, 0,
                                                         age);
  }

  // Unfished spawning biomass in year 0 is the equilibrium, so it must equal
  // unfished recruitment times unfished spawning biomass per recruit. The
  // fixture's natural mortality varies by age, so this also checks that both
  // use the natural mortality of the age being left.
  double phi_0 = catch_at_age_model->CalculateSBPR0(population);
  EXPECT_NEAR(dq["unfished_spawning_biomass"][0], r0 * phi_0,
              1e-10 * r0 * phi_0);
}

// CatchAtAge_CalculateUnfishedInitialNumbersAA and
// CatchAtAge_CalculateUnfishedNumbersAA
// Edge handling
TEST_F(CAAEvaluateTestFixture,
       HandlesConstantM_CatchAtAge_UnfishedNumbersAtEquilibrium) {
  size_t pop_id = population->GetId();
  auto& dq = catch_at_age_model->GetPopulationDerivedQuantities(pop_id);
  double r0 = fims_math::exp(population->recruitment->log_rzero[0]);
  double m = 0.2;
  for (size_t i = 0; i < population->M.size(); i++) {
    population->M[i] = m;
  }

  for (int year = 0; year < (population->n_years + 1); year++) {
    for (int age = 0; age < population->n_ages; age++) {
      int i_age_year = year * population->n_ages + age;
      if (age == 0) {
        dq["unfished_numbers_at_age"][i_age_year] = r0;
      } else if (year == 0) {
        catch_at_age_model->CalculateUnfishedInitialNumbersAA(population,
                                                              i_age_year, age);
      } else {
        int i_agem1_yearm1 = (year - 1) * population->n_ages + (age - 1);
        catch_at_age_model->CalculateUnfishedNumbersAA(population, i_age_year,
                                                       i_agem1_yearm1, age);
      }
    }
  }

  // With constant natural mortality, unfished numbers at age are
  // R0 * exp(-M * a) for a < A and R0 * exp(-M * A) / (1 - exp(-M)) for the
  // plus group A, and they do not change from year to year.
  int plus_group = population->n_ages - 1;
  for (int year = 0; year < (population->n_years + 1); year++) {
    for (int age = 0; age < population->n_ages; age++) {
      int i_age_year = year * population->n_ages + age;
      double expected = r0 * std::exp(-m * age);
      if (age == plus_group) {
        expected /= (1.0 - std::exp(-m));
      }
      EXPECT_NEAR(dq["unfished_numbers_at_age"][i_age_year], expected,
                  1e-10 * expected);
    }
  }
}
}  // namespace
