// Instructions ----
// This file follows the format generated by FIMS:::use_gtest_template().
// Necessary tests include input and output (IO) correctness [IO
// correctness], edge-case handling [Edge handling], and built-in errors and
// warnings [Error handling]. See `?FIMS:::use_gtest_template` for more
// information. Every test should have a description comment.
// More assertion macros provided by GoogleTest can be found at
// https://google.github.io/googletest/reference/assertions.html.

#include "gtest/gtest.h"
#include "common/def.hpp"

#include <cstdio>
#include <fstream>
#include <sstream>
#include <string>

namespace {

fims::FIMSLog MakeLogger() {
  fims::FIMSLog log;
  log.write_on_exit = false;
  log.throw_on_error = false;
  return log;
}

// FIMSLog_clear
// IO correctness
TEST(LogEntry_to_string, HandlesCorrectInput) {
  // Setup a deterministic log entry.
  fims::LogEntry entry;
  entry.timestamp = "Jan 01 00:00:00 2000";
  entry.level = "warning";
  entry.message = "logger test message";
  entry.rank = 7;
  entry.user = "tester";
  entry.wd = "/tmp/fims";
  entry.file = "/tmp/fims/source.cpp";
  entry.routine = "TestRoutine";
  entry.line = 123;

  // Test that serialization includes each expected JSON field/value.
  const std::string serialized = entry.to_string();
  EXPECT_NE(serialized.find("\"timestamp\": \"Jan 01 00:00:00 2000\""), std::string::npos);
  EXPECT_NE(serialized.find("\"level\": \"warning\""), std::string::npos);
  EXPECT_NE(serialized.find("\"message\": \"logger test message\""), std::string::npos);
  EXPECT_NE(serialized.find("\"id\": \"7\""), std::string::npos);
  EXPECT_NE(serialized.find("\"user\": \"tester\""), std::string::npos);
  EXPECT_NE(serialized.find("\"wd\": \"/tmp/fims\""), std::string::npos);
  EXPECT_NE(serialized.find("\"file\": \"/tmp/fims/source.cpp\""), std::string::npos);
  EXPECT_NE(serialized.find("\"routine\": \"TestRoutine\""), std::string::npos);
  EXPECT_NE(serialized.find("\"line\": \"123\""), std::string::npos);
}

TEST(FIMSLog_getAbsolutePathWithoutDotDot, HandlesCorrectInput) {
  // Setup a relative path containing parent-directory navigation.
  fims::FIMSLog log = MakeLogger();
  const auto normalized_path =
      log.getAbsolutePathWithoutDotDot("alpha/beta/../gamma.txt");
  const std::string normalized_path_string = normalized_path.generic_string();

  // Test that dot-dot notation is removed from the absolute path.
  EXPECT_EQ(normalized_path_string.find(".."), std::string::npos);
  EXPECT_NE(normalized_path_string.find("alpha/gamma.txt"), std::string::npos);
}

TEST(FIMSLog_Getters, FiltersEntriesBySeverity) {
  // Setup a logger with one entry per severity.
  fims::FIMSLog log = MakeLogger();
  log.info_message("info only", 11, "../tmp/info.cpp", "InfoRoutine");
  log.warning_message("warning only", 22, "../tmp/warn.cpp", "WarnRoutine");
  log.error_message("error only", 33, "../tmp/error.cpp", "ErrorRoutine");

  const std::string all_entries = log.get_log();
  const std::string info_entries = log.get_info();
  const std::string warning_entries = log.get_warnings();
  const std::string error_entries = log.get_errors();

  // Test that the full log contains every message.
  EXPECT_NE(all_entries.find("info only"), std::string::npos);
  EXPECT_NE(all_entries.find("warning only"), std::string::npos);
  EXPECT_NE(all_entries.find("error only"), std::string::npos);

  // Test that severity-specific getters return only matching entries.
  EXPECT_NE(info_entries.find("info only"), std::string::npos);
  EXPECT_EQ(info_entries.find("warning only"), std::string::npos);
  EXPECT_EQ(info_entries.find("error only"), std::string::npos);

  EXPECT_NE(warning_entries.find("warning only"), std::string::npos);
  EXPECT_EQ(warning_entries.find("info only"), std::string::npos);
  EXPECT_EQ(warning_entries.find("error only"), std::string::npos);

  EXPECT_NE(error_entries.find("error only"), std::string::npos);
  EXPECT_EQ(error_entries.find("info only"), std::string::npos);
  EXPECT_EQ(error_entries.find("warning only"), std::string::npos);
}

TEST(FIMSLog_clear, HandlesCorrectInput) {
  // Setup a logger with one info, one warning, and one error entry.
  fims::FIMSLog log = MakeLogger();
  log.info_message("info message", 10, "../tmp/info.cpp", "InfoRoutine");
  log.warning_message("warning message", 20, "../tmp/warn.cpp", "WarnRoutine");
  log.error_message("error message", 30, "../tmp/error.cpp", "ErrorRoutine");

  ASSERT_NE(log.get_log(), "[\n]");
  ASSERT_EQ(log.get_warning_count(), 1);
  ASSERT_EQ(log.get_error_count(), 1);

  // Test that clear removes all stored entries and resets the counters.
  log.clear();

  EXPECT_EQ(log.get_log(), "[\n]");
  EXPECT_EQ(log.get_info(), "[\n]");
  EXPECT_EQ(log.get_warnings(), "[\n]");
  EXPECT_EQ(log.get_errors(), "[\n]");
  EXPECT_EQ(log.get_warning_count(), 0);
  EXPECT_EQ(log.get_error_count(), 0);
}

// Edge handling
TEST(FIMSLog_clear, HandlesEmptyLogger) {
  // Setup a logger with no entries.
  fims::FIMSLog log = MakeLogger();

  // Test that calling clear on an empty logger is a no-op.
  EXPECT_NO_THROW(log.clear());
  EXPECT_EQ(log.get_log(), "[\n]");
  EXPECT_EQ(log.get_warning_count(), 0);
  EXPECT_EQ(log.get_error_count(), 0);
}

// Error handling
TEST(FIMSLog_clear, PreservesPathAndThrowOnErrorConfiguration) {
  // Setup a logger with custom configuration and at least one entry.
  fims::FIMSLog log = MakeLogger();
  log.set_path("custom/fims_test.log");
  log.throw_on_error = true;
  log.warning_message("warning before clear", 40, "../tmp/config.cpp", "ConfigRoutine");

  // Test that clear preserves configured path and throw_on_error behavior.
  log.clear();

  EXPECT_EQ(log.get_path(), "custom/fims_test.log");
  EXPECT_TRUE(log.throw_on_error);

  // Test that throw_on_error still applies after clear.
  EXPECT_THROW(
    log.error_message("error after clear", 50, "../tmp/config.cpp", "ConfigRoutine"),
    std::runtime_error
  );
}

TEST(FIMSLog_write_on_exit, WritesLogToConfiguredPathOnDestruction) {
  // Setup a unique file path and ensure it does not exist before the test.
  const std::string file_path = "fimslog_write_on_exit_test.json";
  std::remove(file_path.c_str());

  {
    fims::FIMSLog log;
    log.write_on_exit = true;
    log.throw_on_error = false;
    log.set_path(file_path);
    log.info_message("written on exit", 77, "../tmp/write.cpp", "WriteRoutine");
  }

  std::ifstream in(file_path);
  ASSERT_TRUE(in.is_open());
  std::stringstream buffer;
  buffer << in.rdbuf();
  in.close();

  const std::string file_contents = buffer.str();
  EXPECT_NE(file_contents.find("written on exit"), std::string::npos);
  EXPECT_NE(file_contents.find("\"level\": \"info\""), std::string::npos);

  std::remove(file_path.c_str());
}

}  // namespace
