// Instructions ----
// This file follows the format generated by FIMS:::use_gtest_template().
// Necessary tests include input and output (IO) correctness [IO
// correctness], edge-case handling [Edge handling], and built-in errors and
// warnings [Error handling]. See `?FIMS:::use_gtest_template` for more
// information. Every test should have a description comment.
// More assertion macros provided by GoogleTest can be found at
// https://google.github.io/googletest/reference/assertions.html.

#include "gtest/gtest.h"
#include "population/population.hpp"
#include "../../tests/gtest/test_population_test_fixture.hpp"

namespace {
// CatchAtAge_CalculateCatchWeightAA
// IO correctness
TEST_F(CAAEvaluateTestFixture,
       HandlesCorrectInput_CatchAtAge_CalculateCatchWeightAA) {
  // Fleet 0 has its own weight at age and fleet 1 uses the population weight
  // at age
  std::shared_ptr<fims_popdy::Fleet<double>>& fleet_with_weight =
      population->fleets[0];
  fleet_with_weight->weight_at_age.resize(n_years * n_ages);
  for (size_t i = 0; i < fleet_with_weight->weight_at_age.size(); i++) {
    fleet_with_weight->weight_at_age[i] = 0.1 * static_cast<double>(i + 1);
  }

  catch_at_age_model->CalculateCatchNumbersAA(population, i_age_year, year,
                                              age);
  catch_at_age_model->CalculateCatchWeightAA(population, year, age);
  catch_at_age_model->CalculateIndexNumbersAA(population, i_age_year, year,
                                              age);
  catch_at_age_model->CalculateIndexWeightAA(population, year, age);

  double population_weight =
      population->growth->evaluate(year, population->ages[age]);
  auto& dq_fleet_with_weight =
      catch_at_age_model->GetFleetDerivedQuantities(fleet_with_weight->GetId());
  auto& dq_fleet_without_weight = catch_at_age_model->GetFleetDerivedQuantities(
      population->fleets[1]->GetId());

  // Test that a fleet with its own weight at age uses it for its catch and
  // index weight at age.
  EXPECT_DOUBLE_EQ(dq_fleet_with_weight["catch_weight_at_age"][i_age_year],
                   dq_fleet_with_weight["catch_numbers_at_age"][i_age_year] *
                       fleet_with_weight->weight_at_age[i_age_year]);
  EXPECT_DOUBLE_EQ(dq_fleet_with_weight["index_weight_at_age"][i_age_year],
                   dq_fleet_with_weight["index_numbers_at_age"][i_age_year] *
                       fleet_with_weight->weight_at_age[i_age_year]);

  // Test that a fleet without its own weight at age uses the population
  // weight at age.
  EXPECT_DOUBLE_EQ(dq_fleet_without_weight["catch_weight_at_age"][i_age_year],
                   dq_fleet_without_weight["catch_numbers_at_age"][i_age_year] *
                       population_weight);
  EXPECT_DOUBLE_EQ(dq_fleet_without_weight["index_weight_at_age"][i_age_year],
                   dq_fleet_without_weight["index_numbers_at_age"][i_age_year] *
                       population_weight);
}
}  // namespace
