# Instructions ----
#' This file follows the format generated by FIMS:::use_testthat_template().
#' Necessary tests include input and output (IO) correctness [IO
#' correctness], edge-case handling [Edge handling], and built-in errors and
#' warnings [Error handling]. See `?FIMS:::use_testthat_template` for more
#' information. Every test should have a @description tag that takes up just
#' one line, which will be used in the bookdown report of {testthat} results.

# {{{ function_name }}} ----
## Setup ----
# Load or prepare any necessary data for testing

## IO correctness ----
test_that("{{{ function_name }}}() works with correct inputs", {
  #' @description Test that {{{ function_name }}}(x) returns y.
  expect_equal(
    object = {{{ function_name }}}(x),
    expected = y
  )

  #' @description Test that {{{ function_name }}}(x) returns y.
  expect_equal(
    object = {{{ function_name }}}(x),
    expected = y
  )
})

## Edge handling ----
# Please remove/comment out the test template below if no edge cases are being tested.
test_that("{{{ function_name }}}() returns correct outputs for edge cases", {
  #' @description Test that {{{ function_name }}}(x) returns an error.
  expect_error(
    object = {{{ function_name }}}(x)
  )
})

## Error handling ----
# Please remove/comment out the test template below if there are no built-in errors/warnings.
test_that("{{{ function_name }}}() returns correct error messages", {
  #' @description Test that {{{ function_name }}}(x) returns expected error.
  expect_error(
    object = {{{ function_name }}}(x),
    regexp = "Insert text here that should be in the error message."
  )
})
