include_root <- "inst/include"
src_dir      <- "src"

dir.create(src_dir, showWarnings = FALSE)

# Recursively find all .hpp files
files <- list.files(include_root,
                    pattern = "\\.hpp$",
                    recursive = TRUE,
                    full.names = TRUE)

# Encode full relative path into unique filename
encode_name <- function(path) {
  rel <- sub(paste0("^", include_root, "/"), "", path)
  rel <- sub("\\.hpp$", "", rel)
  rel <- gsub("/", "_", rel)
  paste0("F_", rel)
}

generated_headers <- character()

for (file in files) {

  encoded_base <- encode_name(file)
  out_h   <- file.path(src_dir, paste0(encoded_base, ".h"))
  out_cpp <- file.path(src_dir, paste0(encoded_base, ".cpp"))

  cat("Generating", out_h, "\n")

  txt <- readLines(file, warn = FALSE)

  # Rewrite FIMS_DEPENDS(x/y/z.hpp)
pattern <- "FIMS_DEPENDS\\(([^)]+)\\.hpp\\);"

for (i in seq_along(txt)) {

  if (grepl(pattern, txt[i])) {

    match <- regmatches(txt[i], regexec(pattern, txt[i]))[[1]]
    dep_name <- match[2]          # e.g. "model" or "path/to/model"

    # If no slash, search for it
    if (!grepl("/", dep_name)) {

      candidates <- files[basename(files) == paste0(dep_name, ".hpp")]

      if (length(candidates) == 0) {
        stop("Cannot resolve dependency: ", dep_name)
      }

      if (length(candidates) > 1) {
        cat("Ambiguous dependency: ", dep_name, " — multiple matches found.\n")
      }

      dep_full <- sub(paste0("^", include_root, "/"), "", candidates)

    } else {
      dep_full <- dep_name
    }
    dep_full <- stringr::str_remove(dep_full, "\\.hpp")
    dep_encoded <- paste0("F_", gsub("/", "_", dep_full), ".h")

    txt[i] <- paste0("#include \"", dep_encoded, "\"")
  }
}

#   # Write generated header
  writeLines(
    c(
      "// Autogenerated",
      "#define WITH_LIBTMB",
      "//#include <TMB.h>",
      txt
    ),
    out_h
  )

  # Write corresponding cpp
  writeLines(
    c(
      "// Autogenerated",
      "#define WITH_LIBTMB",
      paste0("#include \"", basename(out_h), "\"")
    ),
    out_cpp
  )

  generated_headers <- c(generated_headers, basename(out_h))
}

# Generate umbrella header
writeLines(
  c("// Autogenerated FIMS umbrella",
    paste0("#include \"", generated_headers, "\"")),
  file.path(src_dir, "FIMS.h")
)


