# ---
# repo: NOAA-FIMS/FIMS
# file: standalone-use-testthat-template.R
# last-updated: 2026-04-30
# license: https://unlicense.org
# imports: cli
# ---
#
# This file is a standalone function for using testthat template, which
# is used to create new test files for the testthat framework in R. The function
# can be used across packages by running
# usethis::use_standalone("NOAA-FIMS/FIMS", file = "use-testthat-template").
# The function creates a new test file based on a template and ensures that the
# file does not already exist before creating it.
#
# ## Changelog
# 2026-04-30:
# - Initial version of standalone test template generator.
#
# nocov start

#' Create tests/testthat/test-*.R test file
#'
#' This helper function creates a new test file for testthat using a template
#' inside `.get_testthat_template()`. The test file is
#' created under the "tests/testthat" directory with a name based on the input
#' argument `name`. If the test file already exists, an error message is
#' returned and no changes are made.
#'
#' @details
#' There are three minimum testing criteria for the package, which should be validated
#' for every R function within the package. The template file sets up a
#' section for each of the three following test criteria:
#'
#' 1. Input and output correctness (IO correctness): ensure that the function
#'    behaves as expected with correct inputs and returns the expected outputs.
#' 1. Edge-case handling (Edge handling): validate the function's performance
#'    with invalid inputs and unusual scenarios.
#' 1. Built-in errors and warnings (Error handling): confirm that appropriate
#'    error and warning messages are triggered under exceptional conditions.
#'
#' @param name A character string providing the name of the R function that you
#'   want to test. The name will be used to create the file name, i.e.,
#'   `tests/testthat/test-{name}.R`. If `name` is not specified, the function
#'   will not be able to create a file name and an error will be returned.
#'
#' @return
#' If successful, this function invisibly returns `TRUE` to allow for the
#' chaining of commands. If the function is unsuccessful, an error message is
#' returned.
#'
#' A message is returned that states the file path of the newly created file.
#' The file will not be automatically opened.
#'
#' @examples
#' # Create a new test file named "test-new_function" for `new_function()`
#' \dontrun{
#' package_name:::use_testthat_template("new_function")
#' }
#'
#' @keywords developer
use_testthat_template <- function(name) {
  # TODO: add the ability to add a function to a file that already exists
  # TODO: add the ability to also pass the arguments for the function or find
  #       them within the code base and ensure that the template includes the
  #       necessary structure for each input argument
  if (missing(name) || is.null(name) || name == "") {
    cli::cli_abort("{.arg name} must be specified to create a test file.")
  }
  # Look for DESCRIPTION in the current working directory only
  description_file <- "DESCRIPTION"

  if (!file.exists(description_file)) {
    cli::cli_abort(c(
      "x" = "Could not find a {.path DESCRIPTION} file in the current directory.",
      "i" = "Please ensure you are at the root of your R package project."
    ))
  }

  # Extract the package name
  package_name <- read.dcf(description_file, fields = "Package")[1, 1]

  # Create test file path
  path <- file.path("tests", "testthat", paste0("test-", name, ".R"))

  if (file.exists(path)) {
    cli::cli_abort("The file {.path {path}} already exists.")
  }

  template_text <- .get_testthat_template()
  function_name <- gsub("-", "_", name)
  # Replace both function name and package name in the template
  final_content <- gsub("{{{ function_name }}}", function_name, template_text, fixed = TRUE)
  final_content <- gsub("{{{ package_name }}}", package_name, final_content, fixed = TRUE)

  # Create directory and write
  if (!dir.exists(dirname(path))) {
    dir.create(dirname(path), recursive = TRUE)
  }

  writeLines(final_content, path)
  cli::cli_alert_success(c("v" = "Setting up tests for {.val {path}} in {.pkg {package_name}}"))

  invisible(TRUE)
}

.get_testthat_template <- function() {
  r"(# Instructions ----
# This file follows the format generated by {{{ package_name }}}:::use_testthat_template().
# Necessary tests include input and output (IO) correctness [IO
# correctness], edge-case handling [Edge handling], and built-in errors and
# warnings [Error handling]. See `?{{{ package_name }}}:::use_testthat_template` for more
# information. Add clear comments to document each test_that() block and each
# expectation so the test intent is easy to understand.

# {{{ function_name }}} ----
## Setup ----
# Load or prepare any necessary data for testing

## IO correctness ----
# Add one or more test_that() blocks for IO correctness.
# Each test_that() block can include multiple checks with documentation comments.
test_that("{{{ function_name }}}() returns expected output for standard valid input", {
  # Document what this check validates.
  expect_equal(
    object = {{{ function_name }}}(x),
    expected = y
  )

  # Document what this check validates.
  expect_equal(
    object = {{{ function_name }}}(a),
    expected = b
  )
})

# Add another IO correctness test_that() block as needed.
# Please remove/comment out the test_that() block below if there are no
# additional IO correctness tests.
test_that("{{{ function_name }}}() returns expected output for <scenario>", {
  # Document what this check validates.
  expect_equal(object = {{{ function_name }}}(<input>), expected = <expected output>)
})

## Edge handling ----
# Add one or more test_that() blocks for edge-case handling.
# Please remove/comment out the test template below if no edge cases are being tested.
test_that("{{{ function_name }}}() handles invalid or boundary inputs as expected", {
  # Document what this check validates.
  expect_error(
    object = {{{ function_name }}}(x)
  )
})

## Error handling ----
# Add one or more test_that() blocks for built-in errors and warnings.
# Please remove/comment out the test template below if there are no built-in errors/warnings.
test_that("{{{ function_name }}}() reports the expected error or warning message", {
  # Document what this check validates.
  expect_error(
    object = {{{ function_name }}}(x),
    regexp = "Insert text here that should be in the error message."
  )
})
)"
}
# nocov end
