# Runs covr::codecov() to calculate code coverage.
name: call-calc_coverage

on:
  pull_request:
    branches:
      - dev
      - main
    paths-ignore:
      - .devcontainer
      - .github
      - '.gitignore'
      - '.Rbuildignore'
      - 'CONTRIBUTING.md'
      - 'LICENSE'
      - 'man'
      - 'README.md'
  push:
    branches:
      - dev
    paths-ignore:
      - .devcontainer
      - .github
      - '.gitignore'
      - '.Rbuildignore'
      - 'CONTRIBUTING.md'
      - 'LICENSE'
      - 'man'
      - 'README.md'
  workflow_dispatch:
 
jobs:
  call-workflow:
    uses: nmfs-fish-tools/ghactions4r/.github/workflows/calc-coverage.yml@main
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

