# Runs R CMD CHECK on the package.
name: call-r-cmd-check

on:
  push:
  workflow_dispatch:

jobs:
  call-workflow:
    uses: nmfs-fish-tools/ghactions4r/.github/workflows/r-cmd-check.yml@main
    with: 
      gha_timeout_minutes: 60
      
