# Run clang-tidy
name: Clang-tidy

on:
  # The default build trigger is to run the action on every push and pull request, for any branch
  push:
  pull_request:
  # To run the default repository branch weekly on sunday, uncomment the following 2 lines
  #schedule:
    #- cron: '0 0 * * 0'

jobs:
  checkout-and-check-formatting:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run clang-tidy
      uses: HorstBaerbel/action-clang-tidy@1.2
      # These are optional (defaults displayed)
      with:
        scandir: '.'
        builddir: 'build'
        excludedirs: ''
        extensions: 'c,h,C,H,cpp,hpp,cc,hh,c++,h++,cxx,hxx'
        cmakeoptions: ''
