name: call-spell-check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  cspell:
    uses: noaa-fims/.github/.github/workflows/cspell.yml@main
