name: clang-format

on:
  push:
  pull_request:

jobs:
  clang-format:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    if: github.actor != 'github-actions[bot]'

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Run clang-format
        uses: DoozyX/clang-format-lint-action@v0.20
        with:
          source: './inst/include ./src ./tests/gtest'
          extensions: 'hpp, cpp'
          style: "{BasedOnStyle: Google, SortIncludes: false}"
          inplace: True

      - name: Commit formatting changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git diff --quiet && exit 0

          git add .
          git commit -m "Apply clang-format"
          git push
