# .github/workflows/pr-commands.yml
on:
  issue_comment:
    types: [created]

name: pr-commands

permissions: read-all

jobs:
  doc_and_style:
    if: ${{ github.event.issue.pull_request && 
            (github.event.comment.author_association == 'MEMBER' || github.event.comment.author_association == 'OWNER') &&
            (startsWith(github.event.comment.body, '/document-r') || startsWith(github.event.comment.body, '/style-r')) }}
    name: Document and Style
    uses: ./.github/workflows/call-doc-and-style-r.yml
    secrets: inherit
