on:
  # TODO: uncomment branches when ready
  push:
    # branches: [dev]
  pull_request:
    # branches: [dev]

name: r-universe-R-CMD-check.yaml

permissions: read-all

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          # corresponds to MacOS arm64
          - {os: macos-14,   r: 'release'}
          - {os: macos-14,   r: 'oldrel-1'}
          # corresponds to MacOS x86_64
          - {os: macos-13, r: 'release'}
          - {os: macos-13, r: 'oldrel-1'}
          # corresponds to Windows
          - {os: windows-2022, r: 'release'}
          - {os: windows-2022,  r: 'devel'}
          - {os: windows-2022, r: 'oldrel-1'}
          # corresponds to Linux x86_64
          - {os: ubuntu-24.04,  r: 'release'}
          - {os: ubuntu-24.04,  r: 'devel', http-user-agent: 'release'}
          # corresponds to Linux arm64
          - {os: ubuntu-24.04-arm,  r: 'release'}
          - {os: ubuntu-24.04-arm,  r: 'devel', http-user-agent: 'release'}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-pandoc@v2

      - name: Install TinyTeX
        uses: r-lib/actions/setup-tinytex@v2 
      
      - name: Install Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      # - uses: r-lib/actions/setup-r-dependencies@v2
      #   with:
      #     extra-packages: any::rcmdcheck
      #     needs: check

      - name: Get dependencies
        run: |
          cat('::group::Show build environment\n')
          cat(Sys.which('gcc'), "\n")
          invisible(system("gcc --version"))
          print(as.list(getOption('repos')))
          cat(readLines(Sys.getenv('R_ENVIRON_USER')), sep = '\n')
          cat('::endgroup::\n')

          write_output <- function(key, value){
            cat(paste0(key, '=', value, '\n'), file = Sys.getenv("GITHUB_OUTPUT"), append = TRUE)
          }
          write_output('rversion', getRversion())

          # Do not try to install base packages
          skiplist <- c("R", row.names(installed.packages(priority="base")))

          #cat('::group::Install package dependencies\n')
          dir.create(Sys.getenv('R_LIBS_USER'), recursive = TRUE, showWarnings = FALSE)
          sourcepkg <- commandArgs(TRUE)[1]

          # Derive all dependencies
          filename <- sub("_.*", "/DESCRIPTION", basename(sourcepkg))
          untar(sourcepkg, filename, extras = '--strip=1')
          desc <- as.data.frame(read.dcf("DESCRIPTION"))
          unlink('DESCRIPTION')
          deps <- c(desc$Depends, desc$Imports, desc$LinkingTo, desc$Suggests, desc$Enhances)
          pkg_deps <- unique(trimws(sub("\\(.*\\)", "", unlist(strsplit(as.character(deps), ',')))))
          pkg_deps <- setdiff(pkg_deps, skiplist)

          # Add Additional_repositories
          if(length(desc$Additional_repositories)){
            addrepos <- trimws(strsplit(desc$Additional_repositories, ",", fixed=TRUE)[[1]])
            addrepos <- grep('^https?://\\S+$', addrepos, value = TRUE)
            addrepos <- grep(Sys.getenv("MY_UNIVERSE"), fixed = TRUE, addrepos, value = TRUE, invert = TRUE)
            message("Additional_repositories: ", paste(addrepos, collapse = ', '))
            options(repos = c(getOption('repos'), addrepos))
          }

          # Install sysdeps (Linux only)
          if(grepl("linux", R.Version()$platform)) {
            sysreqs <- gsub("\\s+", " ", desc[['Config/pak/sysreqs']])
            if(length(sysreqs)){
              cat("Installing sysreqs:", sysreqs, "\n")
              system("apt-get update")
              system(paste("apt-get install -y", sysreqs))
            }
          }

          # Hack for bioc mess
          #if(identical('bioc', Sys.getenv('UNIVERSE_NAME'))){
          #  pkg_deps <- c(pkg_deps, "zlibbioc")
          #}

          # Temp fix
          # if(.Platform$OS.type == 'windows' && R.version$minor == '6.0'){
          #  install.packages('data.table', repos = 'https://test.r-universe.dev')
          # }

          # Install new packages
          options(install.packages.check.source = "no")
          options("install.packages.compile.from.source"="never")

          # Somehow 'install.packages.check.source=no' still installs packages w/o compiled code from src
          # But we also need transitive deps that are not available as binary such as bioconductor data packages
          if(.Platform$OS.type == 'windows'){
            install.packages(pkg_deps, type = 'win.binary')
            alldeps <- unique(unname(c(pkg_deps, unlist(tools::package_dependencies(pkg_deps, recursive = TRUE)))))
            missingdeps <- setdiff(alldeps, c(skiplist, row.names(installed.packages())))
            install.packages(missingdeps)
          } else {
            install.packages(pkg_deps)
          }

          # Update pre-installed and outdated binary packages
          options(install.packages.check.source = NULL)
          options("install.packages.compile.from.source"="interactive")
          update.packages(oldPkgs = pkg_deps, type = 'source', ask = FALSE)

          # Test again if any are missing, try with remotes
          installed <- row.names(installed.packages())
          unavail <- setdiff(pkg_deps, installed)
          if(length(unavail)) {
            warning("Installing from remotes: ", paste(unavail, collapse = ','))
            install.packages('remotes')
            remotes::install_deps(sourcepkg, dependencies = TRUE, upgrade = FALSE)
          }
        shell: Rscript {0}

      - name: Run R-universe check 
        id: rcmdcheck
        run: |
          # Crucial: Enable 'pipefail' and 'exit on error' for robust scripting
          # This applies to all OSes running this Bash script.
          {
            set -euo pipefail
            # -e: Exit immediately if a command exits with a non-zero status.
            # -u: Treat unset variables as an error.
            # -o pipefail: Ensures that a command failing in a pipeline causes the 
            # pipeline to fail.
            # Set environment variables 
            export FIMS="."
            export CHECKARGS="--no-manual --no-vignettes"
            export MY_R_LIB="${{ github.workspace }}/../mylib"

            # Create library directory 
             mkdir -p "$MY_R_LIB"
            
            # Run R CMD INSTALL and capture output to log file and console
            # Due to 'set -o pipefail', if R CMD INSTALL fails, the whole line 
            # will cause script to exit.
            echo "Running R CMD INSTALL..."
            # Run R CMD INSTALL and capture output to log file and console 
            R CMD INSTALL "$FIMS" --library="$MY_R_LIB" --build 

            # Run R CMD check. This command's exit code will determine step success/failure.
            # R CMD check "$FIMS" --library="$MY_R_LIB" --install=check:install.log "$CHECKARGS" 
            R CMD check "$FIMS" --library="$MY_R_LIB" "$CHECKARGS"
          } 2>&1 | tee install_check.log
        shell: bash
        
      - name: Upload check results on failure
        if: failure() # This step will only run if a previous step in the job failed
        uses: actions/upload-artifact@main
        with:
          # Unique name for the artifact per OS
          name: ${{ matrix.config.os }}-r${{ matrix.config.r }}-results
          path: install_check.log