# Tests R-universe builds when manually dispatched.
name: Test R-universe

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: R-universe testing
    uses: r-universe-org/workflows/.github/workflows/build.yml@v3
    with:
      universe: ${{ github.repository_owner }}
