# Runs usethis::git_vaccinate() to update .gitignore file with best practices
# twice a year and creates a PR to the dev branch.
name: vaccinate-gitignore

on:
  schedule:
    # Run on January 15th at 10:00 UTC
    - cron: '0 10 15 1 *'
    # Run on July 15th at 10:00 UTC
    - cron: '0 10 15 7 *'
  workflow_dispatch:

jobs:
  vaccinate:
    name: Vaccinate .gitignore file
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v6
      with:
        ref: dev
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Setup R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.1.0'
    
    - name: Install usethis
      run: |
        install.packages("usethis")
      shell: Rscript {0}
    
    - name: Run git_vaccinate
      run: |
        usethis::git_vaccinate()
      shell: Rscript {0}
    
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v8
      with:
        commit-message: 'chore(.gitignore): Vaccinates the .gitignore file'
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: vaccinate-gitignore-${{ github.run_number }}
        base: dev
        title: 'chore(.gitignore): Vaccinates the .gitignore file'
        body: |
          This PR updates the .gitignore file using `usethis::git_vaccinate()` to add recommended patterns for commonly-generated files.
          
          Auto-generated by [vaccinate-gitignore.yml][1]
          
          [1]: https://github.com/NOAA-FIMS/FIMS/blob/main/.github/workflows/vaccinate-gitignore.yml
        labels: |
          status: in progress
          kind: refactor
        reviewers: NOAA-FIMS/project-lead
